/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-transport-line-common.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-transport-line-common.yang */
public class openconfigTransportLineCommon extends ConfNamespace {
    public static final int hash = 1343105134;
    public int hash() {
        return openconfigTransportLineCommon.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/transport-line-common";
    public String id() {
        return openconfigTransportLineCommon.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/transport-line-common";
    public String uri() {
        return openconfigTransportLineCommon.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigTransportLineCommon.uri);
    }

    public static final String prefix = "oc-line-com";
    public String prefix() {
        return openconfigTransportLineCommon.prefix;
    }

    public openconfigTransportLineCommon() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _max = 2088175689;
    public static final String _max_ = "max";
    public static final int    _optical_port = 1841497737;
    public static final String _optical_port_ = "optical-port";
    public static final int    _interval = 559952988;
    public static final String _interval_ = "interval";
    public static final int    _min_time = 1805904672;
    public static final String _min_time_ = "min-time";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _min = 83205090;
    public static final String _min_ = "min";
    public static final int    _admin_state = 1519849494;
    public static final String _admin_state_ = "admin-state";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _output_power = 571387945;
    public static final String _output_power_ = "output-power";
    public static final int    _avg = 2050512522;
    public static final String _avg_ = "avg";
    public static final int    _tilt = 1895297389;
    public static final String _tilt_ = "tilt";
    public static final int    _max_time = 1093347309;
    public static final String _max_time_ = "max-time";
    public static final int    _optical_port_type = 417765295;
    public static final String _optical_port_type_ = "optical-port-type";
    public static final int    _instant = 2051543381;
    public static final String _instant_ = "instant";
    public static final int    _sonet = 1768993483;
    public static final String _sonet_ = "sonet";
    public static final int    _input_power = 1019491846;
    public static final String _input_power_ = "input-power";
}
