/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-license.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-license.yang */
public class openconfigLicense extends ConfNamespace {
    public static final int hash = 1208096034;
    public int hash() {
        return openconfigLicense.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/license";
    public String id() {
        return openconfigLicense.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/license";
    public String uri() {
        return openconfigLicense.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigLicense.uri);
    }

    public static final String prefix = "oc-license";
    public String prefix() {
        return openconfigLicense.prefix;
    }

    public openconfigLicense() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
