/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-packet-match.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-packet-match.yang */
public class openconfigPacketMatch extends ConfNamespace {
    public static final int hash = 148412667;
    public int hash() {
        return openconfigPacketMatch.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/header-fields";
    public String id() {
        return openconfigPacketMatch.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/header-fields";
    public String uri() {
        return openconfigPacketMatch.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigPacketMatch.uri);
    }

    public static final String prefix = "oc-pkt-match";
    public String prefix() {
        return openconfigPacketMatch.prefix;
    }

    public openconfigPacketMatch() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
