/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-optical-attenuator.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-optical-attenuator.yang */
public class openconfigOpticalAttenuator extends ConfNamespace {
    public static final int hash = 82622882;
    public int hash() {
        return openconfigOpticalAttenuator.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/optical-attenuator";
    public String id() {
        return openconfigOpticalAttenuator.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/optical-attenuator";
    public String uri() {
        return openconfigOpticalAttenuator.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigOpticalAttenuator.uri);
    }

    public static final String prefix = "oc-opt-att";
    public String prefix() {
        return openconfigOpticalAttenuator.prefix;
    }

    public openconfigOpticalAttenuator() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _max = 2088175689;
    public static final String _max_ = "max";
    public static final int    _optical_return_loss = 1136259073;
    public static final String _optical_return_loss_ = "optical-return-loss";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _CONSTANT_POWER = 768939509;
    public static final String _CONSTANT_POWER_ = "CONSTANT_POWER";
    public static final int    _interval = 559952988;
    public static final String _interval_ = "interval";
    public static final int    _min_time = 1805904672;
    public static final String _min_time_ = "min-time";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _CONSTANT_ATTENUATION = 1222932250;
    public static final String _CONSTANT_ATTENUATION_ = "CONSTANT_ATTENUATION";
    public static final int    _attenuator = 1212311396;
    public static final String _attenuator_ = "attenuator";
    public static final int    _target_output_power = 1907745428;
    public static final String _target_output_power_ = "target-output-power";
    public static final int    _attenuation = 1694846668;
    public static final String _attenuation_ = "attenuation";
    public static final int    _actual_attenuation = 1772148530;
    public static final String _actual_attenuation_ = "actual-attenuation";
    public static final int    _min = 83205090;
    public static final String _min_ = "min";
    public static final int    _OPTICAL_ATTENUATOR_MODE = 121803556;
    public static final String _OPTICAL_ATTENUATOR_MODE_ = "OPTICAL_ATTENUATOR_MODE";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _avg = 2050512522;
    public static final String _avg_ = "avg";
    public static final int    _attenuation_mode = 1317618666;
    public static final String _attenuation_mode_ = "attenuation-mode";
    public static final int    _max_time = 1093347309;
    public static final String _max_time_ = "max-time";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _component = 1543026623;
    public static final String _component_ = "component";
    public static final int    _instant = 2051543381;
    public static final String _instant_ = "instant";
    public static final int    _attenuators = 1513078613;
    public static final String _attenuators_ = "attenuators";
    public static final int    _optical_attenuator = 203879888;
    public static final String _optical_attenuator_ = "optical-attenuator";
    public static final int    _output_power_total = 764719814;
    public static final String _output_power_total_ = "output-power-total";
    public static final int    _egress_port = 389091880;
    public static final String _egress_port_ = "egress-port";
    public static final int    _ingress_port = 1493679030;
    public static final String _ingress_port_ = "ingress-port";
}
