/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-mpls.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-mpls.yang */
public class openconfigMpls extends ConfNamespace {
    public static final int hash = 845238616;
    public int hash() {
        return openconfigMpls.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/mpls";
    public String id() {
        return openconfigMpls.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/mpls";
    public String uri() {
        return openconfigMpls.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigMpls.uri);
    }

    public static final String prefix = "oc-mpls";
    public String prefix() {
        return openconfigMpls.prefix;
    }

    public openconfigMpls() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
