/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-ate-flow.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-ate-flow.yang */
public class openconfigAteFlow extends ConfNamespace {
    public static final int hash = 2044181494;
    public int hash() {
        return openconfigAteFlow.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ate-flow";
    public String id() {
        return openconfigAteFlow.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ate-flow";
    public String uri() {
        return openconfigAteFlow.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigAteFlow.uri);
    }

    public static final String prefix = "oc-flow";
    public String prefix() {
        return openconfigAteFlow.prefix;
    }

    public openconfigAteFlow() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _out_pkts = 335453834;
    public static final String _out_pkts_ = "out-pkts";
    public static final int    _vlan_id = 1443431623;
    public static final String _vlan_id_ = "vlan-id";
    public static final int    _ingress_tracking = 1892045289;
    public static final String _ingress_tracking_ = "ingress-tracking";
    public static final int    _out_octets = 2123582464;
    public static final String _out_octets_ = "out-octets";
    public static final int    _mpls_label = 837233201;
    public static final String _mpls_label_ = "mpls-label";
    public static final int    _out_rate = 268343224;
    public static final String _out_rate_ = "out-rate";
    public static final int    _src_ipv6 = 1462489351;
    public static final String _src_ipv6_ = "src-ipv6";
    public static final int    _egress_tracking = 1932020689;
    public static final String _egress_tracking_ = "egress-tracking";
    public static final int    _in_rate = 1162687589;
    public static final String _in_rate_ = "in-rate";
    public static final int    _convergence_time = 95415173;
    public static final String _convergence_time_ = "convergence-time";
    public static final int    _in_pkts = 1264605324;
    public static final String _in_pkts_ = "in-pkts";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _dst_port = 645748677;
    public static final String _dst_port_ = "dst-port";
    public static final int    _out_frame_rate = 1804018206;
    public static final String _out_frame_rate_ = "out-frame-rate";
    public static final int    _src_port = 557457527;
    public static final String _src_port_ = "src-port";
    public static final int    _flow = 2144387363;
    public static final String _flow_ = "flow";
    public static final int    _filter = 518848087;
    public static final String _filter_ = "filter";
    public static final int    _dst_ipv6 = 21236723;
    public static final String _dst_ipv6_ = "dst-ipv6";
    public static final int    _src_ipv4 = 1086341483;
    public static final String _src_ipv4_ = "src-ipv4";
    public static final int    _counters = 1327053922;
    public static final String _counters_ = "counters";
    public static final int    _in_frame_rate = 795492677;
    public static final String _in_frame_rate_ = "in-frame-rate";
    public static final int    _in_octets = 1354763654;
    public static final String _in_octets_ = "in-octets";
    public static final int    _loss_pct = 448149829;
    public static final String _loss_pct_ = "loss-pct";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _first_packet_latency = 1030721531;
    public static final String _first_packet_latency_ = "first-packet-latency";
    public static final int    _dst_ipv4 = 1448372914;
    public static final String _dst_ipv4_ = "dst-ipv4";
    public static final int    _flows = 1866960985;
    public static final String _flows_ = "flows";
}
