/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-macsec.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-macsec.yang */
public class openconfigMacsec extends ConfNamespace {
    public static final int hash = 536728785;
    public int hash() {
        return openconfigMacsec.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/macsec";
    public String id() {
        return openconfigMacsec.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/macsec";
    public String uri() {
        return openconfigMacsec.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigMacsec.uri);
    }

    public static final String prefix = "oc-macsec";
    public String prefix() {
        return openconfigMacsec.prefix;
    }

    public openconfigMacsec() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _sa_invalid = 1367441760;
    public static final String _sa_invalid_ = "sa-invalid";
    public static final int    _out_sak_mkpdu = 2048313186;
    public static final String _out_sak_mkpdu_ = "out-sak-mkpdu";
    public static final int    _in_sak_mkpdu = 1484924014;
    public static final String _in_sak_mkpdu_ = "in-sak-mkpdu";
    public static final int    _out_mkpdu_errors = 101749763;
    public static final String _out_mkpdu_errors_ = "out-mkpdu-errors";
    public static final int    _out_cak_mkpdu = 1078484789;
    public static final String _out_cak_mkpdu_ = "out-cak-mkpdu";
    public static final int    _mka_policy = 1297797302;
    public static final String _mka_policy_ = "mka-policy";
    public static final int    _policy = 1919655803;
    public static final String _policy_ = "policy";
    public static final int    _sa_auth_only = 1920882109;
    public static final String _sa_auth_only_ = "sa-auth-only";
    public static final int    _sak_generation_errors = 1916320277;
    public static final String _sak_generation_errors_ = "sak-generation-errors";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _sak_rekey_on_live_peer_loss = 562608463;
    public static final String _sak_rekey_on_live_peer_loss_ = "sak-rekey-on-live-peer-loss";
    public static final int    _sci_rx = 2013407749;
    public static final String _sci_rx_ = "sci-rx";
    public static final int    _key_server_priority = 1595468216;
    public static final String _key_server_priority_ = "key-server-priority";
    public static final int    _policies = 764028492;
    public static final String _policies_ = "policies";
    public static final int    _sak_encryption_errors = 1239224021;
    public static final String _sak_encryption_errors_ = "sak-encryption-errors";
    public static final int    _delay_protection = 1764680021;
    public static final String _delay_protection_ = "delay-protection";
    public static final int    _replay_protection = 1524657482;
    public static final String _replay_protection_ = "replay-protection";
    public static final int    _in_mkpdu = 2073301604;
    public static final String _in_mkpdu_ = "in-mkpdu";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _rx_badtag_pkts = 631447530;
    public static final String _rx_badtag_pkts_ = "rx-badtag-pkts";
    public static final int    _sak_rekey_interval = 1360607198;
    public static final String _sak_rekey_interval_ = "sak-rekey-interval";
    public static final int    _in_mkpdu_bad_peer_errors = 195383445;
    public static final String _in_mkpdu_bad_peer_errors_ = "in-mkpdu-bad-peer-errors";
    public static final int    _in_mkpdu_validation_errors = 607472120;
    public static final String _in_mkpdu_validation_errors_ = "in-mkpdu-validation-errors";
    public static final int    _use_updated_eth_header = 293518806;
    public static final String _use_updated_eth_header_ = "use-updated-eth-header";
    public static final int    _macsec = 1063323203;
    public static final String _macsec_ = "macsec";
    public static final int    _sc_encrypted = 1984836898;
    public static final String _sc_encrypted_ = "sc-encrypted";
    public static final int    _include_icv_indicator = 1695300568;
    public static final String _include_icv_indicator_ = "include-icv-indicator";
    public static final int    _enable = 448570367;
    public static final String _enable_ = "enable";
    public static final int    _rx_unknownsci_pkts = 224340119;
    public static final String _rx_unknownsci_pkts_ = "rx-unknownsci-pkts";
    public static final int    _sc_auth_only = 1977549854;
    public static final String _sc_auth_only_ = "sc-auth-only";
    public static final int    _out_mkpdu = 737387029;
    public static final String _out_mkpdu_ = "out-mkpdu";
    public static final int    _in_mkpdu_peer_list_errors = 707615749;
    public static final String _in_mkpdu_peer_list_errors_ = "in-mkpdu-peer-list-errors";
    public static final int    _sak_hash_errors = 1344235128;
    public static final String _sak_hash_errors_ = "sak-hash-errors";
    public static final int    _sc_invalid = 527149976;
    public static final String _sc_invalid_ = "sc-invalid";
    public static final int    _sa_valid = 1279395327;
    public static final String _sa_valid_ = "sa-valid";
    public static final int    _scsa_rx = 1660430984;
    public static final String _scsa_rx_ = "scsa-rx";
    public static final int    _confidentiality_offset = 1383962441;
    public static final String _confidentiality_offset_ = "confidentiality-offset";
    public static final int    _rx_nosci_pkts = 886080741;
    public static final String _rx_nosci_pkts_ = "rx-nosci-pkts";
    public static final int    _scsa_tx = 718953170;
    public static final String _scsa_tx_ = "scsa-tx";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _sci_tx = 1723208562;
    public static final String _sci_tx_ = "sci-tx";
    public static final int    _sc_valid = 2132774195;
    public static final String _sc_valid_ = "sc-valid";
    public static final int    _counters = 1327053922;
    public static final String _counters_ = "counters";
    public static final int    _in_cak_mkpdu = 1058276780;
    public static final String _in_cak_mkpdu_ = "in-cak-mkpdu";
    public static final int    _key_chain = 1359335192;
    public static final String _key_chain_ = "key-chain";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _mka = 1464935962;
    public static final String _mka_ = "mka";
    public static final int    _sak_cipher_mismatch_errors = 463852340;
    public static final String _sak_cipher_mismatch_errors_ = "sak-cipher-mismatch-errors";
    public static final int    _rx_untagged_pkts = 1642185061;
    public static final String _rx_untagged_pkts_ = "rx-untagged-pkts";
    public static final int    _sa_encrypted = 1947562407;
    public static final String _sa_encrypted_ = "sa-encrypted";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _macsec_cipher_suite = 2134603552;
    public static final String _macsec_cipher_suite_ = "macsec-cipher-suite";
    public static final int    _sak_decryption_errors = 327158451;
    public static final String _sak_decryption_errors_ = "sak-decryption-errors";
    public static final int    _in_mkpdu_icv_verification_errors = 524849401;
    public static final String _in_mkpdu_icv_verification_errors_ = "in-mkpdu-icv-verification-errors";
    public static final int    _tx_untagged_pkts = 660501857;
    public static final String _tx_untagged_pkts_ = "tx-untagged-pkts";
}
