/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-bfd.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-bfd.yang */
public class openconfigBfd extends ConfNamespace {
    public static final int hash = 965521844;
    public int hash() {
        return openconfigBfd.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/bfd";
    public String id() {
        return openconfigBfd.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/bfd";
    public String uri() {
        return openconfigBfd.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigBfd.uri);
    }

    public static final String prefix = "oc-bfd";
    public String prefix() {
        return openconfigBfd.prefix;
    }

    public openconfigBfd() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _local_discriminator = 968074567;
    public static final String _local_discriminator_ = "local-discriminator";
    public static final int    _last_packet_transmitted = 1121940878;
    public static final String _last_packet_transmitted_ = "last-packet-transmitted";
    public static final int    _remote_session_state = 1414644266;
    public static final String _remote_session_state_ = "remote-session-state";
    public static final int    _member_interface = 1434228746;
    public static final String _member_interface_ = "member-interface";
    public static final int    _echo = 954217248;
    public static final String _echo_ = "echo";
    public static final int    _local_diagnostic_code = 349342118;
    public static final String _local_diagnostic_code_ = "local-diagnostic-code";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _subinterface = 1294223328;
    public static final String _subinterface_ = "subinterface";
    public static final int    _micro_bfd_session = 1055177085;
    public static final String _micro_bfd_session_ = "micro-bfd-session";
    public static final int    _remote_minimum_receive_interval = 740363723;
    public static final String _remote_minimum_receive_interval_ = "remote-minimum-receive-interval";
    public static final int    _interface_ref = 952985348;
    public static final String _interface_ref_ = "interface-ref";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _subscribed_protocols = 1406157166;
    public static final String _subscribed_protocols_ = "subscribed-protocols";
    public static final int    _local_address = 856636202;
    public static final String _local_address_ = "local-address";
    public static final int    _received_packets = 458197719;
    public static final String _received_packets_ = "received-packets";
    public static final int    _last_failure_time = 2146776803;
    public static final String _last_failure_time_ = "last-failure-time";
    public static final int    _demand_mode_requested = 753081880;
    public static final String _demand_mode_requested_ = "demand-mode-requested";
    public static final int    _enable_per_member_link = 117254987;
    public static final String _enable_per_member_link_ = "enable-per-member-link";
    public static final int    _failure_transitions = 272899228;
    public static final String _failure_transitions_ = "failure-transitions";
    public static final int    _session_state = 113214794;
    public static final String _session_state_ = "session-state";
    public static final int    _remote_address = 829475023;
    public static final String _remote_address_ = "remote-address";
    public static final int    _remote_discriminator = 1231281115;
    public static final String _remote_discriminator_ = "remote-discriminator";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _remote_control_plane_independent = 1577008036;
    public static final String _remote_control_plane_independent_ = "remote-control-plane-independent";
    public static final int    _desired_minimum_tx_interval = 1752975443;
    public static final String _desired_minimum_tx_interval_ = "desired-minimum-tx-interval";
    public static final int    _async = 1368962940;
    public static final String _async_ = "async";
    public static final int    _transmitted_packets = 2089984096;
    public static final String _transmitted_packets_ = "transmitted-packets";
    public static final int    _peer = 1450174230;
    public static final String _peer_ = "peer";
    public static final int    _last_packet_received = 132602702;
    public static final String _last_packet_received_ = "last-packet-received";
    public static final int    _peers = 958391453;
    public static final String _peers_ = "peers";
    public static final int    _required_minimum_receive = 747584394;
    public static final String _required_minimum_receive_ = "required-minimum-receive";
    public static final int    _detection_multiplier = 1584191488;
    public static final String _detection_multiplier_ = "detection-multiplier";
    public static final int    _remote_authentication_enabled = 258181007;
    public static final String _remote_authentication_enabled_ = "remote-authentication-enabled";
    public static final int    _up_transitions = 649368090;
    public static final String _up_transitions_ = "up-transitions";
    public static final int    _remote_diagnostic_code = 102118665;
    public static final String _remote_diagnostic_code_ = "remote-diagnostic-code";
    public static final int    _bfd = 788285710;
    public static final String _bfd_ = "bfd";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _active = 124277386;
    public static final String _active_ = "active";
    public static final int    _micro_bfd_sessions = 1052751491;
    public static final String _micro_bfd_sessions_ = "micro-bfd-sessions";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
}
