/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-spanning-tree.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-spanning-tree.yang */
public class openconfigSpanningTree extends ConfNamespace {
    public static final int hash = 911567060;
    public int hash() {
        return openconfigSpanningTree.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/spanning-tree";
    public String id() {
        return openconfigSpanningTree.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/spanning-tree";
    public String uri() {
        return openconfigSpanningTree.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigSpanningTree.uri);
    }

    public static final String prefix = "oc-stp";
    public String prefix() {
        return openconfigSpanningTree.prefix;
    }

    public openconfigSpanningTree() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _vlan_id = 1443431623;
    public static final String _vlan_id_ = "vlan-id";
    public static final int    _designated_bridge_address = 836890722;
    public static final String _designated_bridge_address_ = "designated-bridge-address";
    public static final int    _loop_guard = 442804692;
    public static final String _loop_guard_ = "loop-guard";
    public static final int    _forwarding_delay = 989511296;
    public static final String _forwarding_delay_ = "forwarding-delay";
    public static final int    _guard = 629105066;
    public static final String _guard_ = "guard";
    public static final int    _cost = 1323324755;
    public static final String _cost_ = "cost";
    public static final int    _mstp = 1730500410;
    public static final String _mstp_ = "mstp";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _mst_instance = 1793816510;
    public static final String _mst_instance_ = "mst-instance";
    public static final int    _last_topology_change = 2049708802;
    public static final String _last_topology_change_ = "last-topology-change";
    public static final int    _vlan = 71481437;
    public static final String _vlan_ = "vlan";
    public static final int    _root_cost = 96512768;
    public static final String _root_cost_ = "root-cost";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _designated_port_num = 342883633;
    public static final String _designated_port_num_ = "designated-port-num";
    public static final int    _revision = 1794066410;
    public static final String _revision_ = "revision";
    public static final int    _bpduguard_timeout_recovery = 1272873346;
    public static final String _bpduguard_timeout_recovery_ = "bpduguard-timeout-recovery";
    public static final int    _role = 1297556411;
    public static final String _role_ = "role";
    public static final int    _topology_changes = 1153771830;
    public static final String _topology_changes_ = "topology-changes";
    public static final int    _global = 1112611080;
    public static final String _global_ = "global";
    public static final int    _port_num = 325135876;
    public static final String _port_num_ = "port-num";
    public static final int    _etherchannel_misconfig_guard = 2028624239;
    public static final String _etherchannel_misconfig_guard_ = "etherchannel-misconfig-guard";
    public static final int    _port_priority = 703113541;
    public static final String _port_priority_ = "port-priority";
    public static final int    _bridge_priority = 870031236;
    public static final String _bridge_priority_ = "bridge-priority";
    public static final int    _forward_transisitions = 1910849552;
    public static final String _forward_transisitions_ = "forward-transisitions";
    public static final int    _port_state = 620517993;
    public static final String _port_state_ = "port-state";
    public static final int    _designated_port_priority = 286717165;
    public static final String _designated_port_priority_ = "designated-port-priority";
    public static final int    _hello_time = 350517458;
    public static final String _hello_time_ = "hello-time";
    public static final int    _designated_root_priority = 1113152110;
    public static final String _designated_root_priority_ = "designated-root-priority";
    public static final int    _enabled_protocol = 620126591;
    public static final String _enabled_protocol_ = "enabled-protocol";
    public static final int    _designated_root_address = 952598137;
    public static final String _designated_root_address_ = "designated-root-address";
    public static final int    _max_age = 788786427;
    public static final String _max_age_ = "max-age";
    public static final int    _link_type = 1729323344;
    public static final String _link_type_ = "link-type";
    public static final int    _bpdu_received = 1100359874;
    public static final String _bpdu_received_ = "bpdu-received";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _bridge_assurance = 1668450636;
    public static final String _bridge_assurance_ = "bridge-assurance";
    public static final int    _hold_time = 204730640;
    public static final String _hold_time_ = "hold-time";
    public static final int    _rapid_pvst = 1726275581;
    public static final String _rapid_pvst_ = "rapid-pvst";
    public static final int    _counters = 1327053922;
    public static final String _counters_ = "counters";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _max_hop = 389277615;
    public static final String _max_hop_ = "max-hop";
    public static final int    _designated_cost = 393441269;
    public static final String _designated_cost_ = "designated-cost";
    public static final int    _stp = 1701853972;
    public static final String _stp_ = "stp";
    public static final int    _edge_port = 25716128;
    public static final String _edge_port_ = "edge-port";
    public static final int    _bpdu_sent = 1464142900;
    public static final String _bpdu_sent_ = "bpdu-sent";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _mst_instances = 108128558;
    public static final String _mst_instances_ = "mst-instances";
    public static final int    _rstp = 386282833;
    public static final String _rstp_ = "rstp";
    public static final int    _designated_bridge_priority = 1256160609;
    public static final String _designated_bridge_priority_ = "designated-bridge-priority";
    public static final int    _bridge_address = 1795967590;
    public static final String _bridge_address_ = "bridge-address";
    public static final int    _bpdu_guard = 1715913620;
    public static final String _bpdu_guard_ = "bpdu-guard";
    public static final int    _bpdu_filter = 858108044;
    public static final String _bpdu_filter_ = "bpdu-filter";
    public static final int    _root_port = 1940963912;
    public static final String _root_port_ = "root-port";
    public static final int    _mst_id = 514828449;
    public static final String _mst_id_ = "mst-id";
    public static final int    _hold_count = 95029875;
    public static final String _hold_count_ = "hold-count";
}
