/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-sampling.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-sampling.yang */
public class openconfigSampling extends ConfNamespace {
    public static final int hash = 1183398364;
    public int hash() {
        return openconfigSampling.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/sampling";
    public String id() {
        return openconfigSampling.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/sampling";
    public String uri() {
        return openconfigSampling.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigSampling.uri);
    }

    public static final String prefix = "oc-sampling";
    public String prefix() {
        return openconfigSampling.prefix;
    }

    public openconfigSampling() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _sampling = 1644225525;
    public static final String _sampling_ = "sampling";
}
