/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-openflow-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-openflow-types.yang */
public class openconfigOpenflowTypes extends ConfNamespace {
    public static final int hash = 638413294;
    public int hash() {
        return openconfigOpenflowTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openflow/types";
    public String id() {
        return openconfigOpenflowTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openflow/types";
    public String uri() {
        return openconfigOpenflowTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigOpenflowTypes.uri);
    }

    public static final String prefix = "openflow-types";
    public String prefix() {
        return openconfigOpenflowTypes.prefix;
    }

    public openconfigOpenflowTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
