/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-lldp-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-lldp-types.yang */
public class openconfigLldpTypes extends ConfNamespace {
    public static final int hash = 74817316;
    public int hash() {
        return openconfigLldpTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/lldp/types";
    public String id() {
        return openconfigLldpTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/lldp/types";
    public String uri() {
        return openconfigLldpTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigLldpTypes.uri);
    }

    public static final String prefix = "oc-lldp-types";
    public String prefix() {
        return openconfigLldpTypes.prefix;
    }

    public openconfigLldpTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _TELEPHONE = 1567432922;
    public static final String _TELEPHONE_ = "TELEPHONE";
    public static final int    _TWO_PORT_MAC_RELAY = 896164942;
    public static final String _TWO_PORT_MAC_RELAY_ = "TWO_PORT_MAC_RELAY";
    public static final int    _CHASSIS_ID = 356369854;
    public static final String _CHASSIS_ID_ = "CHASSIS_ID";
    public static final int    _LLDP_SYSTEM_CAPABILITY = 1980778876;
    public static final String _LLDP_SYSTEM_CAPABILITY_ = "LLDP_SYSTEM_CAPABILITY";
    public static final int    _ROUTER = 399545655;
    public static final String _ROUTER_ = "ROUTER";
    public static final int    _SYSTEM_NAME = 877909834;
    public static final String _SYSTEM_NAME_ = "SYSTEM_NAME";
    public static final int    _REPEATER = 1691447740;
    public static final String _REPEATER_ = "REPEATER";
    public static final int    _LLDP_TLV = 393189728;
    public static final String _LLDP_TLV_ = "LLDP_TLV";
    public static final int    _SYSTEM_CAPABILITIES = 2040546183;
    public static final String _SYSTEM_CAPABILITIES_ = "SYSTEM_CAPABILITIES";
    public static final int    _PORT_ID = 659261922;
    public static final String _PORT_ID_ = "PORT_ID";
    public static final int    _SYSTEM_DESCRIPTION = 281620828;
    public static final String _SYSTEM_DESCRIPTION_ = "SYSTEM_DESCRIPTION";
    public static final int    _STATION_ONLY = 1637537553;
    public static final String _STATION_ONLY_ = "STATION_ONLY";
    public static final int    _OTHER = 187383631;
    public static final String _OTHER_ = "OTHER";
    public static final int    _C_VLAN = 842728206;
    public static final String _C_VLAN_ = "C_VLAN";
    public static final int    _MAC_BRIDGE = 138170127;
    public static final String _MAC_BRIDGE_ = "MAC_BRIDGE";
    public static final int    _DOCSIS_CABLE_DEVICE = 1863222733;
    public static final String _DOCSIS_CABLE_DEVICE_ = "DOCSIS_CABLE_DEVICE";
    public static final int    _MANAGEMENT_ADDRESS = 542785689;
    public static final String _MANAGEMENT_ADDRESS_ = "MANAGEMENT_ADDRESS";
    public static final int    _PORT_DESCRIPTION = 1817475244;
    public static final String _PORT_DESCRIPTION_ = "PORT_DESCRIPTION";
    public static final int    _WLAN_ACCESS_POINT = 1380901949;
    public static final String _WLAN_ACCESS_POINT_ = "WLAN_ACCESS_POINT";
    public static final int    _S_VLAN = 631405204;
    public static final String _S_VLAN_ = "S_VLAN";
}
