/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-rib-bgp-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-rib-bgp-types.yang */
public class openconfigRibBgpTypes extends ConfNamespace {
    public static final int hash = 331527041;
    public int hash() {
        return openconfigRibBgpTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rib/bgp-types";
    public String id() {
        return openconfigRibBgpTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rib/bgp-types";
    public String uri() {
        return openconfigRibBgpTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigRibBgpTypes.uri);
    }

    public static final String prefix = "oc-bgprib-types";
    public String prefix() {
        return openconfigRibBgpTypes.prefix;
    }

    public openconfigRibBgpTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _REJECTED_IMPORT_POLICY = 1400155361;
    public static final String _REJECTED_IMPORT_POLICY_ = "REJECTED_IMPORT_POLICY";
    public static final int    _SRTE_PREFERENCE = 1326398230;
    public static final String _SRTE_PREFERENCE_ = "SRTE_PREFERENCE";
    public static final int    _SRTE_SEGMENT_LIST_SEGMENT = 1179967674;
    public static final String _SRTE_SEGMENT_LIST_SEGMENT_ = "SRTE_SEGMENT_LIST_SEGMENT";
    public static final int    _TUNNEL_REMOTE_ENDPOINT = 751390676;
    public static final String _TUNNEL_REMOTE_ENDPOINT_ = "TUNNEL_REMOTE_ENDPOINT";
    public static final int    _SRTE_BINDING_SID = 269858494;
    public static final String _SRTE_BINDING_SID_ = "SRTE_BINDING_SID";
    public static final int    _MED_HIGHER = 229978588;
    public static final String _MED_HIGHER_ = "MED_HIGHER";
    public static final int    _HIGHER_ROUTER_ID = 952572681;
    public static final String _HIGHER_ROUTER_ID_ = "HIGHER_ROUTER_ID";
    public static final int    _INVALID_ORIGINATOR = 1735450243;
    public static final String _INVALID_ORIGINATOR_ = "INVALID_ORIGINATOR";
    public static final int    _TUNNEL_ENCAPSULATION_TYPE = 921334966;
    public static final String _TUNNEL_ENCAPSULATION_TYPE_ = "TUNNEL_ENCAPSULATION_TYPE";
    public static final int    _TUNNEL_COLOR = 1903881231;
    public static final String _TUNNEL_COLOR_ = "TUNNEL_COLOR";
    public static final int    _SRTE_SEGMENT_LIST = 316437334;
    public static final String _SRTE_SEGMENT_LIST_ = "SRTE_SEGMENT_LIST";
    public static final int    _BGP_NOT_SELECTED_BESTPATH = 1332166396;
    public static final String _BGP_NOT_SELECTED_BESTPATH_ = "BGP_NOT_SELECTED_BESTPATH";
    public static final int    _ORIGIN_TYPE_HIGHER = 1179538394;
    public static final String _ORIGIN_TYPE_HIGHER_ = "ORIGIN_TYPE_HIGHER";
    public static final int    _INVALID_AS_LOOP = 1123243151;
    public static final String _INVALID_AS_LOOP_ = "INVALID_AS_LOOP";
    public static final int    _SRTE_POLICY_TUNNEL = 1978555137;
    public static final String _SRTE_POLICY_TUNNEL_ = "SRTE_POLICY_TUNNEL";
    public static final int    _INVALID_ROUTE_REASON = 746597251;
    public static final String _INVALID_ROUTE_REASON_ = "INVALID_ROUTE_REASON";
    public static final int    _BGP_NOT_SELECTED_POLICY = 1471810501;
    public static final String _BGP_NOT_SELECTED_POLICY_ = "BGP_NOT_SELECTED_POLICY";
    public static final int    _INVALID_CLUSTER_LOOP = 57263232;
    public static final String _INVALID_CLUSTER_LOOP_ = "INVALID_CLUSTER_LOOP";
    public static final int    _LOCAL_PREF_LOWER = 182942030;
    public static final String _LOCAL_PREF_LOWER_ = "LOCAL_PREF_LOWER";
    public static final int    _SRTE_SEGMENT_LIST_WEIGHT = 1847497617;
    public static final String _SRTE_SEGMENT_LIST_WEIGHT_ = "SRTE_SEGMENT_LIST_WEIGHT";
    public static final int    _PREFER_EXTERNAL = 964932319;
    public static final String _PREFER_EXTERNAL_ = "PREFER_EXTERNAL";
    public static final int    _INVALID_CONFED = 1394621379;
    public static final String _INVALID_CONFED_ = "INVALID_CONFED";
    public static final int    _HIGHER_PEER_ADDRESS = 1572276748;
    public static final String _HIGHER_PEER_ADDRESS_ = "HIGHER_PEER_ADDRESS";
    public static final int    _NEXTHOP_COST_HIGHER = 77979501;
    public static final String _NEXTHOP_COST_HIGHER_ = "NEXTHOP_COST_HIGHER";
    public static final int    _TUNNEL_ENCAPSULATION_SUBTLV_TYPE = 665619248;
    public static final String _TUNNEL_ENCAPSULATION_SUBTLV_TYPE_ = "TUNNEL_ENCAPSULATION_SUBTLV_TYPE";
    public static final int    _AS_PATH_LONGER = 1223099127;
    public static final String _AS_PATH_LONGER_ = "AS_PATH_LONGER";
    public static final int    _SRTE_SEGMENT_LIST_SUBTLV = 727593094;
    public static final String _SRTE_SEGMENT_LIST_SUBTLV_ = "SRTE_SEGMENT_LIST_SUBTLV";
}
