/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-isis-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-isis-types.yang */
public class openconfigIsisTypes extends ConfNamespace {
    public static final int hash = 512626541;
    public int hash() {
        return openconfigIsisTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/isis-types";
    public String id() {
        return openconfigIsisTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/isis-types";
    public String uri() {
        return openconfigIsisTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigIsisTypes.uri);
    }

    public static final String prefix = "oc-isis-types";
    public String prefix() {
        return openconfigIsisTypes.prefix;
    }

    public openconfigIsisTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _MT_TYPE = 1167718602;
    public static final String _MT_TYPE_ = "MT_TYPE";
    public static final int    _UNICAST = 714208215;
    public static final String _UNICAST_ = "UNICAST";
    public static final int    _AFI_SAFI_TYPE = 1755201881;
    public static final String _AFI_SAFI_TYPE_ = "AFI_SAFI_TYPE";
    public static final int    _MD5 = 959247075;
    public static final String _MD5_ = "MD5";
    public static final int    _IPV4 = 2050433468;
    public static final String _IPV4_ = "IPV4";
    public static final int    _IPV6 = 1468531886;
    public static final String _IPV6_ = "IPV6";
    public static final int    _SAFI_TYPE = 846369923;
    public static final String _SAFI_TYPE_ = "SAFI_TYPE";
    public static final int    _IPV4_UNICAST = 751206307;
    public static final String _IPV4_UNICAST_ = "IPV4_UNICAST";
    public static final int    _IPV6_MULTICAST = 1835742059;
    public static final String _IPV6_MULTICAST_ = "IPV6_MULTICAST";
    public static final int    _AUTH_MODE = 309420944;
    public static final String _AUTH_MODE_ = "AUTH_MODE";
    public static final int    _OVERLOAD_RESET_TRIGGER_TYPE = 1598857774;
    public static final String _OVERLOAD_RESET_TRIGGER_TYPE_ = "OVERLOAD_RESET_TRIGGER_TYPE";
    public static final int    _IPV4_MULTICAST = 1160802435;
    public static final String _IPV4_MULTICAST_ = "IPV4_MULTICAST";
    public static final int    _MULTICAST = 146719160;
    public static final String _MULTICAST_ = "MULTICAST";
    public static final int    _AFI_TYPE = 178219080;
    public static final String _AFI_TYPE_ = "AFI_TYPE";
    public static final int    _WAIT_FOR_BGP = 291531983;
    public static final String _WAIT_FOR_BGP_ = "WAIT_FOR_BGP";
    public static final int    _TEXT = 1127876954;
    public static final String _TEXT_ = "TEXT";
    public static final int    _WAIT_FOR_SYSTEM = 831225571;
    public static final String _WAIT_FOR_SYSTEM_ = "WAIT_FOR_SYSTEM";
    public static final int    _IPV6_UNICAST = 1440955788;
    public static final String _IPV6_UNICAST_ = "IPV6_UNICAST";
}
