/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-if-ethernet.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-if-ethernet.yang */
public class openconfigIfEthernet extends ConfNamespace {
    public static final int hash = 1833271490;
    public int hash() {
        return openconfigIfEthernet.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/interfaces/ethernet";
    public String id() {
        return openconfigIfEthernet.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/interfaces/ethernet";
    public String uri() {
        return openconfigIfEthernet.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigIfEthernet.uri);
    }

    public static final String prefix = "oc-eth";
    public String prefix() {
        return openconfigIfEthernet.prefix;
    }

    public openconfigIfEthernet() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _out_mac_control_frames = 1033076598;
    public static final String _out_mac_control_frames_ = "out-mac-control-frames";
    public static final int    _SPEED_400GB = 928657629;
    public static final String _SPEED_400GB_ = "SPEED_400GB";
    public static final int    _duplex_mode = 1404309190;
    public static final String _duplex_mode_ = "duplex-mode";
    public static final int    _out_8021q_frames = 1916377746;
    public static final String _out_8021q_frames_ = "out-8021q-frames";
    public static final int    _in_maxsize_exceeded = 1592620661;
    public static final String _in_maxsize_exceeded_ = "in-maxsize-exceeded";
    public static final int    _fec_mode = 1758513387;
    public static final String _fec_mode_ = "fec-mode";
    public static final int    _port_speed = 1659992901;
    public static final String _port_speed_ = "port-speed";
    public static final int    _ethernet = 766975154;
    public static final String _ethernet_ = "ethernet";
    public static final int    _in_symbol_error = 330345552;
    public static final String _in_symbol_error_ = "in-symbol-error";
    public static final int    _SPEED_1GB = 1894348501;
    public static final String _SPEED_1GB_ = "SPEED_1GB";
    public static final int    _hw_mac_address = 761716137;
    public static final String _hw_mac_address_ = "hw-mac-address";
    public static final int    _SPEED_10GB = 620120484;
    public static final String _SPEED_10GB_ = "SPEED_10GB";
    public static final int    _FEC_RS544 = 2016616192;
    public static final String _FEC_RS544_ = "FEC_RS544";
    public static final int    _enable_flow_control = 204818831;
    public static final String _enable_flow_control_ = "enable-flow-control";
    public static final int    _SPEED_100GB = 1977203562;
    public static final String _SPEED_100GB_ = "SPEED_100GB";
    public static final int    _in_jabber_frames = 408306399;
    public static final String _in_jabber_frames_ = "in-jabber-frames";
    public static final int    _in_block_errors = 574971365;
    public static final String _in_block_errors_ = "in-block-errors";
    public static final int    _in_8021q_frames = 1930482994;
    public static final String _in_8021q_frames_ = "in-8021q-frames";
    public static final int    _out_mac_errors_tx = 1741887964;
    public static final String _out_mac_errors_tx_ = "out-mac-errors-tx";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _in_single_collision = 644608466;
    public static final String _in_single_collision_ = "in-single-collision";
    public static final int    _mac_address = 2110689796;
    public static final String _mac_address_ = "mac-address";
    public static final int    _FEC_DISABLED = 347512213;
    public static final String _FEC_DISABLED_ = "FEC_DISABLED";
    public static final int    _INTERFACE_FEC = 1814887658;
    public static final String _INTERFACE_FEC_ = "INTERFACE_FEC";
    public static final int    _in_carrier_errors = 1819454577;
    public static final String _in_carrier_errors_ = "in-carrier-errors";
    public static final int    _in_interrupted_tx = 1788111094;
    public static final String _in_interrupted_tx_ = "in-interrupted-tx";
    public static final int    _in_crc_errors = 621329595;
    public static final String _in_crc_errors_ = "in-crc-errors";
    public static final int    _in_oversize_frames = 1638462268;
    public static final String _in_oversize_frames_ = "in-oversize-frames";
    public static final int    _in_mac_control_frames = 1842676927;
    public static final String _in_mac_control_frames_ = "in-mac-control-frames";
    public static final int    _in_late_collision = 1149684835;
    public static final String _in_late_collision_ = "in-late-collision";
    public static final int    _SPEED_100MB = 1591127439;
    public static final String _SPEED_100MB_ = "SPEED_100MB";
    public static final int    _out_mac_pause_frames = 1294592065;
    public static final String _out_mac_pause_frames_ = "out-mac-pause-frames";
    public static final int    _FEC_RS544_2X_INTERLEAVE = 1302900439;
    public static final String _FEC_RS544_2X_INTERLEAVE_ = "FEC_RS544_2X_INTERLEAVE";
    public static final int    _SPEED_600GB = 2074753353;
    public static final String _SPEED_600GB_ = "SPEED_600GB";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _in_mac_errors_rx = 1863161887;
    public static final String _in_mac_errors_rx_ = "in-mac-errors-rx";
    public static final int    _FEC_FC = 1518437486;
    public static final String _FEC_FC_ = "FEC_FC";
    public static final int    _negotiated_duplex_mode = 1452772647;
    public static final String _negotiated_duplex_mode_ = "negotiated-duplex-mode";
    public static final int    _SPEED_50GB = 1290536247;
    public static final String _SPEED_50GB_ = "SPEED_50GB";
    public static final int    _standalone_link_training = 963533190;
    public static final String _standalone_link_training_ = "standalone-link-training";
    public static final int    _SPEED_40GB = 1431070194;
    public static final String _SPEED_40GB_ = "SPEED_40GB";
    public static final int    _SPEED_25GB = 1898852688;
    public static final String _SPEED_25GB_ = "SPEED_25GB";
    public static final int    _in_mac_pause_frames = 1003418322;
    public static final String _in_mac_pause_frames_ = "in-mac-pause-frames";
    public static final int    _counters = 1327053922;
    public static final String _counters_ = "counters";
    public static final int    _SPEED_10MB = 699501289;
    public static final String _SPEED_10MB_ = "SPEED_10MB";
    public static final int    _FEC_RS528 = 2035162655;
    public static final String _FEC_RS528_ = "FEC_RS528";
    public static final int    _SPEED_800GB = 363718347;
    public static final String _SPEED_800GB_ = "SPEED_800GB";
    public static final int    _in_undersize_frames = 1512667264;
    public static final String _in_undersize_frames_ = "in-undersize-frames";
    public static final int    _in_fragment_frames = 564635238;
    public static final String _in_fragment_frames_ = "in-fragment-frames";
    public static final int    _negotiated_port_speed = 1543346698;
    public static final String _negotiated_port_speed_ = "negotiated-port-speed";
    public static final int    _auto_negotiate = 2102272149;
    public static final String _auto_negotiate_ = "auto-negotiate";
    public static final int    _SPEED_200GB = 28992515;
    public static final String _SPEED_200GB_ = "SPEED_200GB";
    public static final int    _SPEED_UNKNOWN = 1980508219;
    public static final String _SPEED_UNKNOWN_ = "SPEED_UNKNOWN";
    public static final int    _SPEED_2500MB = 144799248;
    public static final String _SPEED_2500MB_ = "SPEED_2500MB";
    public static final int    _SPEED_5GB = 1781082174;
    public static final String _SPEED_5GB_ = "SPEED_5GB";
    public static final int    _ETHERNET_SPEED = 1987059756;
    public static final String _ETHERNET_SPEED_ = "ETHERNET_SPEED";
}
