/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-acl.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-acl.yang */
public class openconfigAcl extends ConfNamespace {
    public static final int hash = 1565404788;
    public int hash() {
        return openconfigAcl.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/acl";
    public String id() {
        return openconfigAcl.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/acl";
    public String uri() {
        return openconfigAcl.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigAcl.uri);
    }

    public static final String prefix = "oc-acl";
    public String prefix() {
        return openconfigAcl.prefix;
    }

    public openconfigAcl() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _hop_limit = 1986810812;
    public static final String _hop_limit_ = "hop-limit";
    public static final int    _ipv4 = 268057062;
    public static final String _ipv4_ = "ipv4";
    public static final int    _destination_mac = 1658530568;
    public static final String _destination_mac_ = "destination-mac";
    public static final int    _acl_sets = 38672230;
    public static final String _acl_sets_ = "acl-sets";
    public static final int    _acl_set = 1045582166;
    public static final String _acl_set_ = "acl-set";
    public static final int    _ACL_COUNTER_CAPABILITY = 1915047429;
    public static final String _ACL_COUNTER_CAPABILITY_ = "ACL_COUNTER_CAPABILITY";
    public static final int    _source_flow_label = 1351148708;
    public static final String _source_flow_label_ = "source-flow-label";
    public static final int    _mpls = 1138155655;
    public static final String _mpls_ = "mpls";
    public static final int    _set_name = 1054410690;
    public static final String _set_name_ = "set-name";
    public static final int    _ethertype = 1713629078;
    public static final String _ethertype_ = "ethertype";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _end_label_value = 2092223248;
    public static final String _end_label_value_ = "end-label-value";
    public static final int    _subinterface = 1294223328;
    public static final String _subinterface_ = "subinterface";
    public static final int    _tcp_flags = 2105017645;
    public static final String _tcp_flags_ = "tcp-flags";
    public static final int    _source_address = 554848846;
    public static final String _source_address_ = "source-address";
    public static final int    _destination_mac_mask = 2123449726;
    public static final String _destination_mac_mask_ = "destination-mac-mask";
    public static final int    _destination_flow_label = 418530020;
    public static final String _destination_flow_label_ = "destination-flow-label";
    public static final int    _interface_ref = 952985348;
    public static final String _interface_ref_ = "interface-ref";
    public static final int    _log_action = 1709946873;
    public static final String _log_action_ = "log-action";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _matched_octets = 666620061;
    public static final String _matched_octets_ = "matched-octets";
    public static final int    _FORWARDING_ACTION = 1701038382;
    public static final String _FORWARDING_ACTION_ = "FORWARDING_ACTION";
    public static final int    _start_label_value = 858882444;
    public static final String _start_label_value_ = "start-label-value";
    public static final int    _acl_entries = 1454774857;
    public static final String _acl_entries_ = "acl-entries";
    public static final int    _ttl_value = 486644255;
    public static final String _ttl_value_ = "ttl-value";
    public static final int    _counter_capability = 1393730278;
    public static final String _counter_capability_ = "counter-capability";
    public static final int    _ACL_MIXED = 1920446269;
    public static final String _ACL_MIXED_ = "ACL_MIXED";
    public static final int    _source_mac_mask = 232677856;
    public static final String _source_mac_mask_ = "source-mac-mask";
    public static final int    _LOG_NONE = 795240028;
    public static final String _LOG_NONE_ = "LOG_NONE";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _ACCEPT = 890190251;
    public static final String _ACCEPT_ = "ACCEPT";
    public static final int    _destination_port = 1685436757;
    public static final String _destination_port_ = "destination-port";
    public static final int    _ACL_IPV4 = 461233847;
    public static final String _ACL_IPV4_ = "ACL_IPV4";
    public static final int    _egress_acl_sets = 842928225;
    public static final String _egress_acl_sets_ = "egress-acl-sets";
    public static final int    _sequence_id = 1922783271;
    public static final String _sequence_id_ = "sequence-id";
    public static final int    _source_mac = 358822574;
    public static final String _source_mac_ = "source-mac";
    public static final int    _DROP = 1226140191;
    public static final String _DROP_ = "DROP";
    public static final int    _ACL_TYPE = 1937024167;
    public static final String _ACL_TYPE_ = "ACL_TYPE";
    public static final int    _matched_packets = 1743639543;
    public static final String _matched_packets_ = "matched-packets";
    public static final int    _destination_address = 1799113401;
    public static final String _destination_address_ = "destination-address";
    public static final int    _ipv6 = 1228132394;
    public static final String _ipv6_ = "ipv6";
    public static final int    _AGGREGATE_ONLY = 480232379;
    public static final String _AGGREGATE_ONLY_ = "AGGREGATE_ONLY";
    public static final int    _source_port = 256320896;
    public static final String _source_port_ = "source-port";
    public static final int    _input_interface = 1233459580;
    public static final String _input_interface_ = "input-interface";
    public static final int    _INTERFACE_AGGREGATE = 1854902128;
    public static final String _INTERFACE_AGGREGATE_ = "INTERFACE_AGGREGATE";
    public static final int    _ACL_MPLS = 858936162;
    public static final String _ACL_MPLS_ = "ACL_MPLS";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _ACL_IPV6 = 150631895;
    public static final String _ACL_IPV6_ = "ACL_IPV6";
    public static final int    _ingress_acl_set = 291543376;
    public static final String _ingress_acl_set_ = "ingress-acl-set";
    public static final int    _INTERFACE_ONLY = 1714523084;
    public static final String _INTERFACE_ONLY_ = "INTERFACE_ONLY";
    public static final int    _REJECT = 1411847091;
    public static final String _REJECT_ = "REJECT";
    public static final int    _ingress_acl_sets = 596604490;
    public static final String _ingress_acl_sets_ = "ingress-acl-sets";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _acl = 994927724;
    public static final String _acl_ = "acl";
    public static final int    _LOG_ACTION = 986752433;
    public static final String _LOG_ACTION_ = "LOG_ACTION";
    public static final int    _transport = 514190987;
    public static final String _transport_ = "transport";
    public static final int    _traffic_class = 1665496674;
    public static final String _traffic_class_ = "traffic-class";
    public static final int    _egress_acl_set = 1092913639;
    public static final String _egress_acl_set_ = "egress-acl-set";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _protocol = 943257313;
    public static final String _protocol_ = "protocol";
    public static final int    _actions = 2034878685;
    public static final String _actions_ = "actions";
    public static final int    _acl_entry = 248164204;
    public static final String _acl_entry_ = "acl-entry";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _l2 = 544849882;
    public static final String _l2_ = "l2";
    public static final int    _dscp_set = 1366758509;
    public static final String _dscp_set_ = "dscp-set";
    public static final int    _description = 202559156;
    public static final String _description_ = "description";
    public static final int    _dscp = 1118112132;
    public static final String _dscp_ = "dscp";
    public static final int    _LOG_SYSLOG = 1872531152;
    public static final String _LOG_SYSLOG_ = "LOG_SYSLOG";
    public static final int    _forwarding_action = 1195948894;
    public static final String _forwarding_action_ = "forwarding-action";
    public static final int    _ACL_L2 = 1301559970;
    public static final String _ACL_L2_ = "ACL_L2";
}
