/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-wifi-phy.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-wifi-phy.yang */
public class openconfigWifiPhy extends ConfNamespace {
    public static final int hash = 746713030;
    public int hash() {
        return openconfigWifiPhy.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/wifi-phy";
    public String id() {
        return openconfigWifiPhy.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/wifi-phy";
    public String uri() {
        return openconfigWifiPhy.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigWifiPhy.uri);
    }

    public static final String prefix = "oc-wifi-phy";
    public String prefix() {
        return openconfigWifiPhy.prefix;
    }

    public openconfigWifiPhy() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _dfs_hit_time = 15117951;
    public static final String _dfs_hit_time_ = "dfs-hit-time";
    public static final int    _neighbor = 81789621;
    public static final String _neighbor_ = "neighbor";
    public static final int    _scanning_dwell_time = 448108980;
    public static final String _scanning_dwell_time_ = "scanning-dwell-time";
    public static final int    _software_selectable = 304106495;
    public static final String _software_selectable_ = "software-selectable";
    public static final int    _operating_frequency = 258493278;
    public static final String _operating_frequency_ = "operating-frequency";
    public static final int    _primary_channel = 867652544;
    public static final String _primary_channel_ = "primary-channel";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _base_radio_mac = 1212335342;
    public static final String _base_radio_mac_ = "base-radio-mac";
    public static final int    _scanning_defer_traffic = 758768712;
    public static final String _scanning_defer_traffic_ = "scanning-defer-traffic";
    public static final int    _bss_color_id = 1827855932;
    public static final String _bss_color_id_ = "bss-color-id";
    public static final int    _rx_noise_channel_utilization = 2020995357;
    public static final String _rx_noise_channel_utilization_ = "rx-noise-channel-utilization";
    public static final int    _bss_coloring = 1132523191;
    public static final String _bss_coloring_ = "bss-coloring";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _ssid = 829059196;
    public static final String _ssid_ = "ssid";
    public static final int    _transmit_eirp = 1065572237;
    public static final String _transmit_eirp_ = "transmit-eirp";
    public static final int    _neighbors = 1478644450;
    public static final String _neighbors_ = "neighbors";
    public static final int    _noise_floor = 345986689;
    public static final String _noise_floor_ = "noise-floor";
    public static final int    _allowed_channels = 1273578867;
    public static final String _allowed_channels_ = "allowed-channels";
    public static final int    _dtp = 1386126427;
    public static final String _dtp_ = "dtp";
    public static final int    _transmit_power = 2083230338;
    public static final String _transmit_power_ = "transmit-power";
    public static final int    _bssid = 899218419;
    public static final String _bssid_ = "bssid";
    public static final int    _channel_width = 1760432088;
    public static final String _channel_width_ = "channel-width";
    public static final int    _antenna_gain = 1821817617;
    public static final String _antenna_gain_ = "antenna-gain";
    public static final int    _dtp_max = 387929790;
    public static final String _dtp_max_ = "dtp-max";
    public static final int    _radio = 704661128;
    public static final String _radio_ = "radio";
    public static final int    _channel_change_reason = 2041617277;
    public static final String _channel_change_reason_ = "channel-change-reason";
    public static final int    _radios = 1196902793;
    public static final String _radios_ = "radios";
    public static final int    _total_channel_utilization = 299134300;
    public static final String _total_channel_utilization_ = "total-channel-utilization";
    public static final int    _dca = 403688283;
    public static final String _dca_ = "dca";
    public static final int    _obss_rx = 1559474594;
    public static final String _obss_rx_ = "obss-rx";
    public static final int    _opmode = 1025161122;
    public static final String _opmode_ = "opmode";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _failed_fcs_frames = 768732330;
    public static final String _failed_fcs_frames_ = "failed-fcs-frames";
    public static final int    _scanning = 402273914;
    public static final String _scanning_ = "scanning";
    public static final int    _counters = 1327053922;
    public static final String _counters_ = "counters";
    public static final int    _allowed_regulatory_channels = 799972453;
    public static final String _allowed_regulatory_channels_ = "allowed-regulatory-channels";
    public static final int    _scanning_interval = 832562255;
    public static final String _scanning_interval_ = "scanning-interval";
    public static final int    _tx_dot11_channel_utilization = 2114749792;
    public static final String _tx_dot11_channel_utilization_ = "tx-dot11-channel-utilization";
    public static final int    _dtp_min = 507814863;
    public static final String _dtp_min_ = "dtp-min";
    public static final int    _last_seen = 628939602;
    public static final String _last_seen_ = "last-seen";
    public static final int    _scanning_defer_clients = 708969856;
    public static final String _scanning_defer_clients_ = "scanning-defer-clients";
    public static final int    _rssi = 1763358543;
    public static final String _rssi_ = "rssi";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _channel = 1372178362;
    public static final String _channel_ = "channel";
    public static final int    _supported_channels = 1686674215;
    public static final String _supported_channels_ = "supported-channels";
    public static final int    _rx_dot11_channel_utilization = 2049518015;
    public static final String _rx_dot11_channel_utilization_ = "rx-dot11-channel-utilization";
}
