/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-wavelength-router.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-wavelength-router.yang */
public class openconfigWavelengthRouter extends ConfNamespace {
    public static final int hash = 2143506778;
    public int hash() {
        return openconfigWavelengthRouter.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/wavelength-router";
    public String id() {
        return openconfigWavelengthRouter.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/wavelength-router";
    public String uri() {
        return openconfigWavelengthRouter.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigWavelengthRouter.uri);
    }

    public static final String prefix = "oc-wave-router";
    public String prefix() {
        return openconfigWavelengthRouter.prefix;
    }

    public openconfigWavelengthRouter() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _ATTENUATION_DYNAMIC_LOSS_DAMPED = 1269481777;
    public static final String _ATTENUATION_DYNAMIC_LOSS_DAMPED_ = "ATTENUATION_DYNAMIC_LOSS_DAMPED";
    public static final int    _ase_status = 1995125829;
    public static final String _ase_status_ = "ase-status";
    public static final int    _ATTENUATION_DYNAMIC_LOSS = 164745702;
    public static final String _ATTENUATION_DYNAMIC_LOSS_ = "ATTENUATION_DYNAMIC_LOSS";
    public static final int    _ASE_CONTROL_MODE = 1802449693;
    public static final String _ASE_CONTROL_MODE_ = "ASE_CONTROL_MODE";
    public static final int    _lower_frequency = 297729851;
    public static final String _lower_frequency_ = "lower-frequency";
    public static final int    _ase_injection_delta = 2042047496;
    public static final String _ase_injection_delta_ = "ase-injection-delta";
    public static final int    _dest = 1478643067;
    public static final String _dest_ = "dest";
    public static final int    _port = 10387472;
    public static final String _port_ = "port";
    public static final int    _source = 1141829056;
    public static final String _source_ = "source";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _spectrum_power_profile = 1514396589;
    public static final String _spectrum_power_profile_ = "spectrum-power-profile";
    public static final int    _target_power = 2112504380;
    public static final String _target_power_ = "target-power";
    public static final int    _ase_control_mode = 177547951;
    public static final String _ase_control_mode_ = "ase-control-mode";
    public static final int    _ASE_DISABLED = 2002019498;
    public static final String _ASE_DISABLED_ = "ASE_DISABLED";
    public static final int    _ATTENUATION_CONTROL_MODE = 1184613372;
    public static final String _ATTENUATION_CONTROL_MODE_ = "ATTENUATION_CONTROL_MODE";
    public static final int    _media_channels = 521934610;
    public static final String _media_channels_ = "media-channels";
    public static final int    _ATTENUATION_FIXED_LOSS = 1467347203;
    public static final String _ATTENUATION_FIXED_LOSS_ = "ATTENUATION_FIXED_LOSS";
    public static final int    _port_spectrum_power_profiles = 2042948932;
    public static final String _port_spectrum_power_profiles_ = "port-spectrum-power-profiles";
    public static final int    _admin_status = 2104862928;
    public static final String _admin_status_ = "admin-status";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _super_channel = 1097338244;
    public static final String _super_channel_ = "super-channel";
    public static final int    _ase_injection_mode = 104663193;
    public static final String _ase_injection_mode_ = "ase-injection-mode";
    public static final int    _AUTO_ASE_FAILURE_AND_RESTORE = 2116345897;
    public static final String _AUTO_ASE_FAILURE_AND_RESTORE_ = "AUTO_ASE_FAILURE_AND_RESTORE";
    public static final int    _attenuation_control_mode = 440330125;
    public static final String _attenuation_control_mode_ = "attenuation-control-mode";
    public static final int    _distribution = 2032111206;
    public static final String _distribution_ = "distribution";
    public static final int    _index = 827593980;
    public static final String _index_ = "index";
    public static final int    _AUTO_ASE_ON_FAILURE = 1297791541;
    public static final String _AUTO_ASE_ON_FAILURE_ = "AUTO_ASE_ON_FAILURE";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _oper_status = 1906453952;
    public static final String _oper_status_ = "oper-status";
    public static final int    _ase_injection_threshold = 1092971224;
    public static final String _ase_injection_threshold_ = "ase-injection-threshold";
    public static final int    _wavelength_router = 708507270;
    public static final String _wavelength_router_ = "wavelength-router";
    public static final int    _channel = 1372178362;
    public static final String _channel_ = "channel";
    public static final int    _port_name = 771740271;
    public static final String _port_name_ = "port-name";
    public static final int    _super_channel_parent = 947631100;
    public static final String _super_channel_parent_ = "super-channel-parent";
    public static final int    _ASE_ENABLED = 973087157;
    public static final String _ASE_ENABLED_ = "ASE_ENABLED";
    public static final int    _upper_frequency = 2069940695;
    public static final String _upper_frequency_ = "upper-frequency";
}
