/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-ospf-policy.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-ospf-policy.yang */
public class openconfigOspfPolicy extends ConfNamespace {
    public static final int hash = 832693542;
    public int hash() {
        return openconfigOspfPolicy.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ospf-policy";
    public String id() {
        return openconfigOspfPolicy.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ospf-policy";
    public String uri() {
        return openconfigOspfPolicy.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigOspfPolicy.uri);
    }

    public static final String prefix = "oc-ospf-pol";
    public String prefix() {
        return openconfigOspfPolicy.prefix;
    }

    public openconfigOspfPolicy() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _metric_type = 855418505;
    public static final String _metric_type_ = "metric-type";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _area_eq = 517549606;
    public static final String _area_eq_ = "area-eq";
    public static final int    _ospf_conditions = 1195133234;
    public static final String _ospf_conditions_ = "ospf-conditions";
    public static final int    _set_metric = 881511190;
    public static final String _set_metric_ = "set-metric";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _metric = 235154778;
    public static final String _metric_ = "metric";
    public static final int    _ospf_actions = 1757142546;
    public static final String _ospf_actions_ = "ospf-actions";
    public static final int    _set_area = 611036431;
    public static final String _set_area_ = "set-area";
}
