/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-igmp.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-igmp.yang */
public class openconfigIgmp extends ConfNamespace {
    public static final int hash = 1845427305;
    public int hash() {
        return openconfigIgmp.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/igmp";
    public String id() {
        return openconfigIgmp.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/igmp";
    public String uri() {
        return openconfigIgmp.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigIgmp.uri);
    }

    public static final String prefix = "oc-igmp";
    public String prefix() {
        return openconfigIgmp.prefix;
    }

    public openconfigIgmp() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
