/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-spanning-tree-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-spanning-tree-types.yang */
public class openconfigSpanningTreeTypes extends ConfNamespace {
    public static final int hash = 1177165426;
    public int hash() {
        return openconfigSpanningTreeTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/spanning-tree/types";
    public String id() {
        return openconfigSpanningTreeTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/spanning-tree/types";
    public String uri() {
        return openconfigSpanningTreeTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigSpanningTreeTypes.uri);
    }

    public static final String prefix = "oc-stp-types";
    public String prefix() {
        return openconfigSpanningTreeTypes.prefix;
    }

    public openconfigSpanningTreeTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _EDGE_DISABLE = 1731833628;
    public static final String _EDGE_DISABLE_ = "EDGE_DISABLE";
    public static final int    _DISABLED = 1464461520;
    public static final String _DISABLED_ = "DISABLED";
    public static final int    _BLOCKING = 128750559;
    public static final String _BLOCKING_ = "BLOCKING";
    public static final int    _DESIGNATED = 1718513210;
    public static final String _DESIGNATED_ = "DESIGNATED";
    public static final int    _EDGE_ENABLE = 597127690;
    public static final String _EDGE_ENABLE_ = "EDGE_ENABLE";
    public static final int    _ROOT = 1758779241;
    public static final String _ROOT_ = "ROOT";
    public static final int    _STP_PORT_ROLE = 1684464888;
    public static final String _STP_PORT_ROLE_ = "STP_PORT_ROLE";
    public static final int    _RAPID_PVST = 1598086486;
    public static final String _RAPID_PVST_ = "RAPID_PVST";
    public static final int    _STP_PORT_STATE = 1120212852;
    public static final String _STP_PORT_STATE_ = "STP_PORT_STATE";
    public static final int    _LISTENING = 1926419948;
    public static final String _LISTENING_ = "LISTENING";
    public static final int    _FORWARDING = 1009932180;
    public static final String _FORWARDING_ = "FORWARDING";
    public static final int    _STP_EDGE_PORT = 1802194878;
    public static final String _STP_EDGE_PORT_ = "STP_EDGE_PORT";
    public static final int    _LEARNING = 727262580;
    public static final String _LEARNING_ = "LEARNING";
    public static final int    _ALTERNATE = 1900624787;
    public static final String _ALTERNATE_ = "ALTERNATE";
    public static final int    _STP_PROTOCOL = 1957829784;
    public static final String _STP_PROTOCOL_ = "STP_PROTOCOL";
    public static final int    _BACKUP = 1824483253;
    public static final String _BACKUP_ = "BACKUP";
    public static final int    _MSTP = 1990524089;
    public static final String _MSTP_ = "MSTP";
    public static final int    _RSTP = 777592312;
    public static final String _RSTP_ = "RSTP";
    public static final int    _EDGE_AUTO = 925487535;
    public static final String _EDGE_AUTO_ = "EDGE_AUTO";
}
