/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-platform-cpu.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-platform-cpu.yang */
public class openconfigPlatformCpu extends ConfNamespace {
    public static final int hash = 747192571;
    public int hash() {
        return openconfigPlatformCpu.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/cpu";
    public String id() {
        return openconfigPlatformCpu.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/cpu";
    public String uri() {
        return openconfigPlatformCpu.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigPlatformCpu.uri);
    }

    public static final String prefix = "oc-cpu";
    public String prefix() {
        return openconfigPlatformCpu.prefix;
    }

    public openconfigPlatformCpu() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _max = 2088175689;
    public static final String _max_ = "max";
    public static final int    _interval = 559952988;
    public static final String _interval_ = "interval";
    public static final int    _min_time = 1805904672;
    public static final String _min_time_ = "min-time";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _utilization = 1882370771;
    public static final String _utilization_ = "utilization";
    public static final int    _min = 83205090;
    public static final String _min_ = "min";
    public static final int    _avg = 2050512522;
    public static final String _avg_ = "avg";
    public static final int    _max_time = 1093347309;
    public static final String _max_time_ = "max-time";
    public static final int    _instant = 2051543381;
    public static final String _instant_ = "instant";
}
