/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-policy-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-policy-types.yang */
public class openconfigPolicyTypes extends ConfNamespace {
    public static final int hash = 1049075594;
    public int hash() {
        return openconfigPolicyTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/policy-types";
    public String id() {
        return openconfigPolicyTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/policy-types";
    public String uri() {
        return openconfigPolicyTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigPolicyTypes.uri);
    }

    public static final String prefix = "oc-pol-types";
    public String prefix() {
        return openconfigPolicyTypes.prefix;
    }

    public openconfigPolicyTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _PCEP = 696331841;
    public static final String _PCEP_ = "PCEP";
    public static final int    _ATTRIBUTE_EQ = 382212571;
    public static final String _ATTRIBUTE_EQ_ = "ATTRIBUTE_EQ";
    public static final int    _ISIS = 574246373;
    public static final String _ISIS_ = "ISIS";
    public static final int    _LOCAL_AGGREGATE = 1483965019;
    public static final String _LOCAL_AGGREGATE_ = "LOCAL_AGGREGATE";
    public static final int    _ATTRIBUTE_LE = 121645146;
    public static final String _ATTRIBUTE_LE_ = "ATTRIBUTE_LE";
    public static final int    _BGP = 346655972;
    public static final String _BGP_ = "BGP";
    public static final int    _OSPF3 = 630371620;
    public static final String _OSPF3_ = "OSPF3";
    public static final int    _OSPF = 619009612;
    public static final String _OSPF_ = "OSPF";
    public static final int    _ATTRIBUTE_COMPARISON = 1727192591;
    public static final String _ATTRIBUTE_COMPARISON_ = "ATTRIBUTE_COMPARISON";
    public static final int    _PIM = 1710011258;
    public static final String _PIM_ = "PIM";
    public static final int    _IGMP = 1678389166;
    public static final String _IGMP_ = "IGMP";
    public static final int    _STATIC = 977019608;
    public static final String _STATIC_ = "STATIC";
    public static final int    _GRIBI = 901890394;
    public static final String _GRIBI_ = "GRIBI";
    public static final int    _DIRECTLY_CONNECTED = 615714624;
    public static final String _DIRECTLY_CONNECTED_ = "DIRECTLY_CONNECTED";
    public static final int    _ATTRIBUTE_GE = 1537951632;
    public static final String _ATTRIBUTE_GE_ = "ATTRIBUTE_GE";
    public static final int    _INSTALL_PROTOCOL_TYPE = 1846295931;
    public static final String _INSTALL_PROTOCOL_TYPE_ = "INSTALL_PROTOCOL_TYPE";
}
