/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-transport-line-protection.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-transport-line-protection.yang */
public class openconfigTransportLineProtection extends ConfNamespace {
    public static final int hash = 806587432;
    public int hash() {
        return openconfigTransportLineProtection.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/optical-transport-line-protection";
    public String id() {
        return openconfigTransportLineProtection.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/optical-transport-line-protection";
    public String uri() {
        return openconfigTransportLineProtection.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigTransportLineProtection.uri);
    }

    public static final String prefix = "oc-line-protect";
    public String prefix() {
        return openconfigTransportLineProtection.prefix;
    }

    public openconfigTransportLineProtection() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _optical_power = 310316755;
    public static final String _optical_power_ = "optical-power";
    public static final int    _PRIMARY = 355888324;
    public static final String _PRIMARY_ = "PRIMARY";
    public static final int    _max = 2088175689;
    public static final String _max_ = "max";
    public static final int    _common_in = 2026646659;
    public static final String _common_in_ = "common-in";
    public static final int    _primary_switch_hysteresis = 134078249;
    public static final String _primary_switch_hysteresis_ = "primary-switch-hysteresis";
    public static final int    _APS_PATHS = 438387567;
    public static final String _APS_PATHS_ = "APS_PATHS";
    public static final int    _wait_to_restore_time = 1695744172;
    public static final String _wait_to_restore_time_ = "wait-to-restore-time";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _line_primary_out = 1213694906;
    public static final String _line_primary_out_ = "line-primary-out";
    public static final int    _common_output = 13899150;
    public static final String _common_output_ = "common-output";
    public static final int    _interval = 559952988;
    public static final String _interval_ = "interval";
    public static final int    _min_time = 1805904672;
    public static final String _min_time_ = "min-time";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _line_secondary_in = 1667199995;
    public static final String _line_secondary_in_ = "line-secondary-in";
    public static final int    _relative_switch_threshold_offset = 503774169;
    public static final String _relative_switch_threshold_offset_ = "relative-switch-threshold-offset";
    public static final int    _line_secondary_out = 1423041241;
    public static final String _line_secondary_out_ = "line-secondary-out";
    public static final int    _attenuation = 1694846668;
    public static final String _attenuation_ = "attenuation";
    public static final int    _aps = 1528266830;
    public static final String _aps_ = "aps";
    public static final int    _SECONDARY = 531792517;
    public static final String _SECONDARY_ = "SECONDARY";
    public static final int    _revertive = 1569418781;
    public static final String _revertive_ = "revertive";
    public static final int    _aps_modules = 1912361995;
    public static final String _aps_modules_ = "aps-modules";
    public static final int    _aps_module = 407918111;
    public static final String _aps_module_ = "aps-module";
    public static final int    _target_attenuation = 1586582681;
    public static final String _target_attenuation_ = "target-attenuation";
    public static final int    _min = 83205090;
    public static final String _min_ = "min";
    public static final int    _primary_switch_threshold = 56114232;
    public static final String _primary_switch_threshold_ = "primary-switch-threshold";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _ports = 1554580266;
    public static final String _ports_ = "ports";
    public static final int    _active_path = 1394605946;
    public static final String _active_path_ = "active-path";
    public static final int    _force_to_port = 1068528734;
    public static final String _force_to_port_ = "force-to-port";
    public static final int    _avg = 2050512522;
    public static final String _avg_ = "avg";
    public static final int    _max_time = 1093347309;
    public static final String _max_time_ = "max-time";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _line_primary_in = 1011704893;
    public static final String _line_primary_in_ = "line-primary-in";
    public static final int    _hold_off_time = 1302203176;
    public static final String _hold_off_time_ = "hold-off-time";
    public static final int    _relative_switch_threshold = 662299997;
    public static final String _relative_switch_threshold_ = "relative-switch-threshold";
    public static final int    _instant = 2051543381;
    public static final String _instant_ = "instant";
    public static final int    _secondary_switch_threshold = 571465491;
    public static final String _secondary_switch_threshold_ = "secondary-switch-threshold";
}
