/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-evpn.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-evpn.yang */
public class openconfigEvpn extends ConfNamespace {
    public static final int hash = 1249209261;
    public int hash() {
        return openconfigEvpn.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/evpn";
    public String id() {
        return openconfigEvpn.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/evpn";
    public String uri() {
        return openconfigEvpn.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigEvpn.uri);
    }

    public static final String prefix = "oc-evpn";
    public String prefix() {
        return openconfigEvpn.prefix;
    }

    public openconfigEvpn() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
