/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-system-terminal.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-system-terminal.yang */
public class openconfigSystemTerminal extends ConfNamespace {
    public static final int hash = 214522185;
    public int hash() {
        return openconfigSystemTerminal.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/system/terminal";
    public String id() {
        return openconfigSystemTerminal.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/system/terminal";
    public String uri() {
        return openconfigSystemTerminal.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigSystemTerminal.uri);
    }

    public static final String prefix = "oc-sys-term";
    public String prefix() {
        return openconfigSystemTerminal.prefix;
    }

    public openconfigSystemTerminal() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
