/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-gribi.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-gribi.yang */
public class openconfigGribi extends ConfNamespace {
    public static final int hash = 534592455;
    public int hash() {
        return openconfigGribi.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/gribi";
    public String id() {
        return openconfigGribi.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/gribi";
    public String uri() {
        return openconfigGribi.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigGribi.uri);
    }

    public static final String prefix = "oc-gribi";
    public String prefix() {
        return openconfigGribi.prefix;
    }

    public openconfigGribi() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _GRIBI = 901890394;
    public static final String _GRIBI_ = "GRIBI";
}
