/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-lldp.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-lldp.yang */
public class openconfigLldp extends ConfNamespace {
    public static final int hash = 591569475;
    public int hash() {
        return openconfigLldp.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/lldp";
    public String id() {
        return openconfigLldp.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/lldp";
    public String uri() {
        return openconfigLldp.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigLldp.uri);
    }

    public static final String prefix = "oc-lldp";
    public String prefix() {
        return openconfigLldp.prefix;
    }

    public openconfigLldp() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _neighbor = 81789621;
    public static final String _neighbor_ = "neighbor";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _last_update = 498080631;
    public static final String _last_update_ = "last-update";
    public static final int    _frame_out = 899192982;
    public static final String _frame_out_ = "frame-out";
    public static final int    _port_id_type = 1294387739;
    public static final String _port_id_type_ = "port-id-type";
    public static final int    _management_address_type = 1070023607;
    public static final String _management_address_type_ = "management-address-type";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _neighbors = 1478644450;
    public static final String _neighbors_ = "neighbors";
    public static final int    _hello_timer = 1869518339;
    public static final String _hello_timer_ = "hello-timer";
    public static final int    _tlv_accepted = 1856541892;
    public static final String _tlv_accepted_ = "tlv-accepted";
    public static final int    _oui_subtype = 960442680;
    public static final String _oui_subtype_ = "oui-subtype";
    public static final int    _system_description = 1651773485;
    public static final String _system_description_ = "system-description";
    public static final int    _capabilities = 1381570067;
    public static final String _capabilities_ = "capabilities";
    public static final int    _age = 304093784;
    public static final String _age_ = "age";
    public static final int    _tlv_discard = 75606479;
    public static final String _tlv_discard_ = "tlv-discard";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _entries_aged_out = 818798602;
    public static final String _entries_aged_out_ = "entries-aged-out";
    public static final int    _capability = 1251322185;
    public static final String _capability_ = "capability";
    public static final int    _port_id = 411479338;
    public static final String _port_id_ = "port-id";
    public static final int    _ttl = 774234709;
    public static final String _ttl_ = "ttl";
    public static final int    _oui = 169238003;
    public static final String _oui_ = "oui";
    public static final int    _chassis_id_type = 2064781464;
    public static final String _chassis_id_type_ = "chassis-id-type";
    public static final int    _port_description = 1466459667;
    public static final String _port_description_ = "port-description";
    public static final int    _system_name = 1975516496;
    public static final String _system_name_ = "system-name";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _tlv_unknown = 546776942;
    public static final String _tlv_unknown_ = "tlv-unknown";
    public static final int    _chassis_id = 1476535866;
    public static final String _chassis_id_ = "chassis-id";
    public static final int    _counters = 1327053922;
    public static final String _counters_ = "counters";
    public static final int    _suppress_tlv_advertisement = 1552375923;
    public static final String _suppress_tlv_advertisement_ = "suppress-tlv-advertisement";
    public static final int    _lldp = 830250803;
    public static final String _lldp_ = "lldp";
    public static final int    _frame_discard = 1933515315;
    public static final String _frame_discard_ = "frame-discard";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _management_address = 613978086;
    public static final String _management_address_ = "management-address";
    public static final int    _custom_tlvs = 1472881104;
    public static final String _custom_tlvs_ = "custom-tlvs";
    public static final int    _frame_in = 497567735;
    public static final String _frame_in_ = "frame-in";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _frame_error_in = 511909285;
    public static final String _frame_error_in_ = "frame-error-in";
    public static final int    _tlv = 1250745731;
    public static final String _tlv_ = "tlv";
    public static final int    _frame_error_out = 1736170451;
    public static final String _frame_error_out_ = "frame-error-out";
    public static final int    _last_clear = 1168907511;
    public static final String _last_clear_ = "last-clear";
}
