/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-procmon.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-procmon.yang */
public class openconfigProcmon extends ConfNamespace {
    public static final int hash = 2023737692;
    public int hash() {
        return openconfigProcmon.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/system/procmon";
    public String id() {
        return openconfigProcmon.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/system/procmon";
    public String uri() {
        return openconfigProcmon.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigProcmon.uri);
    }

    public static final String prefix = "oc-proc";
    public String prefix() {
        return openconfigProcmon.prefix;
    }

    public openconfigProcmon() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
