/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-isis-policy.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-isis-policy.yang */
public class openconfigIsisPolicy extends ConfNamespace {
    public static final int hash = 1487951822;
    public int hash() {
        return openconfigIsisPolicy.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-isis-policy";
    public String id() {
        return openconfigIsisPolicy.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-isis-policy";
    public String uri() {
        return openconfigIsisPolicy.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigIsisPolicy.uri);
    }

    public static final String prefix = "oc-isis-pol";
    public String prefix() {
        return openconfigIsisPolicy.prefix;
    }

    public openconfigIsisPolicy() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _set_metric_type = 532385650;
    public static final String _set_metric_type_ = "set-metric-type";
    public static final int    _isis_actions = 826650940;
    public static final String _isis_actions_ = "isis-actions";
    public static final int    _set_level = 393386362;
    public static final String _set_level_ = "set-level";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _level_eq = 1966819302;
    public static final String _level_eq_ = "level-eq";
    public static final int    _set_metric = 881511190;
    public static final String _set_metric_ = "set-metric";
    public static final int    _isis_conditions = 1403268967;
    public static final String _isis_conditions_ = "isis-conditions";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
}
