/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-vlan-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-vlan-types.yang */
public class openconfigVlanTypes extends ConfNamespace {
    public static final int hash = 1753609013;
    public int hash() {
        return openconfigVlanTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/vlan-types";
    public String id() {
        return openconfigVlanTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/vlan-types";
    public String uri() {
        return openconfigVlanTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigVlanTypes.uri);
    }

    public static final String prefix = "oc-vlan-types";
    public String prefix() {
        return openconfigVlanTypes.prefix;
    }

    public openconfigVlanTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _TPID_TYPES = 382907686;
    public static final String _TPID_TYPES_ = "TPID_TYPES";
    public static final int    _TPID_ANY = 2033114277;
    public static final String _TPID_ANY_ = "TPID_ANY";
    public static final int    _TPID_0X8100 = 1360772003;
    public static final String _TPID_0X8100_ = "TPID_0X8100";
    public static final int    _TPID_0X88A8 = 1005676458;
    public static final String _TPID_0X88A8_ = "TPID_0X88A8";
    public static final int    _TPID_0X9200 = 1396454253;
    public static final String _TPID_0X9200_ = "TPID_0X9200";
    public static final int    _TPID_0X9100 = 1028366700;
    public static final String _TPID_0X9100_ = "TPID_0X9100";
}
