/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-if-tunnel.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-if-tunnel.yang */
public class openconfigIfTunnel extends ConfNamespace {
    public static final int hash = 176733720;
    public int hash() {
        return openconfigIfTunnel.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/interfaces/tunnel";
    public String id() {
        return openconfigIfTunnel.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/interfaces/tunnel";
    public String uri() {
        return openconfigIfTunnel.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigIfTunnel.uri);
    }

    public static final String prefix = "oc-tun";
    public String prefix() {
        return openconfigIfTunnel.prefix;
    }

    public openconfigIfTunnel() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _neighbor = 81789621;
    public static final String _neighbor_ = "neighbor";
    public static final int    _src = 1474138878;
    public static final String _src_ = "src";
    public static final int    _out_pkts = 335453834;
    public static final String _out_pkts_ = "out-pkts";
    public static final int    _proxy_arp = 676928388;
    public static final String _proxy_arp_ = "proxy-arp";
    public static final int    _ipv4 = 268057062;
    public static final String _ipv4_ = "ipv4";
    public static final int    _out_octets = 2123582464;
    public static final String _out_octets_ = "out-octets";
    public static final int    _suppress = 1746378947;
    public static final String _suppress_ = "suppress";
    public static final int    _in_error_pkts = 1525691105;
    public static final String _in_error_pkts_ = "in-error-pkts";
    public static final int    _out_forwarded_pkts = 1671788686;
    public static final String _out_forwarded_pkts_ = "out-forwarded-pkts";
    public static final int    _mode = 575893728;
    public static final String _mode_ = "mode";
    public static final int    _out_error_pkts = 1259985273;
    public static final String _out_error_pkts_ = "out-error-pkts";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _subinterface = 1294223328;
    public static final String _subinterface_ = "subinterface";
    public static final int    _in_pkts = 1264605324;
    public static final String _in_pkts_ = "in-pkts";
    public static final int    _interval = 559952988;
    public static final String _interval_ = "interval";
    public static final int    _interface_ref = 952985348;
    public static final String _interface_ref_ = "interface-ref";
    public static final int    _addresses = 1825332052;
    public static final String _addresses_ = "addresses";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _neighbors = 1478644450;
    public static final String _neighbors_ = "neighbors";
    public static final int    _neighbor_state = 393193907;
    public static final String _neighbor_state_ = "neighbor-state";
    public static final int    _dup_addr_detect_transmits = 53367116;
    public static final String _dup_addr_detect_transmits_ = "dup-addr-detect-transmits";
    public static final int    _dst = 1772754210;
    public static final String _dst_ = "dst";
    public static final int    _tunnel = 1120006729;
    public static final String _tunnel_ = "tunnel";
    public static final int    _ttl = 774234709;
    public static final String _ttl_ = "ttl";
    public static final int    _ipv6 = 1228132394;
    public static final String _ipv6_ = "ipv6";
    public static final int    _origin = 2002579816;
    public static final String _origin_ = "origin";
    public static final int    _mtu = 1751455506;
    public static final String _mtu_ = "mtu";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _counters = 1327053922;
    public static final String _counters_ = "counters";
    public static final int    _out_discarded_pkts = 2063997953;
    public static final String _out_discarded_pkts_ = "out-discarded-pkts";
    public static final int    _in_octets = 1354763654;
    public static final String _in_octets_ = "in-octets";
    public static final int    _lifetime = 92991035;
    public static final String _lifetime_ = "lifetime";
    public static final int    _dhcp_client = 1259775382;
    public static final String _dhcp_client_ = "dhcp-client";
    public static final int    _is_router = 1891156201;
    public static final String _is_router_ = "is-router";
    public static final int    _in_discarded_pkts = 1037387075;
    public static final String _in_discarded_pkts_ = "in-discarded-pkts";
    public static final int    _out_forwarded_octets = 1487514732;
    public static final String _out_forwarded_octets_ = "out-forwarded-octets";
    public static final int    _router_advertisement = 996372025;
    public static final String _router_advertisement_ = "router-advertisement";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _ip = 1643785435;
    public static final String _ip_ = "ip";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _unnumbered = 1288780644;
    public static final String _unnumbered_ = "unnumbered";
    public static final int    _in_forwarded_octets = 425114535;
    public static final String _in_forwarded_octets_ = "in-forwarded-octets";
    public static final int    _in_forwarded_pkts = 1440015958;
    public static final String _in_forwarded_pkts_ = "in-forwarded-pkts";
    public static final int    _link_layer_address = 2084100809;
    public static final String _link_layer_address_ = "link-layer-address";
    public static final int    _gre_key = 835370429;
    public static final String _gre_key_ = "gre-key";
    public static final int    _prefix_length = 524393771;
    public static final String _prefix_length_ = "prefix-length";
}
