/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-telemetry.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-telemetry.yang */
public class openconfigTelemetry extends ConfNamespace {
    public static final int hash = 1527053704;
    public int hash() {
        return openconfigTelemetry.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/telemetry";
    public String id() {
        return openconfigTelemetry.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/telemetry";
    public String uri() {
        return openconfigTelemetry.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigTelemetry.uri);
    }

    public static final String prefix = "oc-telemetry";
    public String prefix() {
        return openconfigTelemetry.prefix;
    }

    public openconfigTelemetry() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _sample_interval = 1730479987;
    public static final String _sample_interval_ = "sample-interval";
    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _destination_group = 1598383525;
    public static final String _destination_group_ = "destination-group";
    public static final int    _suppress_redundant = 1367205526;
    public static final String _suppress_redundant_ = "suppress-redundant";
    public static final int    _sensor_profile = 1970107157;
    public static final String _sensor_profile_ = "sensor-profile";
    public static final int    _sensor_paths = 1692117363;
    public static final String _sensor_paths_ = "sensor-paths";
    public static final int    _encoding = 180862443;
    public static final String _encoding_ = "encoding";
    public static final int    _sensor_group = 521692491;
    public static final String _sensor_group_ = "sensor-group";
    public static final int    _destination = 1426812369;
    public static final String _destination_ = "destination";
    public static final int    _group_id = 2095068827;
    public static final String _group_id_ = "group-id";
    public static final int    _persistent_subscription = 1373683679;
    public static final String _persistent_subscription_ = "persistent-subscription";
    public static final int    _sensor_groups = 1378032050;
    public static final String _sensor_groups_ = "sensor-groups";
    public static final int    _dynamic_subscriptions = 358197336;
    public static final String _dynamic_subscriptions_ = "dynamic-subscriptions";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _dynamic_subscription = 1460307865;
    public static final String _dynamic_subscription_ = "dynamic-subscription";
    public static final int    _destination_port = 1685436757;
    public static final String _destination_port_ = "destination-port";
    public static final int    _local_source_address = 1348732713;
    public static final String _local_source_address_ = "local-source-address";
    public static final int    _destination_groups = 676110724;
    public static final String _destination_groups_ = "destination-groups";
    public static final int    _sensor_path = 424127023;
    public static final String _sensor_path_ = "sensor-path";
    public static final int    _destination_address = 1799113401;
    public static final String _destination_address_ = "destination-address";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _telemetry_system = 658036610;
    public static final String _telemetry_system_ = "telemetry-system";
    public static final int    _sensor_profiles = 2055311817;
    public static final String _sensor_profiles_ = "sensor-profiles";
    public static final int    _exclude_filter = 1205417205;
    public static final String _exclude_filter_ = "exclude-filter";
    public static final int    _sensor_group_id = 1378386708;
    public static final String _sensor_group_id_ = "sensor-group-id";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _destinations = 1001041063;
    public static final String _destinations_ = "destinations";
    public static final int    _heartbeat_interval = 1281304246;
    public static final String _heartbeat_interval_ = "heartbeat-interval";
    public static final int    _subscriptions = 886823438;
    public static final String _subscriptions_ = "subscriptions";
    public static final int    _originated_qos_marking = 324407343;
    public static final String _originated_qos_marking_ = "originated-qos-marking";
    public static final int    _protocol = 943257313;
    public static final String _protocol_ = "protocol";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _persistent_subscriptions = 1211207143;
    public static final String _persistent_subscriptions_ = "persistent-subscriptions";
}
