/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-oc-all-nc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-oc-all-nc.yang */
public class tailfNedIdOcAllNc extends ConfNamespace {
    public static final int hash = 258740039;
    public int hash() {
        return tailfNedIdOcAllNc.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/oc-all-nc";
    public String id() {
        return tailfNedIdOcAllNc.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/oc-all-nc";
    public String uri() {
        return tailfNedIdOcAllNc.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdOcAllNc.uri);
    }

    public static final String prefix = "oc-all-nc";
    public String prefix() {
        return tailfNedIdOcAllNc.prefix;
    }

    public tailfNedIdOcAllNc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    ned_id = 170765500;
    public static final String ned_id_ = "oc-all-nc:oc-all-nc";
    public static final int    _oc_all_nc = 170765500;
    public static final String _oc_all_nc_ = "oc-all-nc";
}
