/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-id-oc-all-nc-1.0.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-id-oc-all-nc-1.0.yang */
public class tailfNedIdOcAllNc1_0 extends ConfNamespace {
    public static final int hash = 1022186405;
    public int hash() {
        return tailfNedIdOcAllNc1_0.hash;
    }

    public static final String id = "http://tail-f.com/ns/ned-id/oc-all-nc-1.0";
    public String id() {
        return tailfNedIdOcAllNc1_0.id;
    }

    public static final String uri = "http://tail-f.com/ns/ned-id/oc-all-nc-1.0";
    public String uri() {
        return tailfNedIdOcAllNc1_0.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(tailfNedIdOcAllNc1_0.uri);
    }

    public static final String prefix = "oc-all-nc-1.0";
    public String prefix() {
        return tailfNedIdOcAllNc1_0.prefix;
    }

    public tailfNedIdOcAllNc1_0() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _oc_all_nc_10x2e0 = 1859503451;
    public static final String _oc_all_nc_10x2e0_ = "oc-all-nc-1.0";
}
