#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-netconf-monitoring.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-netconf-monitoring.yang


class ns(object):
    hash = 1807594832

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"

    prefix = "ncm"

    ncm_info = 2062105651
    ncm_info_ = "info"
    ncm_yin = 301270440
    ncm_yin_ = "yin"
    ncm_yang = 125956256
    ncm_yang_ = "yang"
    ncm_locked_by_session = 916935714
    ncm_locked_by_session_ = "locked-by-session"
    ncm_lock_id = 1218349718
    ncm_lock_id_ = "lock-id"
    ncm_netconf_soap_over_https = 1667369492
    ncm_netconf_soap_over_https_ = "netconf-soap-over-https"
    ncm_netconf_beep = 457515174
    ncm_netconf_beep_ = "netconf-beep"
    ncm_location = 1827424758
    ncm_location_ = "location"
    ncm_datastores = 527897995
    ncm_datastores_ = "datastores"
    ncm_result = 401396173
    ncm_result_ = "result"
    ncm_statistics = 1049034618
    ncm_statistics_ = "statistics"
    ncm_schema = 1919828639
    ncm_schema_ = "schema"
    ncm_device = 617911018
    ncm_device_ = "device"
    ncm_schemas = 1917353471
    ncm_schemas_ = "schemas"
    ncm_dropped_sessions = 1544687737
    ncm_dropped_sessions_ = "dropped-sessions"
    ncm_locks = 2046791790
    ncm_locks_ = "locks"
    ncm_version = 1714291735
    ncm_version_ = "version"
    ncm_source_host = 1399987302
    ncm_source_host_ = "source-host"
    ncm_get_schema = 229086858
    ncm_get_schema_ = "get-schema"
    ncm_datastore = 449538578
    ncm_datastore_ = "datastore"
    ncm_locked_node = 228482246
    ncm_locked_node_ = "locked-node"
    ncm_rnc = 1942942111
    ncm_rnc_ = "rnc"
    ncm_capabilities = 1381570067
    ncm_capabilities_ = "capabilities"
    ncm_netconf_soap_over_beep = 971045646
    ncm_netconf_soap_over_beep_ = "netconf-soap-over-beep"
    ncm_session_id = 372565948
    ncm_session_id_ = "session-id"
    ncm_rpc_get_schema = 2117616030
    ncm_rpc_get_schema_ = "rpc-get-schema"
    ncm_in_bad_rpcs = 1884060047
    ncm_in_bad_rpcs_ = "in-bad-rpcs"
    ncm_identifier = 1002883111
    ncm_identifier_ = "identifier"
    ncm_in_sessions = 1124264593
    ncm_in_sessions_ = "in-sessions"
    ncm_capability = 1251322185
    ncm_capability_ = "capability"
    ncm_netconf_ssh = 1990240108
    ncm_netconf_ssh_ = "netconf-ssh"
    ncm_username = 870658415
    ncm_username_ = "username"
    ncm_candidate = 1
    ncm_candidate_ = "candidate"
    ncm_sessions = 972148830
    ncm_sessions_ = "sessions"
    ncm_netconf_start_time = 753673644
    ncm_netconf_start_time_ = "netconf-start-time"
    ncm_rng = 362068674
    ncm_rng_ = "rng"
    ncm_schema_format = 1050397973
    ncm_schema_format_ = "schema-format"
    ncm_login_time = 56217328
    ncm_login_time_ = "login-time"
    ncm_out_notifications = 336790191
    ncm_out_notifications_ = "out-notifications"
    ncm_netconf_state = 1132832184
    ncm_netconf_state_ = "netconf-state"
    ncm_namespace = 1847615892
    ncm_namespace_ = "namespace"
    ncm_NETCONF = 0
    ncm_NETCONF_ = "NETCONF"
    ncm_locked_time = 231512154
    ncm_locked_time_ = "locked-time"
    ncm_in_rpcs = 501359903
    ncm_in_rpcs_ = "in-rpcs"
    ncm_name = 1998270519
    ncm_name_ = "name"
    ncm_startup = 2
    ncm_startup_ = "startup"
    ncm_transport = 514190987
    ncm_transport_ = "transport"
    ncm_out_rpc_errors = 1948390774
    ncm_out_rpc_errors_ = "out-rpc-errors"
    ncm_session = 1896174846
    ncm_session_ = "session"
    ncm_select = 1473597411
    ncm_select_ = "select"
    ncm_format = 1150348190
    ncm_format_ = "format"
    ncm_data = 535242711
    ncm_data_ = "data"
    ncm_in_bad_hellos = 1621991935
    ncm_in_bad_hellos_ = "in-bad-hellos"
    ncm_partial_lock = 957776378
    ncm_partial_lock_ = "partial-lock"
    ncm_xsd = 1923342839
    ncm_xsd_ = "xsd"
    ncm_running = 0
    ncm_running_ = "running"
    ncm_lock_type = 410285766
    ncm_lock_type_ = "lock-type"
    ncm_netconf_tls = 898337675
    ncm_netconf_tls_ = "netconf-tls"
    ncm_global_lock = 848123075
    ncm_global_lock_ = "global-lock"
