#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/ietf-interfaces.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module ietf-interfaces.yang


class ns(object):
    hash = 886813517

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#urn:ietf:params:xml:ns:yang:ietf-interfaces"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#urn:ietf:params:xml:ns:yang:ietf-interfaces"

    prefix = "if"

    if_in_multicast_pkts = 1126031588
    if_in_multicast_pkts_ = "in-multicast-pkts"
    if_interface_type = 1566485963
    if_interface_type_ = "interface-type"
    if_out_octets = 2123582464
    if_out_octets_ = "out-octets"
    if_discontinuity_time = 318342031
    if_discontinuity_time_ = "discontinuity-time"
    if_out_broadcast_pkts = 1427076806
    if_out_broadcast_pkts_ = "out-broadcast-pkts"
    if_interfaces_state = 2120054373
    if_interfaces_state_ = "interfaces-state"
    if_up = 1
    if_up_ = "up"
    if_interfaces = 321503962
    if_interfaces_ = "interfaces"
    if_testing = 3
    if_testing_ = "testing"
    if_statistics = 1049034618
    if_statistics_ = "statistics"
    if_lower_layer_down = 7
    if_lower_layer_down_ = "lower-layer-down"
    if_in_unicast_pkts = 1100444555
    if_in_unicast_pkts_ = "in-unicast-pkts"
    if_type = 2040883914
    if_type_ = "type"
    if_admin_status = 2104862928
    if_admin_status_ = "admin-status"
    if_disabled = 2
    if_disabled_ = "disabled"
    if_in_discards = 1607867097
    if_in_discards_ = "in-discards"
    if_in_errors = 419802148
    if_in_errors_ = "in-errors"
    if_in_unknown_protos = 1961345832
    if_in_unknown_protos_ = "in-unknown-protos"
    if_link_up_down_trap_enable = 1552886723
    if_link_up_down_trap_enable_ = "link-up-down-trap-enable"
    if_down = 2
    if_down_ = "down"
    if_not_present = 6
    if_not_present_ = "not-present"
    if_speed = 1423237997
    if_speed_ = "speed"
    if_in_octets = 1354763654
    if_in_octets_ = "in-octets"
    if_out_errors = 1825475719
    if_out_errors_ = "out-errors"
    if_in_broadcast_pkts = 1140019954
    if_in_broadcast_pkts_ = "in-broadcast-pkts"
    if_name = 1998270519
    if_name_ = "name"
    if_phys_address = 1102597279
    if_phys_address_ = "phys-address"
    if_higher_layer_if = 750793054
    if_higher_layer_if_ = "higher-layer-if"
    if_out_multicast_pkts = 723352241
    if_out_multicast_pkts_ = "out-multicast-pkts"
    if_last_change = 2008341778
    if_last_change_ = "last-change"
    if_oper_status = 1906453952
    if_oper_status_ = "oper-status"
    if_interface = 221572658
    if_interface_ = "interface"
    if_unknown = 4
    if_unknown_ = "unknown"
    if_if_index = 216876767
    if_if_index_ = "if-index"
    if_dormant = 5
    if_dormant_ = "dormant"
    if_out_unicast_pkts = 170730703
    if_out_unicast_pkts_ = "out-unicast-pkts"
    if_lower_layer_if = 247228720
    if_lower_layer_if_ = "lower-layer-if"
    if_description = 202559156
    if_description_ = "description"
    if_out_discards = 2051284211
    if_out_discards_ = "out-discards"
