#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-oc-all-nc.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-oc-all-nc.yang


class ns(object):
    hash = 258740039

    id = "http://tail-f.com/ns/ned-id/oc-all-nc"

    uri = "http://tail-f.com/ns/ned-id/oc-all-nc"

    prefix = "oc-all-nc"

    ned_id = 170765500
    ned_id_ = "oc-all-nc:oc-all-nc"
    oc_all_nc_oc_all_nc = 170765500
    oc_all_nc_oc_all_nc_ = "oc-all-nc"
