#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/tailf-ned-id-oc-all-nc-1.0.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module tailf-ned-id-oc-all-nc-1.0.yang


class ns(object):
    hash = 1022186405

    id = "http://tail-f.com/ns/ned-id/oc-all-nc-1.0"

    uri = "http://tail-f.com/ns/ned-id/oc-all-nc-1.0"

    prefix = "oc-all-nc-1.0"

    oc_all_nc_10x2e0_oc_all_nc_10x2e0 = 1859503451
    oc_all_nc_10x2e0_oc_all_nc_10x2e0_ = "oc-all-nc-1.0"
