#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-packet-match.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-packet-match.yang


class ns(object):
    hash = 148412667

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/header-fields"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/header-fields"

    prefix = "oc-pkt-match"

