#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-packet-match-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-packet-match-types.yang


class ns(object):
    hash = 896127815

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/packet-match-types"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/packet-match-types"

    prefix = "oc-pkt-match-types"

    oc_pkt_match_types_ANY = 0
    oc_pkt_match_types_ANY_ = "ANY"
    oc_pkt_match_types_ETHERTYPE_VLAN = 436707426
    oc_pkt_match_types_ETHERTYPE_VLAN_ = "ETHERTYPE_VLAN"
    oc_pkt_match_types_IP_IGMP = 764880135
    oc_pkt_match_types_IP_IGMP_ = "IP_IGMP"
    oc_pkt_match_types_IP_AUTH = 1043975182
    oc_pkt_match_types_IP_AUTH_ = "IP_AUTH"
    oc_pkt_match_types_TCP_FIN = 1164880925
    oc_pkt_match_types_TCP_FIN_ = "TCP_FIN"
    oc_pkt_match_types_ETHERTYPE_IPV4 = 1751658908
    oc_pkt_match_types_ETHERTYPE_IPV4_ = "ETHERTYPE_IPV4"
    oc_pkt_match_types_TCP_CWR = 1500811464
    oc_pkt_match_types_TCP_CWR_ = "TCP_CWR"
    oc_pkt_match_types_TCP_URG = 630869116
    oc_pkt_match_types_TCP_URG_ = "TCP_URG"
    oc_pkt_match_types_ETHERTYPE = 422577011
    oc_pkt_match_types_ETHERTYPE_ = "ETHERTYPE"
    oc_pkt_match_types_TCP_FLAGS = 500117467
    oc_pkt_match_types_TCP_FLAGS_ = "TCP_FLAGS"
    oc_pkt_match_types_TCP_ACK = 1076625639
    oc_pkt_match_types_TCP_ACK_ = "TCP_ACK"
    oc_pkt_match_types_ETHERTYPE_IPV6 = 794158069
    oc_pkt_match_types_ETHERTYPE_IPV6_ = "ETHERTYPE_IPV6"
    oc_pkt_match_types_TCP_RST = 1035069476
    oc_pkt_match_types_TCP_RST_ = "TCP_RST"
    oc_pkt_match_types_ETHERTYPE_LLDP = 1034039949
    oc_pkt_match_types_ETHERTYPE_LLDP_ = "ETHERTYPE_LLDP"
    oc_pkt_match_types_IP_TCP = 1623698270
    oc_pkt_match_types_IP_TCP_ = "IP_TCP"
    oc_pkt_match_types_IP_UDP = 333182529
    oc_pkt_match_types_IP_UDP_ = "IP_UDP"
    oc_pkt_match_types_IP_ICMP = 395542725
    oc_pkt_match_types_IP_ICMP_ = "IP_ICMP"
    oc_pkt_match_types_IP_L2TP = 119338649
    oc_pkt_match_types_IP_L2TP_ = "IP_L2TP"
    oc_pkt_match_types_IP_PIM = 500161575
    oc_pkt_match_types_IP_PIM_ = "IP_PIM"
    oc_pkt_match_types_TCP_ECE = 793282102
    oc_pkt_match_types_TCP_ECE_ = "TCP_ECE"
    oc_pkt_match_types_ETHERTYPE_MPLS = 256626193
    oc_pkt_match_types_ETHERTYPE_MPLS_ = "ETHERTYPE_MPLS"
    oc_pkt_match_types_IP_PROTOCOL = 1798790167
    oc_pkt_match_types_IP_PROTOCOL_ = "IP_PROTOCOL"
    oc_pkt_match_types_ETHERTYPE_ROCE = 494633403
    oc_pkt_match_types_ETHERTYPE_ROCE_ = "ETHERTYPE_ROCE"
    oc_pkt_match_types_TCP_SYN = 1221732869
    oc_pkt_match_types_TCP_SYN_ = "TCP_SYN"
    oc_pkt_match_types_ETHERTYPE_ARP = 436090865
    oc_pkt_match_types_ETHERTYPE_ARP_ = "ETHERTYPE_ARP"
    oc_pkt_match_types_TCP_PSH = 1027471523
    oc_pkt_match_types_TCP_PSH_ = "TCP_PSH"
    oc_pkt_match_types_IP_IN_IP = 1135523508
    oc_pkt_match_types_IP_IN_IP_ = "IP_IN_IP"
    oc_pkt_match_types_IP_GRE = 1131330395
    oc_pkt_match_types_IP_GRE_ = "IP_GRE"
    oc_pkt_match_types_IP_RSVP = 2018541646
    oc_pkt_match_types_IP_RSVP_ = "IP_RSVP"
