#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-fw-high-availability.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-fw-high-availability.yang


class ns(object):
    hash = 432810005

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/oc-fw-ha"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/oc-fw-ha"

    prefix = "oc-fw-ha"

    oc_fw_ha_ha_msg_encryption = 210675946
    oc_fw_ha_ha_msg_encryption_ = "ha-msg-encryption"
    oc_fw_ha_ANY = 0
    oc_fw_ha_ANY_ = "ANY"
    oc_fw_ha_data_link_ipv6 = 1152851909
    oc_fw_ha_data_link_ipv6_ = "data-link-ipv6"
    oc_fw_ha_PASSIVE = 1
    oc_fw_ha_PASSIVE_ = "PASSIVE"
    oc_fw_ha_control_link_gateway = 1941462973
    oc_fw_ha_control_link_gateway_ = "control-link-gateway"
    oc_fw_ha_control_link_peer_ipv4 = 1734030348
    oc_fw_ha_control_link_peer_ipv4_ = "control-link-peer-ipv4"
    oc_fw_ha_data_link_port = 293322836
    oc_fw_ha_data_link_port_ = "data-link-port"
    oc_fw_ha_preempt_hold_timer = 1123662157
    oc_fw_ha_preempt_hold_timer_ = "preempt-hold-timer"
    oc_fw_ha_control_link_ipv4 = 1824365955
    oc_fw_ha_control_link_ipv4_ = "control-link-ipv4"
    oc_fw_ha_DOWN = 1
    oc_fw_ha_DOWN_ = "DOWN"
    oc_fw_ha_control_link_ipv6 = 1576015019
    oc_fw_ha_control_link_ipv6_ = "control-link-ipv6"
    oc_fw_ha_ha_key = 1400053972
    oc_fw_ha_ha_key_ = "ha-key"
    oc_fw_ha_ha_session_sync = 1494260114
    oc_fw_ha_ha_session_sync_ = "ha-session-sync"
    oc_fw_ha_SUSPENDED = 3
    oc_fw_ha_SUSPENDED_ = "SUSPENDED"
    oc_fw_ha_state = 630973766
    oc_fw_ha_state_ = "state"
    oc_fw_ha_monitored_interfaces = 2052464213
    oc_fw_ha_monitored_interfaces_ = "monitored-interfaces"
    oc_fw_ha_global_health_status = 2046404638
    oc_fw_ha_global_health_status_ = "global-health-status"
    oc_fw_ha_SOFTWARE_MISMATCH = 1664064059
    oc_fw_ha_SOFTWARE_MISMATCH_ = "SOFTWARE_MISMATCH"
    oc_fw_ha_backup = 23119955
    oc_fw_ha_backup_ = "backup"
    oc_fw_ha_data_link_gateway = 608423875
    oc_fw_ha_data_link_gateway_ = "data-link-gateway"
    oc_fw_ha_data_link_ipv4 = 2138865777
    oc_fw_ha_data_link_ipv4_ = "data-link-ipv4"
    oc_fw_ha_control_link_peer_ipv6 = 1907488007
    oc_fw_ha_control_link_peer_ipv6_ = "control-link-peer-ipv6"
    oc_fw_ha_data_link_peer_ipv6 = 371778183
    oc_fw_ha_data_link_peer_ipv6_ = "data-link-peer-ipv6"
    oc_fw_ha_ha_state_last_change = 988896625
    oc_fw_ha_ha_state_last_change_ = "ha-state-last-change"
    oc_fw_ha_data_link = 623143938
    oc_fw_ha_data_link_ = "data-link"
    oc_fw_ha_ha_group = 1804583280
    oc_fw_ha_ha_group_ = "ha-group"
    oc_fw_ha_ALL = 1
    oc_fw_ha_ALL_ = "ALL"
    oc_fw_ha_interface_group = 654875926
    oc_fw_ha_interface_group_ = "interface-group"
    oc_fw_ha_interface_groups = 93186499
    oc_fw_ha_interface_groups_ = "interface-groups"
    oc_fw_ha_group_status = 1662558404
    oc_fw_ha_group_status_ = "group-status"
    oc_fw_ha_priority = 1346277862
    oc_fw_ha_priority_ = "priority"
    oc_fw_ha_ACTIVE = 0
    oc_fw_ha_ACTIVE_ = "ACTIVE"
    oc_fw_ha_ha_groups = 1585293573
    oc_fw_ha_ha_groups_ = "ha-groups"
    oc_fw_ha_ha_enabled = 1538690517
    oc_fw_ha_ha_enabled_ = "ha-enabled"
    oc_fw_ha_data_link_ipv6_gateway = 832259381
    oc_fw_ha_data_link_ipv6_gateway_ = "data-link-ipv6-gateway"
    oc_fw_ha_data_link_interface = 1498690656
    oc_fw_ha_data_link_interface_ = "data-link-interface"
    oc_fw_ha_ha_key_hashed = 811423821
    oc_fw_ha_ha_key_hashed_ = "ha-key-hashed"
    oc_fw_ha_config = 2105663071
    oc_fw_ha_config_ = "config"
    oc_fw_ha_ACTIVE_PASSIVE = 0
    oc_fw_ha_ACTIVE_PASSIVE_ = "ACTIVE_PASSIVE"
    oc_fw_ha_HA_PEER_MISMATCHED_ITEM = 170628515
    oc_fw_ha_HA_PEER_MISMATCHED_ITEM_ = "HA_PEER_MISMATCHED_ITEM"
    oc_fw_ha_ha_device_id = 1604004142
    oc_fw_ha_ha_device_id_ = "ha-device-id"
    oc_fw_ha_preempt = 419787493
    oc_fw_ha_preempt_ = "preempt"
    oc_fw_ha_UP = 0
    oc_fw_ha_UP_ = "UP"
    oc_fw_ha_data_link_peer_ipv4 = 1086858993
    oc_fw_ha_data_link_peer_ipv4_ = "data-link-peer-ipv4"
    oc_fw_ha_control_link_port = 822245376
    oc_fw_ha_control_link_port_ = "control-link-port"
    oc_fw_ha_RUNNING_CONFIG_MISMATCH = 1703198481
    oc_fw_ha_RUNNING_CONFIG_MISMATCH_ = "RUNNING_CONFIG_MISMATCH"
    oc_fw_ha_DEGRADED = 2
    oc_fw_ha_DEGRADED_ = "DEGRADED"
    oc_fw_ha_ha_mode = 1735430019
    oc_fw_ha_ha_mode_ = "ha-mode"
    oc_fw_ha_global_health_policy = 1509495708
    oc_fw_ha_global_health_policy_ = "global-health-policy"
    oc_fw_ha_group_policy = 287761729
    oc_fw_ha_group_policy_ = "group-policy"
    oc_fw_ha_control_link = 348926922
    oc_fw_ha_control_link_ = "control-link"
    oc_fw_ha_IPS_SIGNATURES_MISMATCH = 783506101
    oc_fw_ha_IPS_SIGNATURES_MISMATCH_ = "IPS_SIGNATURES_MISMATCH"
    oc_fw_ha_id = 1279252765
    oc_fw_ha_id_ = "id"
    oc_fw_ha_hello_interval = 208691019
    oc_fw_ha_hello_interval_ = "hello-interval"
    oc_fw_ha_ha_mismatched_parameters = 164110521
    oc_fw_ha_ha_mismatched_parameters_ = "ha-mismatched-parameters"
    oc_fw_ha_control_link_ipv6_gateway = 257565953
    oc_fw_ha_control_link_ipv6_gateway_ = "control-link-ipv6-gateway"
    oc_fw_ha_AVC_SIGNATURES_MISMATCH = 160192046
    oc_fw_ha_AVC_SIGNATURES_MISMATCH_ = "AVC_SIGNATURES_MISMATCH"
    oc_fw_ha_ha_state = 1633459074
    oc_fw_ha_ha_state_ = "ha-state"
    oc_fw_ha_ha_config_sync = 1510608238
    oc_fw_ha_ha_config_sync_ = "ha-config-sync"
    oc_fw_ha_control_link_interface = 1510793754
    oc_fw_ha_control_link_interface_ = "control-link-interface"
