#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-policy-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-policy-types.yang


class ns(object):
    hash = 1049075594

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/policy-types"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/policy-types"

    prefix = "oc-pol-types"

    oc_pol_types_ANY = 0
    oc_pol_types_ANY_ = "ANY"
    oc_pol_types_PCEP = 696331841
    oc_pol_types_PCEP_ = "PCEP"
    oc_pol_types_ATTRIBUTE_EQ = 382212571
    oc_pol_types_ATTRIBUTE_EQ_ = "ATTRIBUTE_EQ"
    oc_pol_types_ISIS = 574246373
    oc_pol_types_ISIS_ = "ISIS"
    oc_pol_types_LOCAL_AGGREGATE = 1483965019
    oc_pol_types_LOCAL_AGGREGATE_ = "LOCAL_AGGREGATE"
    oc_pol_types_ATTRIBUTE_LE = 121645146
    oc_pol_types_ATTRIBUTE_LE_ = "ATTRIBUTE_LE"
    oc_pol_types_BGP = 346655972
    oc_pol_types_BGP_ = "BGP"
    oc_pol_types_OSPF3 = 630371620
    oc_pol_types_OSPF3_ = "OSPF3"
    oc_pol_types_OSPF = 619009612
    oc_pol_types_OSPF_ = "OSPF"
    oc_pol_types_ATTRIBUTE_COMPARISON = 1727192591
    oc_pol_types_ATTRIBUTE_COMPARISON_ = "ATTRIBUTE_COMPARISON"
    oc_pol_types_PIM = 1710011258
    oc_pol_types_PIM_ = "PIM"
    oc_pol_types_IGMP = 1678389166
    oc_pol_types_IGMP_ = "IGMP"
    oc_pol_types_STATIC = 977019608
    oc_pol_types_STATIC_ = "STATIC"
    oc_pol_types_GRIBI = 901890394
    oc_pol_types_GRIBI_ = "GRIBI"
    oc_pol_types_ALL = 1
    oc_pol_types_ALL_ = "ALL"
    oc_pol_types_DIRECTLY_CONNECTED = 615714624
    oc_pol_types_DIRECTLY_CONNECTED_ = "DIRECTLY_CONNECTED"
    oc_pol_types_ATTRIBUTE_GE = 1537951632
    oc_pol_types_ATTRIBUTE_GE_ = "ATTRIBUTE_GE"
    oc_pol_types_INSTALL_PROTOCOL_TYPE = 1846295931
    oc_pol_types_INSTALL_PROTOCOL_TYPE_ = "INSTALL_PROTOCOL_TYPE"
