#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-yang-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-yang-types.yang


class ns(object):
    hash = 131710919

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/types/yang"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/types/yang"

    prefix = "oc-yang"

