#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-platform-transceiver.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-platform-transceiver.yang


class ns(object):
    hash = 922198007

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/transceiver"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/transceiver"

    prefix = "oc-transceiver"

    oc_transceiver_connector_type = 1855142630
    oc_transceiver_connector_type_ = "connector-type"
    oc_transceiver_ethernet_pmd = 1853114659
    oc_transceiver_ethernet_pmd_ = "ethernet-pmd"
    oc_transceiver_output_frequency = 884786563
    oc_transceiver_output_frequency_ = "output-frequency"
    oc_transceiver_associated_optical_channel = 1189736983
    oc_transceiver_associated_optical_channel_ = "associated-optical-channel"
    oc_transceiver_max = 2088175689
    oc_transceiver_max_ = "max"
    oc_transceiver_present = 2043219423
    oc_transceiver_present_ = "present"
    oc_transceiver_form_factor_preconf = 673112044
    oc_transceiver_form_factor_preconf_ = "form-factor-preconf"
    oc_transceiver_fec_mode = 1758513387
    oc_transceiver_fec_mode_ = "fec-mode"
    oc_transceiver_enabled = 197426095
    oc_transceiver_enabled_ = "enabled"
    oc_transceiver_PRESENT = 0
    oc_transceiver_PRESENT_ = "PRESENT"
    oc_transceiver_physical_channels = 634498055
    oc_transceiver_physical_channels_ = "physical-channels"
    oc_transceiver_module_functional_type = 1281873586
    oc_transceiver_module_functional_type_ = "module-functional-type"
    oc_transceiver_interval = 559952988
    oc_transceiver_interval_ = "interval"
    oc_transceiver_min_time = 1805904672
    oc_transceiver_min_time_ = "min-time"
    oc_transceiver_state = 630973766
    oc_transceiver_state_ = "state"
    oc_transceiver_fec_status = 2100933247
    oc_transceiver_fec_status_ = "fec-status"
    oc_transceiver_vendor_part = 708944586
    oc_transceiver_vendor_part_ = "vendor-part"
    oc_transceiver_sonet_sdh_compliance_code = 425947975
    oc_transceiver_sonet_sdh_compliance_code_ = "sonet-sdh-compliance-code"
    oc_transceiver_fec_uncorrectable_blocks = 1907475582
    oc_transceiver_fec_uncorrectable_blocks_ = "fec-uncorrectable-blocks"
    oc_transceiver_laser_temperature = 2109521396
    oc_transceiver_laser_temperature_ = "laser-temperature"
    oc_transceiver_pre_fec_ber = 930828535
    oc_transceiver_pre_fec_ber_ = "pre-fec-ber"
    oc_transceiver_target_output_power = 1907745428
    oc_transceiver_target_output_power_ = "target-output-power"
    oc_transceiver_tx_laser = 1159284595
    oc_transceiver_tx_laser_ = "tx-laser"
    oc_transceiver_fec_corrected_bytes = 1141619065
    oc_transceiver_fec_corrected_bytes_ = "fec-corrected-bytes"
    oc_transceiver_transceiver = 170005784
    oc_transceiver_transceiver_ = "transceiver"
    oc_transceiver_vendor = 1639541835
    oc_transceiver_vendor_ = "vendor"
    oc_transceiver_min = 83205090
    oc_transceiver_min_ = "min"
    oc_transceiver_post_fec_ber = 1498085913
    oc_transceiver_post_fec_ber_ = "post-fec-ber"
    oc_transceiver_fault_condition = 1122095305
    oc_transceiver_fault_condition_ = "fault-condition"
    oc_transceiver_laser_bias_current = 1521732466
    oc_transceiver_laser_bias_current_ = "laser-bias-current"
    oc_transceiver_supply_voltage = 1363589656
    oc_transceiver_supply_voltage_ = "supply-voltage"
    oc_transceiver_config = 2105663071
    oc_transceiver_config_ = "config"
    oc_transceiver_NOT_PRESENT = 1
    oc_transceiver_NOT_PRESENT_ = "NOT_PRESENT"
    oc_transceiver_ethernet_pmd_preconf = 781770860
    oc_transceiver_ethernet_pmd_preconf_ = "ethernet-pmd-preconf"
    oc_transceiver_otn_compliance_code = 2068647721
    oc_transceiver_otn_compliance_code_ = "otn-compliance-code"
    oc_transceiver_index = 827593980
    oc_transceiver_index_ = "index"
    oc_transceiver_output_power = 571387945
    oc_transceiver_output_power_ = "output-power"
    oc_transceiver_laser_age = 878017175
    oc_transceiver_laser_age_ = "laser-age"
    oc_transceiver_avg = 2050512522
    oc_transceiver_avg_ = "avg"
    oc_transceiver_max_time = 1093347309
    oc_transceiver_max_time_ = "max-time"
    oc_transceiver_serial_no = 480270650
    oc_transceiver_serial_no_ = "serial-no"
    oc_transceiver_vendor_rev = 533031606
    oc_transceiver_vendor_rev_ = "vendor-rev"
    oc_transceiver_fec_corrected_bits = 1755603872
    oc_transceiver_fec_corrected_bits_ = "fec-corrected-bits"
    oc_transceiver_date_code = 1902762841
    oc_transceiver_date_code_ = "date-code"
    oc_transceiver_fec_uncorrectable_words = 1222725929
    oc_transceiver_fec_uncorrectable_words_ = "fec-uncorrectable-words"
    oc_transceiver_instant = 2051543381
    oc_transceiver_instant_ = "instant"
    oc_transceiver_channel = 1372178362
    oc_transceiver_channel_ = "channel"
    oc_transceiver_description = 202559156
    oc_transceiver_description_ = "description"
    oc_transceiver_tec_current = 1485892935
    oc_transceiver_tec_current_ = "tec-current"
    oc_transceiver_physical_channel = 1994537587
    oc_transceiver_physical_channel_ = "physical-channel"
    oc_transceiver_input_power = 1019491846
    oc_transceiver_input_power_ = "input-power"
    oc_transceiver_form_factor = 605079377
    oc_transceiver_form_factor_ = "form-factor"
    oc_transceiver_target_frequency_deviation = 1068222139
    oc_transceiver_target_frequency_deviation_ = "target-frequency-deviation"
