#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-platform-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-platform-types.yang


class ns(object):
    hash = 460214184

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform-types"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform-types"

    prefix = "oc-platform-types"

    oc_platform_types_USER_INITIATED = 0
    oc_platform_types_USER_INITIATED_ = "USER_INITIATED"
    oc_platform_types_POWER_DISABLED = 1
    oc_platform_types_POWER_DISABLED_ = "POWER_DISABLED"
    oc_platform_types_CPU = 2003850434
    oc_platform_types_CPU_ = "CPU"
    oc_platform_types_OPERATING_SYSTEM_UPDATE = 821910383
    oc_platform_types_OPERATING_SYSTEM_UPDATE_ = "OPERATING_SYSTEM_UPDATE"
    oc_platform_types_BACKPLANE = 516734991
    oc_platform_types_BACKPLANE_ = "BACKPLANE"
    oc_platform_types_PRIMARY = 0
    oc_platform_types_PRIMARY_ = "PRIMARY"
    oc_platform_types_DISABLED = 1464461520
    oc_platform_types_DISABLED_ = "DISABLED"
    oc_platform_types_FEC_AUTO = 1666129688
    oc_platform_types_FEC_AUTO_ = "FEC_AUTO"
    oc_platform_types_OPERATING_SYSTEM = 588501281
    oc_platform_types_OPERATING_SYSTEM_ = "OPERATING_SYSTEM"
    oc_platform_types_SYSTEM_INITIATED = 1
    oc_platform_types_SYSTEM_INITIATED_ = "SYSTEM_INITIATED"
    oc_platform_types_PORT = 1557878253
    oc_platform_types_PORT_ = "PORT"
    oc_platform_types_FEC_STATUS_UNLOCKED = 2126264679
    oc_platform_types_FEC_STATUS_UNLOCKED_ = "FEC_STATUS_UNLOCKED"
    oc_platform_types_FEC_MODE_TYPE = 1557884459
    oc_platform_types_FEC_MODE_TYPE_ = "FEC_MODE_TYPE"
    oc_platform_types_CHASSIS = 1020895844
    oc_platform_types_CHASSIS_ = "CHASSIS"
    oc_platform_types_REBOOT_POWER_FAILURE = 876385422
    oc_platform_types_REBOOT_POWER_FAILURE_ = "REBOOT_POWER_FAILURE"
    oc_platform_types_FABRIC = 551652471
    oc_platform_types_FABRIC_ = "FABRIC"
    oc_platform_types_FEC_DISABLED = 347512213
    oc_platform_types_FEC_DISABLED_ = "FEC_DISABLED"
    oc_platform_types_SECONDARY = 1
    oc_platform_types_SECONDARY_ = "SECONDARY"
    oc_platform_types_STORAGE = 1440738496
    oc_platform_types_STORAGE_ = "STORAGE"
    oc_platform_types_COMPONENT_REBOOT_REASON = 1347453183
    oc_platform_types_COMPONENT_REBOOT_REASON_ = "COMPONENT_REBOOT_REASON"
    oc_platform_types_OPENCONFIG_HARDWARE_COMPONENT = 751182229
    oc_platform_types_OPENCONFIG_HARDWARE_COMPONENT_ = "OPENCONFIG_HARDWARE_COMPONENT"
    oc_platform_types_ACTIVE = 1776322622
    oc_platform_types_ACTIVE_ = "ACTIVE"
    oc_platform_types_OPENCONFIG_SOFTWARE_COMPONENT = 1157725893
    oc_platform_types_OPENCONFIG_SOFTWARE_COMPONENT_ = "OPENCONFIG_SOFTWARE_COMPONENT"
    oc_platform_types_TRANSCEIVER = 985296955
    oc_platform_types_TRANSCEIVER_ = "TRANSCEIVER"
    oc_platform_types_POWER_ENABLED = 0
    oc_platform_types_POWER_ENABLED_ = "POWER_ENABLED"
    oc_platform_types_CONTROLLER_CARD = 1128995636
    oc_platform_types_CONTROLLER_CARD_ = "CONTROLLER_CARD"
    oc_platform_types_COMPONENT_OPER_STATUS = 1122930247
    oc_platform_types_COMPONENT_OPER_STATUS_ = "COMPONENT_OPER_STATUS"
    oc_platform_types_INACTIVE = 1100742089
    oc_platform_types_INACTIVE_ = "INACTIVE"
    oc_platform_types_FRU = 164729260
    oc_platform_types_FRU_ = "FRU"
    oc_platform_types_SENSOR = 325116750
    oc_platform_types_SENSOR_ = "SENSOR"
    oc_platform_types_FAN = 1369376826
    oc_platform_types_FAN_ = "FAN"
    oc_platform_types_REBOOT_USER_INITIATED = 689936085
    oc_platform_types_REBOOT_USER_INITIATED_ = "REBOOT_USER_INITIATED"
    oc_platform_types_INTEGRATED_CIRCUIT = 423035511
    oc_platform_types_INTEGRATED_CIRCUIT_ = "INTEGRATED_CIRCUIT"
    oc_platform_types_SOFTWARE_MODULE = 1688981753
    oc_platform_types_SOFTWARE_MODULE_ = "SOFTWARE_MODULE"
    oc_platform_types_FEC_ENABLED = 1695457742
    oc_platform_types_FEC_ENABLED_ = "FEC_ENABLED"
    oc_platform_types_FEC_STATUS_TYPE = 41908062
    oc_platform_types_FEC_STATUS_TYPE_ = "FEC_STATUS_TYPE"
    oc_platform_types_REBOOT_CRITICAL_ERROR = 2043957614
    oc_platform_types_REBOOT_CRITICAL_ERROR_ = "REBOOT_CRITICAL_ERROR"
    oc_platform_types_FEC_STATUS_LOCKED = 998294599
    oc_platform_types_FEC_STATUS_LOCKED_ = "FEC_STATUS_LOCKED"
    oc_platform_types_BIOS = 1571168887
    oc_platform_types_BIOS_ = "BIOS"
    oc_platform_types_POWER_SUPPLY = 1365464960
    oc_platform_types_POWER_SUPPLY_ = "POWER_SUPPLY"
    oc_platform_types_BOOT_LOADER = 347980823
    oc_platform_types_BOOT_LOADER_ = "BOOT_LOADER"
    oc_platform_types_LINECARD = 1977515942
    oc_platform_types_LINECARD_ = "LINECARD"
