#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-types.yang


class ns(object):
    hash = 508000094

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-types"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-types"

    prefix = "oc-types"

    oc_types_IPV4 = 2050433468
    oc_types_IPV4_ = "IPV4"
    oc_types_IPV6 = 1468531886
    oc_types_IPV6_ = "IPV6"
    oc_types_L2_ETHERNET = 1415666213
    oc_types_L2_ETHERNET_ = "L2_ETHERNET"
    oc_types_ADDRESS_FAMILY = 2015099501
    oc_types_ADDRESS_FAMILY_ = "ADDRESS_FAMILY"
    oc_types_MPLS = 2067937967
    oc_types_MPLS_ = "MPLS"
