#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-platform-port.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-platform-port.yang


class ns(object):
    hash = 848492430

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/port"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/port"

    prefix = "oc-port"

    oc_port_state = 630973766
    oc_port_state_ = "state"
    oc_port_hardware_port = 2121310890
    oc_port_hardware_port_ = "hardware-port"
    oc_port_groups = 575296803
    oc_port_groups_ = "groups"
    oc_port_group = 1540685982
    oc_port_group_ = "group"
    oc_port_num_breakouts = 872287550
    oc_port_num_breakouts_ = "num-breakouts"
    oc_port_breakout_mode = 429492013
    oc_port_breakout_mode_ = "breakout-mode"
    oc_port_config = 2105663071
    oc_port_config_ = "config"
    oc_port_index = 827593980
    oc_port_index_ = "index"
    oc_port_breakout_speed = 1595653044
    oc_port_breakout_speed_ = "breakout-speed"
    oc_port_num_physical_channels = 95222693
    oc_port_num_physical_channels_ = "num-physical-channels"
