#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-sampling.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-sampling.yang


class ns(object):
    hash = 1183398364

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/sampling"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/sampling"

    prefix = "oc-sampling"

    oc_sampling_sampling = 1644225525
    oc_sampling_sampling_ = "sampling"
