#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-platform-controller-card.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-platform-controller-card.yang


class ns(object):
    hash = 1646259851

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/controller-card"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/controller-card"

    prefix = "oc-ctrl-card"

    oc_ctrl_card_power_admin_state = 444634152
    oc_ctrl_card_power_admin_state_ = "power-admin-state"
