#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-optical-amplifier.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-optical-amplifier.yang


class ns(object):
    hash = 2109489472

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/optical-amplfier"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/optical-amplfier"

    prefix = "oc-opt-amp"

    oc_opt_amp_GAIN_RANGE = 223795340
    oc_opt_amp_GAIN_RANGE_ = "GAIN_RANGE"
    oc_opt_amp_DSF = 311577285
    oc_opt_amp_DSF_ = "DSF"
    oc_opt_amp_output_frequency = 884786563
    oc_opt_amp_output_frequency_ = "output-frequency"
    oc_opt_amp_max = 2088175689
    oc_opt_amp_max_ = "max"
    oc_opt_amp_TWC = 1448433078
    oc_opt_amp_TWC_ = "TWC"
    oc_opt_amp_MID_GAIN_RANGE = 256796418
    oc_opt_amp_MID_GAIN_RANGE_ = "MID_GAIN_RANGE"
    oc_opt_amp_supervisory_channels = 403534488
    oc_opt_amp_supervisory_channels_ = "supervisory-channels"
    oc_opt_amp_target_gain_tilt = 281380961
    oc_opt_amp_target_gain_tilt_ = "target-gain-tilt"
    oc_opt_amp_optical_return_loss = 1136259073
    oc_opt_amp_optical_return_loss_ = "optical-return-loss"
    oc_opt_amp_FORWARD_RAMAN = 164208179
    oc_opt_amp_FORWARD_RAMAN_ = "FORWARD_RAMAN"
    oc_opt_amp_enabled = 197426095
    oc_opt_amp_enabled_ = "enabled"
    oc_opt_amp_CONSTANT_POWER = 768939509
    oc_opt_amp_CONSTANT_POWER_ = "CONSTANT_POWER"
    oc_opt_amp_actual_gain = 405966975
    oc_opt_amp_actual_gain_ = "actual-gain"
    oc_opt_amp_actual_gain_tilt = 796778423
    oc_opt_amp_actual_gain_tilt_ = "actual-gain-tilt"
    oc_opt_amp_interval = 559952988
    oc_opt_amp_interval_ = "interval"
    oc_opt_amp_LOW_GAIN_RANGE = 1206922162
    oc_opt_amp_LOW_GAIN_RANGE_ = "LOW_GAIN_RANGE"
    oc_opt_amp_amp_mode = 1348622842
    oc_opt_amp_amp_mode_ = "amp-mode"
    oc_opt_amp_min_time = 1805904672
    oc_opt_amp_min_time_ = "min-time"
    oc_opt_amp_output_power_l_band = 953433346
    oc_opt_amp_output_power_l_band_ = "output-power-l-band"
    oc_opt_amp_amplifier = 645943822
    oc_opt_amp_amplifier_ = "amplifier"
    oc_opt_amp_input_power_total = 593971202
    oc_opt_amp_input_power_total_ = "input-power-total"
    oc_opt_amp_HIGH_GAIN_RANGE = 1838588232
    oc_opt_amp_HIGH_GAIN_RANGE_ = "HIGH_GAIN_RANGE"
    oc_opt_amp_state = 630973766
    oc_opt_amp_state_ = "state"
    oc_opt_amp_input_power_l_band = 1706281405
    oc_opt_amp_input_power_l_band_ = "input-power-l-band"
    oc_opt_amp_fiber_type_profile = 1455574205
    oc_opt_amp_fiber_type_profile_ = "fiber-type-profile"
    oc_opt_amp_min_gain = 181924988
    oc_opt_amp_min_gain_ = "min-gain"
    oc_opt_amp_SSMF = 1596244627
    oc_opt_amp_SSMF_ = "SSMF"
    oc_opt_amp_target_output_power = 1907745428
    oc_opt_amp_target_output_power_ = "target-output-power"
    oc_opt_amp_DYNAMIC_GAIN = 872140987
    oc_opt_amp_DYNAMIC_GAIN_ = "DYNAMIC_GAIN"
    oc_opt_amp_type = 2040883914
    oc_opt_amp_type_ = "type"
    oc_opt_amp_min = 83205090
    oc_opt_amp_min_ = "min"
    oc_opt_amp_HYBRID = 1305289361
    oc_opt_amp_HYBRID_ = "HYBRID"
    oc_opt_amp_LEAF = 268526669
    oc_opt_amp_LEAF_ = "LEAF"
    oc_opt_amp_input_power_c_band = 1924901414
    oc_opt_amp_input_power_c_band_ = "input-power-c-band"
    oc_opt_amp_gain_range = 1185978313
    oc_opt_amp_gain_range_ = "gain-range"
    oc_opt_amp_laser_bias_current = 1521732466
    oc_opt_amp_laser_bias_current_ = "laser-bias-current"
    oc_opt_amp_optical_amplifier = 472808914
    oc_opt_amp_optical_amplifier_ = "optical-amplifier"
    oc_opt_amp_supervisory_channel = 1906266072
    oc_opt_amp_supervisory_channel_ = "supervisory-channel"
    oc_opt_amp_config = 2105663071
    oc_opt_amp_config_ = "config"
    oc_opt_amp_max_output_power = 1793406897
    oc_opt_amp_max_output_power_ = "max-output-power"
    oc_opt_amp_amplifiers = 165367588
    oc_opt_amp_amplifiers_ = "amplifiers"
    oc_opt_amp_output_power = 571387945
    oc_opt_amp_output_power_ = "output-power"
    oc_opt_amp_BACKWARD_RAMAN = 1655772013
    oc_opt_amp_BACKWARD_RAMAN_ = "BACKWARD_RAMAN"
    oc_opt_amp_FIXED_GAIN_RANGE = 1039793810
    oc_opt_amp_FIXED_GAIN_RANGE_ = "FIXED_GAIN_RANGE"
    oc_opt_amp_avg = 2050512522
    oc_opt_amp_avg_ = "avg"
    oc_opt_amp_max_time = 1093347309
    oc_opt_amp_max_time_ = "max-time"
    oc_opt_amp_name = 1998270519
    oc_opt_amp_name_ = "name"
    oc_opt_amp_CONSTANT_GAIN = 201706156
    oc_opt_amp_CONSTANT_GAIN_ = "CONSTANT_GAIN"
    oc_opt_amp_TWRS = 1179074686
    oc_opt_amp_TWRS_ = "TWRS"
    oc_opt_amp_component = 1543026623
    oc_opt_amp_component_ = "component"
    oc_opt_amp_target_gain = 1221172178
    oc_opt_amp_target_gain_ = "target-gain"
    oc_opt_amp_output_power_c_band = 101621813
    oc_opt_amp_output_power_c_band_ = "output-power-c-band"
    oc_opt_amp_interface = 221572658
    oc_opt_amp_interface_ = "interface"
    oc_opt_amp_FIBER_TYPE_PROFILE = 1750213362
    oc_opt_amp_FIBER_TYPE_PROFILE_ = "FIBER_TYPE_PROFILE"
    oc_opt_amp_OPTICAL_AMPLIFIER_MODE = 1108268191
    oc_opt_amp_OPTICAL_AMPLIFIER_MODE_ = "OPTICAL_AMPLIFIER_MODE"
    oc_opt_amp_instant = 2051543381
    oc_opt_amp_instant_ = "instant"
    oc_opt_amp_max_gain = 1978506104
    oc_opt_amp_max_gain_ = "max-gain"
    oc_opt_amp_EDFA = 701500552
    oc_opt_amp_EDFA_ = "EDFA"
    oc_opt_amp_input_power = 1019491846
    oc_opt_amp_input_power_ = "input-power"
    oc_opt_amp_OPTICAL_AMPLIFIER_TYPE = 575825417
    oc_opt_amp_OPTICAL_AMPLIFIER_TYPE_ = "OPTICAL_AMPLIFIER_TYPE"
    oc_opt_amp_output_power_total = 764719814
    oc_opt_amp_output_power_total_ = "output-power-total"
    oc_opt_amp_egress_port = 389091880
    oc_opt_amp_egress_port_ = "egress-port"
    oc_opt_amp_ingress_port = 1493679030
    oc_opt_amp_ingress_port_ = "ingress-port"
