#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-rib-bgp-ext.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-rib-bgp-ext.yang


class ns(object):
    hash = 917647684

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rib/bgp-ext"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rib/bgp-ext"

    prefix = "oc-bgprib-ext"

    oc_bgprib_ext_reject_reason = 1955150025
    oc_bgprib_ext_reject_reason_ = "reject-reason"
