#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-wifi-phy.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-wifi-phy.yang


class ns(object):
    hash = 746713030

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/wifi-phy"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/wifi-phy"

    prefix = "oc-wifi-phy"

    oc_wifi_phy_dfs_hit_time = 15117951
    oc_wifi_phy_dfs_hit_time_ = "dfs-hit-time"
    oc_wifi_phy_neighbor = 81789621
    oc_wifi_phy_neighbor_ = "neighbor"
    oc_wifi_phy_scanning_dwell_time = 448108980
    oc_wifi_phy_scanning_dwell_time_ = "scanning-dwell-time"
    oc_wifi_phy_software_selectable = 304106495
    oc_wifi_phy_software_selectable_ = "software-selectable"
    oc_wifi_phy_operating_frequency = 258493278
    oc_wifi_phy_operating_frequency_ = "operating-frequency"
    oc_wifi_phy_primary_channel = 867652544
    oc_wifi_phy_primary_channel_ = "primary-channel"
    oc_wifi_phy_enabled = 197426095
    oc_wifi_phy_enabled_ = "enabled"
    oc_wifi_phy_WEP = 5
    oc_wifi_phy_WEP_ = "WEP"
    oc_wifi_phy_base_radio_mac = 1212335342
    oc_wifi_phy_base_radio_mac_ = "base-radio-mac"
    oc_wifi_phy_scanning_defer_traffic = 758768712
    oc_wifi_phy_scanning_defer_traffic_ = "scanning-defer-traffic"
    oc_wifi_phy_bss_color_id = 1827855932
    oc_wifi_phy_bss_color_id_ = "bss-color-id"
    oc_wifi_phy_WPA_PERSONAL = 3
    oc_wifi_phy_WPA_PERSONAL_ = "WPA_PERSONAL"
    oc_wifi_phy_rx_noise_channel_utilization = 2020995357
    oc_wifi_phy_rx_noise_channel_utilization_ = "rx-noise-channel-utilization"
    oc_wifi_phy_WPA3_ENTERPRISE = 8
    oc_wifi_phy_WPA3_ENTERPRISE_ = "WPA3_ENTERPRISE"
    oc_wifi_phy_bss_coloring = 1132523191
    oc_wifi_phy_bss_coloring_ = "bss-coloring"
    oc_wifi_phy_state = 630973766
    oc_wifi_phy_state_ = "state"
    oc_wifi_phy_ssid = 829059196
    oc_wifi_phy_ssid_ = "ssid"
    oc_wifi_phy_transmit_eirp = 1065572237
    oc_wifi_phy_transmit_eirp_ = "transmit-eirp"
    oc_wifi_phy_neighbors = 1478644450
    oc_wifi_phy_neighbors_ = "neighbors"
    oc_wifi_phy_noise_floor = 345986689
    oc_wifi_phy_noise_floor_ = "noise-floor"
    oc_wifi_phy_allowed_channels = 1273578867
    oc_wifi_phy_allowed_channels_ = "allowed-channels"
    oc_wifi_phy_dtp = 1386126427
    oc_wifi_phy_dtp_ = "dtp"
    oc_wifi_phy_transmit_power = 2083230338
    oc_wifi_phy_transmit_power_ = "transmit-power"
    oc_wifi_phy_bssid = 899218419
    oc_wifi_phy_bssid_ = "bssid"
    oc_wifi_phy_channel_width = 1760432088
    oc_wifi_phy_channel_width_ = "channel-width"
    oc_wifi_phy_antenna_gain = 1821817617
    oc_wifi_phy_antenna_gain_ = "antenna-gain"
    oc_wifi_phy_dtp_max = 387929790
    oc_wifi_phy_dtp_max_ = "dtp-max"
    oc_wifi_phy_radio = 704661128
    oc_wifi_phy_radio_ = "radio"
    oc_wifi_phy_channel_change_reason = 2041617277
    oc_wifi_phy_channel_change_reason_ = "channel-change-reason"
    oc_wifi_phy_radios = 1196902793
    oc_wifi_phy_radios_ = "radios"
    oc_wifi_phy_total_channel_utilization = 299134300
    oc_wifi_phy_total_channel_utilization_ = "total-channel-utilization"
    oc_wifi_phy_ENHANCED_OPEN = 6
    oc_wifi_phy_ENHANCED_OPEN_ = "ENHANCED_OPEN"
    oc_wifi_phy_dca = 403688283
    oc_wifi_phy_dca_ = "dca"
    oc_wifi_phy_obss_rx = 1559474594
    oc_wifi_phy_obss_rx_ = "obss-rx"
    oc_wifi_phy_opmode = 1025161122
    oc_wifi_phy_opmode_ = "opmode"
    oc_wifi_phy_config = 2105663071
    oc_wifi_phy_config_ = "config"
    oc_wifi_phy_failed_fcs_frames = 768732330
    oc_wifi_phy_failed_fcs_frames_ = "failed-fcs-frames"
    oc_wifi_phy_scanning = 402273914
    oc_wifi_phy_scanning_ = "scanning"
    oc_wifi_phy_counters = 1327053922
    oc_wifi_phy_counters_ = "counters"
    oc_wifi_phy_WPA_ENTERPRISE = 4
    oc_wifi_phy_WPA_ENTERPRISE_ = "WPA_ENTERPRISE"
    oc_wifi_phy_allowed_regulatory_channels = 799972453
    oc_wifi_phy_allowed_regulatory_channels_ = "allowed-regulatory-channels"
    oc_wifi_phy_scanning_interval = 832562255
    oc_wifi_phy_scanning_interval_ = "scanning-interval"
    oc_wifi_phy_WPA2_PERSONAL = 1
    oc_wifi_phy_WPA2_PERSONAL_ = "WPA2_PERSONAL"
    oc_wifi_phy_WPA3_SAE = 7
    oc_wifi_phy_WPA3_SAE_ = "WPA3_SAE"
    oc_wifi_phy_tx_dot11_channel_utilization = 2114749792
    oc_wifi_phy_tx_dot11_channel_utilization_ = "tx-dot11-channel-utilization"
    oc_wifi_phy_dtp_min = 507814863
    oc_wifi_phy_dtp_min_ = "dtp-min"
    oc_wifi_phy_last_seen = 628939602
    oc_wifi_phy_last_seen_ = "last-seen"
    oc_wifi_phy_scanning_defer_clients = 708969856
    oc_wifi_phy_scanning_defer_clients_ = "scanning-defer-clients"
    oc_wifi_phy_rssi = 1763358543
    oc_wifi_phy_rssi_ = "rssi"
    oc_wifi_phy_id = 1279252765
    oc_wifi_phy_id_ = "id"
    oc_wifi_phy_WPA3_ENTERPRISE_192_BIT = 9
    oc_wifi_phy_WPA3_ENTERPRISE_192_BIT_ = "WPA3_ENTERPRISE_192_BIT"
    oc_wifi_phy_channel = 1372178362
    oc_wifi_phy_channel_ = "channel"
    oc_wifi_phy_OPEN = 0
    oc_wifi_phy_OPEN_ = "OPEN"
    oc_wifi_phy_supported_channels = 1686674215
    oc_wifi_phy_supported_channels_ = "supported-channels"
    oc_wifi_phy_WPA2_ENTERPRISE = 2
    oc_wifi_phy_WPA2_ENTERPRISE_ = "WPA2_ENTERPRISE"
    oc_wifi_phy_rx_dot11_channel_utilization = 2049518015
    oc_wifi_phy_rx_dot11_channel_utilization_ = "rx-dot11-channel-utilization"
