#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-pcep.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-pcep.yang


class ns(object):
    hash = 342881269

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/pcep"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/pcep"

    prefix = "oc-pcep"

    oc_pcep_STATEFUL_ACTIVE = 2
    oc_pcep_STATEFUL_ACTIVE_ = "STATEFUL_ACTIVE"
    oc_pcep_PCC_REPORT_ONLY = 2
    oc_pcep_PCC_REPORT_ONLY_ = "PCC_REPORT_ONLY"
    oc_pcep_PCC_CONTROLLED = 1
    oc_pcep_PCC_CONTROLLED_ = "PCC_CONTROLLED"
    oc_pcep_PCE_DELEGATED = 0
    oc_pcep_PCE_DELEGATED_ = "PCE_DELEGATED"
    oc_pcep_STATELESS = 0
    oc_pcep_STATELESS_ = "STATELESS"
    oc_pcep_STATEFUL_PASSIVE = 1
    oc_pcep_STATEFUL_PASSIVE_ = "STATEFUL_PASSIVE"
