#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-transport-line-protection.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-transport-line-protection.yang


class ns(object):
    hash = 806587432

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/optical-transport-line-protection"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/optical-transport-line-protection"

    prefix = "oc-line-protect"

    oc_line_protect_optical_power = 310316755
    oc_line_protect_optical_power_ = "optical-power"
    oc_line_protect_max = 2088175689
    oc_line_protect_max_ = "max"
    oc_line_protect_common_in = 2026646659
    oc_line_protect_common_in_ = "common-in"
    oc_line_protect_primary_switch_hysteresis = 134078249
    oc_line_protect_primary_switch_hysteresis_ = "primary-switch-hysteresis"
    oc_line_protect_APS_PATHS = 438387567
    oc_line_protect_APS_PATHS_ = "APS_PATHS"
    oc_line_protect_wait_to_restore_time = 1695744172
    oc_line_protect_wait_to_restore_time_ = "wait-to-restore-time"
    oc_line_protect_enabled = 197426095
    oc_line_protect_enabled_ = "enabled"
    oc_line_protect_line_primary_out = 1213694906
    oc_line_protect_line_primary_out_ = "line-primary-out"
    oc_line_protect_common_output = 13899150
    oc_line_protect_common_output_ = "common-output"
    oc_line_protect_interval = 559952988
    oc_line_protect_interval_ = "interval"
    oc_line_protect_min_time = 1805904672
    oc_line_protect_min_time_ = "min-time"
    oc_line_protect_state = 630973766
    oc_line_protect_state_ = "state"
    oc_line_protect_line_secondary_in = 1667199995
    oc_line_protect_line_secondary_in_ = "line-secondary-in"
    oc_line_protect_relative_switch_threshold_offset = 503774169
    oc_line_protect_relative_switch_threshold_offset_ = "relative-switch-threshold-offset"
    oc_line_protect_line_secondary_out = 1423041241
    oc_line_protect_line_secondary_out_ = "line-secondary-out"
    oc_line_protect_attenuation = 1694846668
    oc_line_protect_attenuation_ = "attenuation"
    oc_line_protect_aps = 1528266830
    oc_line_protect_aps_ = "aps"
    oc_line_protect_revertive = 1569418781
    oc_line_protect_revertive_ = "revertive"
    oc_line_protect_aps_modules = 1912361995
    oc_line_protect_aps_modules_ = "aps-modules"
    oc_line_protect_aps_module = 407918111
    oc_line_protect_aps_module_ = "aps-module"
    oc_line_protect_target_attenuation = 1586582681
    oc_line_protect_target_attenuation_ = "target-attenuation"
    oc_line_protect_min = 83205090
    oc_line_protect_min_ = "min"
    oc_line_protect_primary_switch_threshold = 56114232
    oc_line_protect_primary_switch_threshold_ = "primary-switch-threshold"
    oc_line_protect_NONE = 0
    oc_line_protect_NONE_ = "NONE"
    oc_line_protect_config = 2105663071
    oc_line_protect_config_ = "config"
    oc_line_protect_ports = 1554580266
    oc_line_protect_ports_ = "ports"
    oc_line_protect_active_path = 1394605946
    oc_line_protect_active_path_ = "active-path"
    oc_line_protect_force_to_port = 1068528734
    oc_line_protect_force_to_port_ = "force-to-port"
    oc_line_protect_avg = 2050512522
    oc_line_protect_avg_ = "avg"
    oc_line_protect_max_time = 1093347309
    oc_line_protect_max_time_ = "max-time"
    oc_line_protect_name = 1998270519
    oc_line_protect_name_ = "name"
    oc_line_protect_line_primary_in = 1011704893
    oc_line_protect_line_primary_in_ = "line-primary-in"
    oc_line_protect_hold_off_time = 1302203176
    oc_line_protect_hold_off_time_ = "hold-off-time"
    oc_line_protect_relative_switch_threshold = 662299997
    oc_line_protect_relative_switch_threshold_ = "relative-switch-threshold"
    oc_line_protect_instant = 2051543381
    oc_line_protect_instant_ = "instant"
    oc_line_protect_secondary_switch_threshold = 571465491
    oc_line_protect_secondary_switch_threshold_ = "secondary-switch-threshold"
