#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-wifi-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-wifi-types.yang


class ns(object):
    hash = 174800356

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/wifi/wifi-types"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/wifi/wifi-types"

    prefix = "oc-wifi-types"

    oc_wifi_types_CLIENT_STATE = 952949869
    oc_wifi_types_CLIENT_STATE_ = "CLIENT_STATE"
    oc_wifi_types_RATE_11MB = 2133946464
    oc_wifi_types_RATE_11MB_ = "RATE_11MB"
    oc_wifi_types_DOT_11R = 1227961071
    oc_wifi_types_DOT_11R_ = "DOT_11R"
    oc_wifi_types_FREQ_2_5_GHZ = 479109896
    oc_wifi_types_FREQ_2_5_GHZ_ = "FREQ_2_5_GHZ"
    oc_wifi_types_FREQ_2_5_6_GHZ = 882423756
    oc_wifi_types_FREQ_2_5_6_GHZ_ = "FREQ_2_5_6_GHZ"
    oc_wifi_types_UPGRADING = 2077378243
    oc_wifi_types_UPGRADING_ = "UPGRADING"
    oc_wifi_types_RATE_48MB = 741377318
    oc_wifi_types_RATE_48MB_ = "RATE_48MB"
    oc_wifi_types_BETTER_CHANNEL = 1878046693
    oc_wifi_types_BETTER_CHANNEL_ = "BETTER_CHANNEL"
    oc_wifi_types_RATE_6MB = 2023003785
    oc_wifi_types_RATE_6MB_ = "RATE_6MB"
    oc_wifi_types_RATE_12MB = 2063758637
    oc_wifi_types_RATE_12MB_ = "RATE_12MB"
    oc_wifi_types_OPERATING_FREQUENCY = 322207171
    oc_wifi_types_OPERATING_FREQUENCY_ = "OPERATING_FREQUENCY"
    oc_wifi_types_FREQ_6GHZ = 951573533
    oc_wifi_types_FREQ_6GHZ_ = "FREQ_6GHZ"
    oc_wifi_types_RATE_36MB = 1954418165
    oc_wifi_types_RATE_36MB_ = "RATE_36MB"
    oc_wifi_types_DOWN = 1781612810
    oc_wifi_types_DOWN_ = "DOWN"
    oc_wifi_types_AUTHENTICATED = 1176749310
    oc_wifi_types_AUTHENTICATED_ = "AUTHENTICATED"
    oc_wifi_types_RATE_18MB = 65823017
    oc_wifi_types_RATE_18MB_ = "RATE_18MB"
    oc_wifi_types_RATE_50x2e5MB = 462630697
    oc_wifi_types_RATE_50x2e5MB_ = "RATE_5.5MB"
    oc_wifi_types_DHCP_REQD = 641033440
    oc_wifi_types_DHCP_REQD_ = "DHCP_REQD"
    oc_wifi_types_AP_STATE = 815051350
    oc_wifi_types_AP_STATE_ = "AP_STATE"
    oc_wifi_types_FREQ_5_6_GHZ = 2043081038
    oc_wifi_types_FREQ_5_6_GHZ_ = "FREQ_5_6_GHZ"
    oc_wifi_types_DFS = 441457722
    oc_wifi_types_DFS_ = "DFS"
    oc_wifi_types_DOT_11V = 600448434
    oc_wifi_types_DOT_11V_ = "DOT_11V"
    oc_wifi_types_RATE_1MB = 1792591095
    oc_wifi_types_RATE_1MB_ = "RATE_1MB"
    oc_wifi_types_MFP = 1666100662
    oc_wifi_types_MFP_ = "MFP"
    oc_wifi_types_L3AUTH_REQD = 1651598272
    oc_wifi_types_L3AUTH_REQD_ = "L3AUTH_REQD"
    oc_wifi_types_L2AUTH_FAILURE_TIMEOUT = 1553003675
    oc_wifi_types_L2AUTH_FAILURE_TIMEOUT_ = "L2AUTH_FAILURE_TIMEOUT"
    oc_wifi_types_RATE_24MB = 1198175976
    oc_wifi_types_RATE_24MB_ = "RATE_24MB"
    oc_wifi_types_FREQ_2GHZ = 869091537
    oc_wifi_types_FREQ_2GHZ_ = "FREQ_2GHZ"
    oc_wifi_types_ASSOCIATED = 119310196
    oc_wifi_types_ASSOCIATED_ = "ASSOCIATED"
    oc_wifi_types_L2AUTH_REQD = 411289209
    oc_wifi_types_L2AUTH_REQD_ = "L2AUTH_REQD"
    oc_wifi_types_OFDMA = 301840878
    oc_wifi_types_OFDMA_ = "OFDMA"
    oc_wifi_types_DHCP_FAILURE = 1885200729
    oc_wifi_types_DHCP_FAILURE_ = "DHCP_FAILURE"
    oc_wifi_types_ERRORS = 710978598
    oc_wifi_types_ERRORS_ = "ERRORS"
    oc_wifi_types_FREQ_5GHZ = 1612121720
    oc_wifi_types_FREQ_5GHZ_ = "FREQ_5GHZ"
    oc_wifi_types_RATE_9MB = 153315519
    oc_wifi_types_RATE_9MB_ = "RATE_9MB"
    oc_wifi_types_CHANGE_REASON_TYPE = 172370898
    oc_wifi_types_CHANGE_REASON_TYPE_ = "CHANGE_REASON_TYPE"
    oc_wifi_types_UP = 82258393
    oc_wifi_types_UP_ = "UP"
    oc_wifi_types_MU_BEAMFORMEE = 1165035199
    oc_wifi_types_MU_BEAMFORMEE_ = "MU_BEAMFORMEE"
    oc_wifi_types_L3AUTH_FAILURE = 1548855534
    oc_wifi_types_L3AUTH_FAILURE_ = "L3AUTH_FAILURE"
    oc_wifi_types_RATE_54MB = 1028314253
    oc_wifi_types_RATE_54MB_ = "RATE_54MB"
    oc_wifi_types_CLIENT_CAPABILITIES = 1992488436
    oc_wifi_types_CLIENT_CAPABILITIES_ = "CLIENT_CAPABILITIES"
    oc_wifi_types_NOISE = 428271887
    oc_wifi_types_NOISE_ = "NOISE"
    oc_wifi_types_L2AUTH_FAILURE_REJECT = 1986466644
    oc_wifi_types_L2AUTH_FAILURE_REJECT_ = "L2AUTH_FAILURE_REJECT"
    oc_wifi_types_POWERSAVE = 1236136921
    oc_wifi_types_POWERSAVE_ = "POWERSAVE"
    oc_wifi_types_MU_BEAMFORMER = 1045037452
    oc_wifi_types_MU_BEAMFORMER_ = "MU_BEAMFORMER"
    oc_wifi_types_RATE_2MB = 1875326045
    oc_wifi_types_RATE_2MB_ = "RATE_2MB"
    oc_wifi_types_BLACKLISTED = 1266899318
    oc_wifi_types_BLACKLISTED_ = "BLACKLISTED"
    oc_wifi_types_DATA_RATE = 1622503507
    oc_wifi_types_DATA_RATE_ = "DATA_RATE"
