#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-bfd.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-bfd.yang


class ns(object):
    hash = 965521844

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/bfd"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/bfd"

    prefix = "oc-bfd"

    oc_bfd_local_discriminator = 968074567
    oc_bfd_local_discriminator_ = "local-discriminator"
    oc_bfd_DETECTION_TIMEOUT = 1
    oc_bfd_DETECTION_TIMEOUT_ = "DETECTION_TIMEOUT"
    oc_bfd_last_packet_transmitted = 1121940878
    oc_bfd_last_packet_transmitted_ = "last-packet-transmitted"
    oc_bfd_remote_session_state = 1414644266
    oc_bfd_remote_session_state_ = "remote-session-state"
    oc_bfd_member_interface = 1434228746
    oc_bfd_member_interface_ = "member-interface"
    oc_bfd_echo = 954217248
    oc_bfd_echo_ = "echo"
    oc_bfd_local_diagnostic_code = 349342118
    oc_bfd_local_diagnostic_code_ = "local-diagnostic-code"
    oc_bfd_interfaces = 321503962
    oc_bfd_interfaces_ = "interfaces"
    oc_bfd_enabled = 197426095
    oc_bfd_enabled_ = "enabled"
    oc_bfd_DOWN = 1
    oc_bfd_DOWN_ = "DOWN"
    oc_bfd_subinterface = 1294223328
    oc_bfd_subinterface_ = "subinterface"
    oc_bfd_micro_bfd_session = 1055177085
    oc_bfd_micro_bfd_session_ = "micro-bfd-session"
    oc_bfd_remote_minimum_receive_interval = 740363723
    oc_bfd_remote_minimum_receive_interval_ = "remote-minimum-receive-interval"
    oc_bfd_interface_ref = 952985348
    oc_bfd_interface_ref_ = "interface-ref"
    oc_bfd_PATH_DOWN = 4
    oc_bfd_PATH_DOWN_ = "PATH_DOWN"
    oc_bfd_state = 630973766
    oc_bfd_state_ = "state"
    oc_bfd_subscribed_protocols = 1406157166
    oc_bfd_subscribed_protocols_ = "subscribed-protocols"
    oc_bfd_local_address = 856636202
    oc_bfd_local_address_ = "local-address"
    oc_bfd_ECHO_FAILED = 2
    oc_bfd_ECHO_FAILED_ = "ECHO_FAILED"
    oc_bfd_NO_DIAGNOSTIC = 0
    oc_bfd_NO_DIAGNOSTIC_ = "NO_DIAGNOSTIC"
    oc_bfd_received_packets = 458197719
    oc_bfd_received_packets_ = "received-packets"
    oc_bfd_last_failure_time = 2146776803
    oc_bfd_last_failure_time_ = "last-failure-time"
    oc_bfd_demand_mode_requested = 753081880
    oc_bfd_demand_mode_requested_ = "demand-mode-requested"
    oc_bfd_enable_per_member_link = 117254987
    oc_bfd_enable_per_member_link_ = "enable-per-member-link"
    oc_bfd_CONCATENATED_PATH_DOWN = 5
    oc_bfd_CONCATENATED_PATH_DOWN_ = "CONCATENATED_PATH_DOWN"
    oc_bfd_failure_transitions = 272899228
    oc_bfd_failure_transitions_ = "failure-transitions"
    oc_bfd_session_state = 113214794
    oc_bfd_session_state_ = "session-state"
    oc_bfd_remote_address = 829475023
    oc_bfd_remote_address_ = "remote-address"
    oc_bfd_remote_discriminator = 1231281115
    oc_bfd_remote_discriminator_ = "remote-discriminator"
    oc_bfd_config = 2105663071
    oc_bfd_config_ = "config"
    oc_bfd_remote_control_plane_independent = 1577008036
    oc_bfd_remote_control_plane_independent_ = "remote-control-plane-independent"
    oc_bfd_desired_minimum_tx_interval = 1752975443
    oc_bfd_desired_minimum_tx_interval_ = "desired-minimum-tx-interval"
    oc_bfd_async = 1368962940
    oc_bfd_async_ = "async"
    oc_bfd_transmitted_packets = 2089984096
    oc_bfd_transmitted_packets_ = "transmitted-packets"
    oc_bfd_peer = 1450174230
    oc_bfd_peer_ = "peer"
    oc_bfd_UP = 0
    oc_bfd_UP_ = "UP"
    oc_bfd_last_packet_received = 132602702
    oc_bfd_last_packet_received_ = "last-packet-received"
    oc_bfd_peers = 958391453
    oc_bfd_peers_ = "peers"
    oc_bfd_required_minimum_receive = 747584394
    oc_bfd_required_minimum_receive_ = "required-minimum-receive"
    oc_bfd_detection_multiplier = 1584191488
    oc_bfd_detection_multiplier_ = "detection-multiplier"
    oc_bfd_remote_authentication_enabled = 258181007
    oc_bfd_remote_authentication_enabled_ = "remote-authentication-enabled"
    oc_bfd_up_transitions = 649368090
    oc_bfd_up_transitions_ = "up-transitions"
    oc_bfd_remote_diagnostic_code = 102118665
    oc_bfd_remote_diagnostic_code_ = "remote-diagnostic-code"
    oc_bfd_bfd = 788285710
    oc_bfd_bfd_ = "bfd"
    oc_bfd_interface = 221572658
    oc_bfd_interface_ = "interface"
    oc_bfd_active = 124277386
    oc_bfd_active_ = "active"
    oc_bfd_micro_bfd_sessions = 1052751491
    oc_bfd_micro_bfd_sessions_ = "micro-bfd-sessions"
    oc_bfd_FORWARDING_RESET = 3
    oc_bfd_FORWARDING_RESET_ = "FORWARDING_RESET"
    oc_bfd_INIT = 3
    oc_bfd_INIT_ = "INIT"
    oc_bfd_id = 1279252765
    oc_bfd_id_ = "id"
    oc_bfd_REVERSE_CONCATENATED_PATH_DOWN = 7
    oc_bfd_REVERSE_CONCATENATED_PATH_DOWN_ = "REVERSE_CONCATENATED_PATH_DOWN"
