#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-interfaces.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-interfaces.yang


class ns(object):
    hash = 1637833021

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/interfaces"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/interfaces"

    prefix = "oc-if"

    oc_if_out_pkts = 335453834
    oc_if_out_pkts_ = "out-pkts"
    oc_if_subinterfaces = 1730428758
    oc_if_subinterfaces_ = "subinterfaces"
    oc_if_carrier_transitions = 1056552358
    oc_if_carrier_transitions_ = "carrier-transitions"
    oc_if_in_multicast_pkts = 1126031588
    oc_if_in_multicast_pkts_ = "in-multicast-pkts"
    oc_if_out_octets = 2123582464
    oc_if_out_octets_ = "out-octets"
    oc_if_cpu = 1825182739
    oc_if_cpu_ = "cpu"
    oc_if_out_broadcast_pkts = 1427076806
    oc_if_out_broadcast_pkts_ = "out-broadcast-pkts"
    oc_if_up = 1984149991
    oc_if_up_ = "up"
    oc_if_ifindex = 1259815303
    oc_if_ifindex_ = "ifindex"
    oc_if_interfaces = 321503962
    oc_if_interfaces_ = "interfaces"
    oc_if_enabled = 197426095
    oc_if_enabled_ = "enabled"
    oc_if_subinterface = 1294223328
    oc_if_subinterface_ = "subinterface"
    oc_if_in_pkts = 1264605324
    oc_if_in_pkts_ = "in-pkts"
    oc_if_loopback_mode = 2918605
    oc_if_loopback_mode_ = "loopback-mode"
    oc_if_logical = 2102296514
    oc_if_logical_ = "logical"
    oc_if_state = 630973766
    oc_if_state_ = "state"
    oc_if_in_unicast_pkts = 1100444555
    oc_if_in_unicast_pkts_ = "in-unicast-pkts"
    oc_if_LOWER_LAYER_DOWN = 7
    oc_if_LOWER_LAYER_DOWN_ = "LOWER_LAYER_DOWN"
    oc_if_DORMANT = 5
    oc_if_DORMANT_ = "DORMANT"
    oc_if_type = 2040883914
    oc_if_type_ = "type"
    oc_if_admin_status = 2104862928
    oc_if_admin_status_ = "admin-status"
    oc_if_in_discards = 1607867097
    oc_if_in_discards_ = "in-discards"
    oc_if_in_errors = 419802148
    oc_if_in_errors_ = "in-errors"
    oc_if_in_unknown_protos = 1961345832
    oc_if_in_unknown_protos_ = "in-unknown-protos"
    oc_if_management = 1308506682
    oc_if_management_ = "management"
    oc_if_down = 940209651
    oc_if_down_ = "down"
    oc_if_mtu = 1751455506
    oc_if_mtu_ = "mtu"
    oc_if_config = 2105663071
    oc_if_config_ = "config"
    oc_if_in_fcs_errors = 422454373
    oc_if_in_fcs_errors_ = "in-fcs-errors"
    oc_if_NOT_PRESENT = 6
    oc_if_NOT_PRESENT_ = "NOT_PRESENT"
    oc_if_hold_time = 204730640
    oc_if_hold_time_ = "hold-time"
    oc_if_index = 827593980
    oc_if_index_ = "index"
    oc_if_counters = 1327053922
    oc_if_counters_ = "counters"
    oc_if_in_octets = 1354763654
    oc_if_in_octets_ = "in-octets"
    oc_if_out_errors = 1825475719
    oc_if_out_errors_ = "out-errors"
    oc_if_in_broadcast_pkts = 1140019954
    oc_if_in_broadcast_pkts_ = "in-broadcast-pkts"
    oc_if_name = 1998270519
    oc_if_name_ = "name"
    oc_if_UNKNOWN = 4
    oc_if_UNKNOWN_ = "UNKNOWN"
    oc_if_out_multicast_pkts = 723352241
    oc_if_out_multicast_pkts_ = "out-multicast-pkts"
    oc_if_last_change = 2008341778
    oc_if_last_change_ = "last-change"
    oc_if_oper_status = 1906453952
    oc_if_oper_status_ = "oper-status"
    oc_if_interface = 221572658
    oc_if_interface_ = "interface"
    oc_if_out_unicast_pkts = 170730703
    oc_if_out_unicast_pkts_ = "out-unicast-pkts"
    oc_if_description = 202559156
    oc_if_description_ = "description"
    oc_if_last_clear = 1168907511
    oc_if_last_clear_ = "last-clear"
    oc_if_out_discards = 2051284211
    oc_if_out_discards_ = "out-discards"
