#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-spanning-tree-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-spanning-tree-types.yang


class ns(object):
    hash = 1177165426

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/spanning-tree/types"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/spanning-tree/types"

    prefix = "oc-stp-types"

    oc_stp_types_EDGE_DISABLE = 1731833628
    oc_stp_types_EDGE_DISABLE_ = "EDGE_DISABLE"
    oc_stp_types_DISABLED = 1464461520
    oc_stp_types_DISABLED_ = "DISABLED"
    oc_stp_types_P2P = 0
    oc_stp_types_P2P_ = "P2P"
    oc_stp_types_BLOCKING = 128750559
    oc_stp_types_BLOCKING_ = "BLOCKING"
    oc_stp_types_DESIGNATED = 1718513210
    oc_stp_types_DESIGNATED_ = "DESIGNATED"
    oc_stp_types_EDGE_ENABLE = 597127690
    oc_stp_types_EDGE_ENABLE_ = "EDGE_ENABLE"
    oc_stp_types_STP_PORT_ROLE = 1684464888
    oc_stp_types_STP_PORT_ROLE_ = "STP_PORT_ROLE"
    oc_stp_types_RAPID_PVST = 1598086486
    oc_stp_types_RAPID_PVST_ = "RAPID_PVST"
    oc_stp_types_STP_PORT_STATE = 1120212852
    oc_stp_types_STP_PORT_STATE_ = "STP_PORT_STATE"
    oc_stp_types_LISTENING = 1926419948
    oc_stp_types_LISTENING_ = "LISTENING"
    oc_stp_types_FORWARDING = 1009932180
    oc_stp_types_FORWARDING_ = "FORWARDING"
    oc_stp_types_STP_EDGE_PORT = 1802194878
    oc_stp_types_STP_EDGE_PORT_ = "STP_EDGE_PORT"
    oc_stp_types_NONE = 2
    oc_stp_types_NONE_ = "NONE"
    oc_stp_types_LEARNING = 727262580
    oc_stp_types_LEARNING_ = "LEARNING"
    oc_stp_types_SHARED = 1
    oc_stp_types_SHARED_ = "SHARED"
    oc_stp_types_ALTERNATE = 1900624787
    oc_stp_types_ALTERNATE_ = "ALTERNATE"
    oc_stp_types_STP_PROTOCOL = 1957829784
    oc_stp_types_STP_PROTOCOL_ = "STP_PROTOCOL"
    oc_stp_types_BACKUP = 1824483253
    oc_stp_types_BACKUP_ = "BACKUP"
    oc_stp_types_MSTP = 1990524089
    oc_stp_types_MSTP_ = "MSTP"
    oc_stp_types_LOOP = 1
    oc_stp_types_LOOP_ = "LOOP"
    oc_stp_types_RSTP = 777592312
    oc_stp_types_RSTP_ = "RSTP"
    oc_stp_types_EDGE_AUTO = 925487535
    oc_stp_types_EDGE_AUTO_ = "EDGE_AUTO"
