#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-openflow.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-openflow.yang


class ns(object):
    hash = 217007103

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openflow"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openflow"

    prefix = "openflow"

    openflow_datapath_id = 1605175629
    openflow_datapath_id_ = "datapath-id"
    openflow_connection = 1134114300
    openflow_connection_ = "connection"
    openflow_port = 10387472
    openflow_port_ = "port"
    openflow_openflow = 491007989
    openflow_openflow_ = "openflow"
    openflow_state = 630973766
    openflow_state_ = "state"
    openflow_failure_mode = 1732372867
    openflow_failure_mode_ = "failure-mode"
    openflow_priority = 1346277862
    openflow_priority_ = "priority"
    openflow_controllers = 1302107053
    openflow_controllers_ = "controllers"
    openflow_certificate_id = 371782284
    openflow_certificate_id_ = "certificate-id"
    openflow_config = 2105663071
    openflow_config_ = "config"
    openflow_max_backoff = 108437373
    openflow_max_backoff_ = "max-backoff"
    openflow_agent = 15006109
    openflow_agent_ = "agent"
    openflow_connections = 1259277820
    openflow_connections_ = "connections"
    openflow_connected = 1024392365
    openflow_connected_ = "connected"
    openflow_name = 1998270519
    openflow_name_ = "name"
    openflow_controller = 1295630195
    openflow_controller_ = "controller"
    openflow_transport = 514190987
    openflow_transport_ = "transport"
    openflow_source_interface = 1180772123
    openflow_source_interface_ = "source-interface"
    openflow_backoff_interval = 1559355679
    openflow_backoff_interval_ = "backoff-interval"
    openflow_inactivity_probe = 1957849095
    openflow_inactivity_probe_ = "inactivity-probe"
    openflow_address = 1266954393
    openflow_address_ = "address"
    openflow_aux_id = 1024671845
    openflow_aux_id_ = "aux-id"
