#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-telemetry.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-telemetry.yang


class ns(object):
    hash = 1527053704

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/telemetry"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/telemetry"

    prefix = "oc-telemetry"

    oc_telemetry_sample_interval = 1730479987
    oc_telemetry_sample_interval_ = "sample-interval"
    oc_telemetry_path = 1002915403
    oc_telemetry_path_ = "path"
    oc_telemetry_destination_group = 1598383525
    oc_telemetry_destination_group_ = "destination-group"
    oc_telemetry_suppress_redundant = 1367205526
    oc_telemetry_suppress_redundant_ = "suppress-redundant"
    oc_telemetry_sensor_profile = 1970107157
    oc_telemetry_sensor_profile_ = "sensor-profile"
    oc_telemetry_sensor_paths = 1692117363
    oc_telemetry_sensor_paths_ = "sensor-paths"
    oc_telemetry_encoding = 180862443
    oc_telemetry_encoding_ = "encoding"
    oc_telemetry_sensor_group = 521692491
    oc_telemetry_sensor_group_ = "sensor-group"
    oc_telemetry_destination = 1426812369
    oc_telemetry_destination_ = "destination"
    oc_telemetry_group_id = 2095068827
    oc_telemetry_group_id_ = "group-id"
    oc_telemetry_persistent_subscription = 1373683679
    oc_telemetry_persistent_subscription_ = "persistent-subscription"
    oc_telemetry_sensor_groups = 1378032050
    oc_telemetry_sensor_groups_ = "sensor-groups"
    oc_telemetry_dynamic_subscriptions = 358197336
    oc_telemetry_dynamic_subscriptions_ = "dynamic-subscriptions"
    oc_telemetry_state = 630973766
    oc_telemetry_state_ = "state"
    oc_telemetry_dynamic_subscription = 1460307865
    oc_telemetry_dynamic_subscription_ = "dynamic-subscription"
    oc_telemetry_destination_port = 1685436757
    oc_telemetry_destination_port_ = "destination-port"
    oc_telemetry_local_source_address = 1348732713
    oc_telemetry_local_source_address_ = "local-source-address"
    oc_telemetry_destination_groups = 676110724
    oc_telemetry_destination_groups_ = "destination-groups"
    oc_telemetry_sensor_path = 424127023
    oc_telemetry_sensor_path_ = "sensor-path"
    oc_telemetry_destination_address = 1799113401
    oc_telemetry_destination_address_ = "destination-address"
    oc_telemetry_config = 2105663071
    oc_telemetry_config_ = "config"
    oc_telemetry_telemetry_system = 658036610
    oc_telemetry_telemetry_system_ = "telemetry-system"
    oc_telemetry_sensor_profiles = 2055311817
    oc_telemetry_sensor_profiles_ = "sensor-profiles"
    oc_telemetry_exclude_filter = 1205417205
    oc_telemetry_exclude_filter_ = "exclude-filter"
    oc_telemetry_sensor_group_id = 1378386708
    oc_telemetry_sensor_group_id_ = "sensor-group-id"
    oc_telemetry_name = 1998270519
    oc_telemetry_name_ = "name"
    oc_telemetry_destinations = 1001041063
    oc_telemetry_destinations_ = "destinations"
    oc_telemetry_heartbeat_interval = 1281304246
    oc_telemetry_heartbeat_interval_ = "heartbeat-interval"
    oc_telemetry_subscriptions = 886823438
    oc_telemetry_subscriptions_ = "subscriptions"
    oc_telemetry_originated_qos_marking = 324407343
    oc_telemetry_originated_qos_marking_ = "originated-qos-marking"
    oc_telemetry_protocol = 943257313
    oc_telemetry_protocol_ = "protocol"
    oc_telemetry_id = 1279252765
    oc_telemetry_id_ = "id"
    oc_telemetry_persistent_subscriptions = 1211207143
    oc_telemetry_persistent_subscriptions_ = "persistent-subscriptions"
