#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-extensions.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-extensions.yang


class ns(object):
    hash = 2049145129

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-ext"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-ext"

    prefix = "oc-ext"

