#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-channel-monitor.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-channel-monitor.yang


class ns(object):
    hash = 148574970

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/channel-monitor"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/channel-monitor"

    prefix = "oc-chan-monitor"

    oc_chan_monitor_lower_frequency = 297729851
    oc_chan_monitor_lower_frequency_ = "lower-frequency"
    oc_chan_monitor_power = 2065308511
    oc_chan_monitor_power_ = "power"
    oc_chan_monitor_state = 630973766
    oc_chan_monitor_state_ = "state"
    oc_chan_monitor_monitor_port = 281931278
    oc_chan_monitor_monitor_port_ = "monitor-port"
    oc_chan_monitor_channels = 1961956329
    oc_chan_monitor_channels_ = "channels"
    oc_chan_monitor_config = 2105663071
    oc_chan_monitor_config_ = "config"
    oc_chan_monitor_name = 1998270519
    oc_chan_monitor_name_ = "name"
    oc_chan_monitor_channel_monitors = 698396811
    oc_chan_monitor_channel_monitors_ = "channel-monitors"
    oc_chan_monitor_channel_monitor = 1756443751
    oc_chan_monitor_channel_monitor_ = "channel-monitor"
    oc_chan_monitor_channel = 1372178362
    oc_chan_monitor_channel_ = "channel"
    oc_chan_monitor_upper_frequency = 2069940695
    oc_chan_monitor_upper_frequency_ = "upper-frequency"
