#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-ospf-policy.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-ospf-policy.yang


class ns(object):
    hash = 832693542

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ospf-policy"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ospf-policy"

    prefix = "oc-ospf-pol"

    oc_ospf_pol_metric_type = 855418505
    oc_ospf_pol_metric_type_ = "metric-type"
    oc_ospf_pol_state = 630973766
    oc_ospf_pol_state_ = "state"
    oc_ospf_pol_area_eq = 517549606
    oc_ospf_pol_area_eq_ = "area-eq"
    oc_ospf_pol_ospf_conditions = 1195133234
    oc_ospf_pol_ospf_conditions_ = "ospf-conditions"
    oc_ospf_pol_set_metric = 881511190
    oc_ospf_pol_set_metric_ = "set-metric"
    oc_ospf_pol_EXTERNAL_TYPE_2 = 1
    oc_ospf_pol_EXTERNAL_TYPE_2_ = "EXTERNAL_TYPE_2"
    oc_ospf_pol_config = 2105663071
    oc_ospf_pol_config_ = "config"
    oc_ospf_pol_metric = 235154778
    oc_ospf_pol_metric_ = "metric"
    oc_ospf_pol_ospf_actions = 1757142546
    oc_ospf_pol_ospf_actions_ = "ospf-actions"
    oc_ospf_pol_set_area = 611036431
    oc_ospf_pol_set_area_ = "set-area"
    oc_ospf_pol_EXTERNAL_TYPE_1 = 0
    oc_ospf_pol_EXTERNAL_TYPE_1_ = "EXTERNAL_TYPE_1"
