#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-mpls-rsvp.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-mpls-rsvp.yang


class ns(object):
    hash = 1556649230

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rsvp"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rsvp"

    prefix = "oc-rsvp"

    oc_rsvp_UNNUMBERED_INTERFACE = 5
    oc_rsvp_UNNUMBERED_INTERFACE_ = "UNNUMBERED_INTERFACE"
    oc_rsvp_DOWN = 1
    oc_rsvp_DOWN_ = "DOWN"
    oc_rsvp_IPV4 = 0
    oc_rsvp_IPV4_ = "IPV4"
    oc_rsvp_IPV6 = 1
    oc_rsvp_IPV6_ = "IPV6"
    oc_rsvp_UP = 0
    oc_rsvp_UP_ = "UP"
    oc_rsvp_ASN4 = 3
    oc_rsvp_ASN4_ = "ASN4"
    oc_rsvp_ASN = 2
    oc_rsvp_ASN_ = "ASN"
    oc_rsvp_LABEL = 4
    oc_rsvp_LABEL_ = "LABEL"
