/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/ietf-interfaces.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module ietf-interfaces.yang */
public class ietfInterfaces extends ConfNamespace {
    public static final int hash = 886813517;
    public int hash() {
        return ietfInterfaces.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#urn:ietf:params:xml:ns:yang:ietf-interfaces";
    public String id() {
        return ietfInterfaces.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#urn:ietf:params:xml:ns:yang:ietf-interfaces";
    public String uri() {
        return ietfInterfaces.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(ietfInterfaces.uri);
    }

    public static final String prefix = "if";
    public String prefix() {
        return ietfInterfaces.prefix;
    }

    public ietfInterfaces() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _in_multicast_pkts = 1126031588;
    public static final String _in_multicast_pkts_ = "in-multicast-pkts";
    public static final int    _interface_type = 1566485963;
    public static final String _interface_type_ = "interface-type";
    public static final int    _out_octets = 2123582464;
    public static final String _out_octets_ = "out-octets";
    public static final int    _discontinuity_time = 318342031;
    public static final String _discontinuity_time_ = "discontinuity-time";
    public static final int    _out_broadcast_pkts = 1427076806;
    public static final String _out_broadcast_pkts_ = "out-broadcast-pkts";
    public static final int    _interfaces_state = 2120054373;
    public static final String _interfaces_state_ = "interfaces-state";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _statistics = 1049034618;
    public static final String _statistics_ = "statistics";
    public static final int    _in_unicast_pkts = 1100444555;
    public static final String _in_unicast_pkts_ = "in-unicast-pkts";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _admin_status = 2104862928;
    public static final String _admin_status_ = "admin-status";
    public static final int    _in_discards = 1607867097;
    public static final String _in_discards_ = "in-discards";
    public static final int    _in_errors = 419802148;
    public static final String _in_errors_ = "in-errors";
    public static final int    _in_unknown_protos = 1961345832;
    public static final String _in_unknown_protos_ = "in-unknown-protos";
    public static final int    _link_up_down_trap_enable = 1552886723;
    public static final String _link_up_down_trap_enable_ = "link-up-down-trap-enable";
    public static final int    _speed = 1423237997;
    public static final String _speed_ = "speed";
    public static final int    _in_octets = 1354763654;
    public static final String _in_octets_ = "in-octets";
    public static final int    _out_errors = 1825475719;
    public static final String _out_errors_ = "out-errors";
    public static final int    _in_broadcast_pkts = 1140019954;
    public static final String _in_broadcast_pkts_ = "in-broadcast-pkts";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _phys_address = 1102597279;
    public static final String _phys_address_ = "phys-address";
    public static final int    _higher_layer_if = 750793054;
    public static final String _higher_layer_if_ = "higher-layer-if";
    public static final int    _out_multicast_pkts = 723352241;
    public static final String _out_multicast_pkts_ = "out-multicast-pkts";
    public static final int    _last_change = 2008341778;
    public static final String _last_change_ = "last-change";
    public static final int    _oper_status = 1906453952;
    public static final String _oper_status_ = "oper-status";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _if_index = 216876767;
    public static final String _if_index_ = "if-index";
    public static final int    _out_unicast_pkts = 170730703;
    public static final String _out_unicast_pkts_ = "out-unicast-pkts";
    public static final int    _lower_layer_if = 247228720;
    public static final String _lower_layer_if_ = "lower-layer-if";
    public static final int    _description = 202559156;
    public static final String _description_ = "description";
    public static final int    _out_discards = 2051284211;
    public static final String _out_discards_ = "out-discards";
}
