/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-fw-link-monitoring.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-fw-link-monitoring.yang */
public class openconfigFwLinkMonitoring extends ConfNamespace {
    public static final int hash = 233547271;
    public int hash() {
        return openconfigFwLinkMonitoring.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-fw-link-monitoring";
    public String id() {
        return openconfigFwLinkMonitoring.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-fw-link-monitoring";
    public String uri() {
        return openconfigFwLinkMonitoring.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigFwLinkMonitoring.uri);
    }

    public static final String prefix = "oc-fw-linkmon";
    public String prefix() {
        return openconfigFwLinkMonitoring.prefix;
    }

    public openconfigFwLinkMonitoring() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
