/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-wifi-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-wifi-types.yang */
public class openconfigWifiTypes extends ConfNamespace {
    public static final int hash = 174800356;
    public int hash() {
        return openconfigWifiTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/wifi/wifi-types";
    public String id() {
        return openconfigWifiTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/wifi/wifi-types";
    public String uri() {
        return openconfigWifiTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigWifiTypes.uri);
    }

    public static final String prefix = "oc-wifi-types";
    public String prefix() {
        return openconfigWifiTypes.prefix;
    }

    public openconfigWifiTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _CLIENT_STATE = 952949869;
    public static final String _CLIENT_STATE_ = "CLIENT_STATE";
    public static final int    _RATE_11MB = 2133946464;
    public static final String _RATE_11MB_ = "RATE_11MB";
    public static final int    _DOT_11R = 1227961071;
    public static final String _DOT_11R_ = "DOT_11R";
    public static final int    _FREQ_2_5_GHZ = 479109896;
    public static final String _FREQ_2_5_GHZ_ = "FREQ_2_5_GHZ";
    public static final int    _FREQ_2_5_6_GHZ = 882423756;
    public static final String _FREQ_2_5_6_GHZ_ = "FREQ_2_5_6_GHZ";
    public static final int    _UPGRADING = 2077378243;
    public static final String _UPGRADING_ = "UPGRADING";
    public static final int    _RATE_48MB = 741377318;
    public static final String _RATE_48MB_ = "RATE_48MB";
    public static final int    _BETTER_CHANNEL = 1878046693;
    public static final String _BETTER_CHANNEL_ = "BETTER_CHANNEL";
    public static final int    _RATE_6MB = 2023003785;
    public static final String _RATE_6MB_ = "RATE_6MB";
    public static final int    _RATE_12MB = 2063758637;
    public static final String _RATE_12MB_ = "RATE_12MB";
    public static final int    _OPERATING_FREQUENCY = 322207171;
    public static final String _OPERATING_FREQUENCY_ = "OPERATING_FREQUENCY";
    public static final int    _FREQ_6GHZ = 951573533;
    public static final String _FREQ_6GHZ_ = "FREQ_6GHZ";
    public static final int    _RATE_36MB = 1954418165;
    public static final String _RATE_36MB_ = "RATE_36MB";
    public static final int    _DOWN = 1781612810;
    public static final String _DOWN_ = "DOWN";
    public static final int    _AUTHENTICATED = 1176749310;
    public static final String _AUTHENTICATED_ = "AUTHENTICATED";
    public static final int    _RATE_18MB = 65823017;
    public static final String _RATE_18MB_ = "RATE_18MB";
    public static final int    _RATE_50x2e5MB = 462630697;
    public static final String _RATE_50x2e5MB_ = "RATE_5.5MB";
    public static final int    _DHCP_REQD = 641033440;
    public static final String _DHCP_REQD_ = "DHCP_REQD";
    public static final int    _AP_STATE = 815051350;
    public static final String _AP_STATE_ = "AP_STATE";
    public static final int    _FREQ_5_6_GHZ = 2043081038;
    public static final String _FREQ_5_6_GHZ_ = "FREQ_5_6_GHZ";
    public static final int    _DFS = 441457722;
    public static final String _DFS_ = "DFS";
    public static final int    _DOT_11V = 600448434;
    public static final String _DOT_11V_ = "DOT_11V";
    public static final int    _RATE_1MB = 1792591095;
    public static final String _RATE_1MB_ = "RATE_1MB";
    public static final int    _MFP = 1666100662;
    public static final String _MFP_ = "MFP";
    public static final int    _L3AUTH_REQD = 1651598272;
    public static final String _L3AUTH_REQD_ = "L3AUTH_REQD";
    public static final int    _L2AUTH_FAILURE_TIMEOUT = 1553003675;
    public static final String _L2AUTH_FAILURE_TIMEOUT_ = "L2AUTH_FAILURE_TIMEOUT";
    public static final int    _RATE_24MB = 1198175976;
    public static final String _RATE_24MB_ = "RATE_24MB";
    public static final int    _FREQ_2GHZ = 869091537;
    public static final String _FREQ_2GHZ_ = "FREQ_2GHZ";
    public static final int    _ASSOCIATED = 119310196;
    public static final String _ASSOCIATED_ = "ASSOCIATED";
    public static final int    _L2AUTH_REQD = 411289209;
    public static final String _L2AUTH_REQD_ = "L2AUTH_REQD";
    public static final int    _OFDMA = 301840878;
    public static final String _OFDMA_ = "OFDMA";
    public static final int    _DHCP_FAILURE = 1885200729;
    public static final String _DHCP_FAILURE_ = "DHCP_FAILURE";
    public static final int    _ERRORS = 710978598;
    public static final String _ERRORS_ = "ERRORS";
    public static final int    _FREQ_5GHZ = 1612121720;
    public static final String _FREQ_5GHZ_ = "FREQ_5GHZ";
    public static final int    _RATE_9MB = 153315519;
    public static final String _RATE_9MB_ = "RATE_9MB";
    public static final int    _CHANGE_REASON_TYPE = 172370898;
    public static final String _CHANGE_REASON_TYPE_ = "CHANGE_REASON_TYPE";
    public static final int    _UP = 82258393;
    public static final String _UP_ = "UP";
    public static final int    _MU_BEAMFORMEE = 1165035199;
    public static final String _MU_BEAMFORMEE_ = "MU_BEAMFORMEE";
    public static final int    _L3AUTH_FAILURE = 1548855534;
    public static final String _L3AUTH_FAILURE_ = "L3AUTH_FAILURE";
    public static final int    _RATE_54MB = 1028314253;
    public static final String _RATE_54MB_ = "RATE_54MB";
    public static final int    _CLIENT_CAPABILITIES = 1992488436;
    public static final String _CLIENT_CAPABILITIES_ = "CLIENT_CAPABILITIES";
    public static final int    _NOISE = 428271887;
    public static final String _NOISE_ = "NOISE";
    public static final int    _L2AUTH_FAILURE_REJECT = 1986466644;
    public static final String _L2AUTH_FAILURE_REJECT_ = "L2AUTH_FAILURE_REJECT";
    public static final int    _POWERSAVE = 1236136921;
    public static final String _POWERSAVE_ = "POWERSAVE";
    public static final int    _MU_BEAMFORMER = 1045037452;
    public static final String _MU_BEAMFORMER_ = "MU_BEAMFORMER";
    public static final int    _RATE_2MB = 1875326045;
    public static final String _RATE_2MB_ = "RATE_2MB";
    public static final int    _BLACKLISTED = 1266899318;
    public static final String _BLACKLISTED_ = "BLACKLISTED";
    public static final int    _DATA_RATE = 1622503507;
    public static final String _DATA_RATE_ = "DATA_RATE";
}
