/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-transport-line-connectivity.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-transport-line-connectivity.yang */
public class openconfigTransportLineConnectivity extends ConfNamespace {
    public static final int hash = 2063687039;
    public int hash() {
        return openconfigTransportLineConnectivity.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-transport-line-connectivity";
    public String id() {
        return openconfigTransportLineConnectivity.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-transport-line-connectivity";
    public String uri() {
        return openconfigTransportLineConnectivity.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigTransportLineConnectivity.uri);
    }

    public static final String prefix = "oc-line-connect";
    public String prefix() {
        return openconfigTransportLineConnectivity.prefix;
    }

    public openconfigTransportLineConnectivity() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _connection = 1134114300;
    public static final String _connection_ = "connection";
    public static final int    _dest = 1478643067;
    public static final String _dest_ = "dest";
    public static final int    _source = 1141829056;
    public static final String _source_ = "source";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _PORT_CONNECTION_TYPE = 1007059418;
    public static final String _PORT_CONNECTION_TYPE_ = "PORT_CONNECTION_TYPE";
    public static final int    _fiber_type = 1613900476;
    public static final String _fiber_type_ = "fiber-type";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _index = 827593980;
    public static final String _index_ = "index";
    public static final int    _EXTERNAL = 1708429095;
    public static final String _EXTERNAL_ = "EXTERNAL";
    public static final int    _connections = 1259277820;
    public static final String _connections_ = "connections";
}
