/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-network-instance-l3.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-network-instance-l3.yang */
public class openconfigNetworkInstanceL3 extends ConfNamespace {
    public static final int hash = 1649887946;
    public int hash() {
        return openconfigNetworkInstanceL3.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/network-instance-l3";
    public String id() {
        return openconfigNetworkInstanceL3.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/network-instance-l3";
    public String uri() {
        return openconfigNetworkInstanceL3.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigNetworkInstanceL3.uri);
    }

    public static final String prefix = "oc-ni-l3";
    public String prefix() {
        return openconfigNetworkInstanceL3.prefix;
    }

    public openconfigNetworkInstanceL3() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
