/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-terminal-device-property-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-terminal-device-property-types.yang */
public class openconfigTerminalDevicePropertyTypes extends ConfNamespace {
    public static final int hash = 1912288498;
    public int hash() {
        return openconfigTerminalDevicePropertyTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://example.net/yang/openconfig-terminal-device-property-types";
    public String id() {
        return openconfigTerminalDevicePropertyTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://example.net/yang/openconfig-terminal-device-property-types";
    public String uri() {
        return openconfigTerminalDevicePropertyTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigTerminalDevicePropertyTypes.uri);
    }

    public static final String prefix = "oc-opt-term-prop-types";
    public String prefix() {
        return openconfigTerminalDevicePropertyTypes.prefix;
    }

    public openconfigTerminalDevicePropertyTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _ADJUSTMENT_GRANULARITY = 46926221;
    public static final String _ADJUSTMENT_GRANULARITY_ = "ADJUSTMENT_GRANULARITY";
    public static final int    _MODULATION_FORMAT_64QAM = 323334316;
    public static final String _MODULATION_FORMAT_64QAM_ = "MODULATION_FORMAT_64QAM";
    public static final int    _UNSPECIFIED = 723886692;
    public static final String _UNSPECIFIED_ = "UNSPECIFIED";
    public static final int    _MODULATION_FORMAT_DP_32QAM = 88555661;
    public static final String _MODULATION_FORMAT_DP_32QAM_ = "MODULATION_FORMAT_DP_32QAM";
    public static final int    _SHAPING_TYPE = 1588053289;
    public static final String _SHAPING_TYPE_ = "SHAPING_TYPE";
    public static final int    _MODULATION_FORMAT_BPSK = 905979364;
    public static final String _MODULATION_FORMAT_BPSK_ = "MODULATION_FORMAT_BPSK";
    public static final int    _TRANSCEIVER_MODE_TYPE_EXPLICIT = 90517129;
    public static final String _TRANSCEIVER_MODE_TYPE_EXPLICIT_ = "TRANSCEIVER_MODE_TYPE_EXPLICIT";
    public static final int    _MODULATION_FORMAT_DPSK = 364023509;
    public static final String _MODULATION_FORMAT_DPSK_ = "MODULATION_FORMAT_DPSK";
    public static final int    _MODULATION_FORMAT_DC_DP_64QAM = 1656004684;
    public static final String _MODULATION_FORMAT_DC_DP_64QAM_ = "MODULATION_FORMAT_DC_DP_64QAM";
    public static final int    _CD_PS_NM = 14600909;
    public static final String _CD_PS_NM_ = "CD_PS_NM";
    public static final int    _TRANSCEIVER_MODE_TYPE_STANDARD = 1131802017;
    public static final String _TRANSCEIVER_MODE_TYPE_STANDARD_ = "TRANSCEIVER_MODE_TYPE_STANDARD";
    public static final int    _FEC_E = 891045592;
    public static final String _FEC_E_ = "FEC_E";
    public static final int    _MODULATION_FORMAT_PAM8 = 1376341307;
    public static final String _MODULATION_FORMAT_PAM8_ = "MODULATION_FORMAT_PAM8";
    public static final int    _FEC_G = 1717115823;
    public static final String _FEC_G_ = "FEC_G";
    public static final int    _RC = 1595782611;
    public static final String _RC_ = "RC";
    public static final int    _MODULATION_FORMAT_32QAM = 1127783280;
    public static final String _MODULATION_FORMAT_32QAM_ = "MODULATION_FORMAT_32QAM";
    public static final int    _PDL_DB = 523741302;
    public static final String _PDL_DB_ = "PDL_DB";
    public static final int    _MODULATION_FORMAT_QPSK = 962781047;
    public static final String _MODULATION_FORMAT_QPSK_ = "MODULATION_FORMAT_QPSK";
    public static final int    _FEC_C = 1966462633;
    public static final String _FEC_C_ = "FEC_C";
    public static final int    _G_50GHZ = 1063038026;
    public static final String _G_50GHZ_ = "G_50GHZ";
    public static final int    _RRC = 140553445;
    public static final String _RRC_ = "RRC";
    public static final int    _MODULATION_FORMAT_DC_DP_16QAM = 385032979;
    public static final String _MODULATION_FORMAT_DC_DP_16QAM_ = "MODULATION_FORMAT_DC_DP_16QAM";
    public static final int    _FEC = 1824304257;
    public static final String _FEC_ = "FEC";
    public static final int    _G_3_125GHZ = 756935463;
    public static final String _G_3_125GHZ_ = "G_3_125GHZ";
    public static final int    _G_25GHZ = 871132125;
    public static final String _G_25GHZ_ = "G_25GHZ";
    public static final int    _CWDM = 315259850;
    public static final String _CWDM_ = "CWDM";
    public static final int    _FEC_OTHER = 1234385461;
    public static final String _FEC_OTHER_ = "FEC_OTHER";
    public static final int    _FLEX = 1453942473;
    public static final String _FLEX_ = "FLEX";
    public static final int    _MODULATION_FORMAT_DC_DP_8QAM = 1784803324;
    public static final String _MODULATION_FORMAT_DC_DP_8QAM_ = "MODULATION_FORMAT_DC_DP_8QAM";
    public static final int    _TRANSCEIVER_MODE_TYPE = 1905974487;
    public static final String _TRANSCEIVER_MODE_TYPE_ = "TRANSCEIVER_MODE_TYPE";
    public static final int    _MODULATION_FORMAT_PAM4 = 7025561;
    public static final String _MODULATION_FORMAT_PAM4_ = "MODULATION_FORMAT_PAM4";
    public static final int    _FEC_O = 2087256938;
    public static final String _FEC_O_ = "FEC_O";
    public static final int    _PMD_PS = 23067444;
    public static final String _PMD_PS_ = "PMD_PS";
    public static final int    _MODULATION_FORMAT_8QAM = 663136940;
    public static final String _MODULATION_FORMAT_8QAM_ = "MODULATION_FORMAT_8QAM";
    public static final int    _MODULATION_FORMAT_16QAM = 2087269376;
    public static final String _MODULATION_FORMAT_16QAM_ = "MODULATION_FORMAT_16QAM";
    public static final int    _MODULATION_FORMAT_DP_8QAM = 404959224;
    public static final String _MODULATION_FORMAT_DP_8QAM_ = "MODULATION_FORMAT_DP_8QAM";
    public static final int    _MODULATION_FORMAT_DP_16QAM = 1405104528;
    public static final String _MODULATION_FORMAT_DP_16QAM_ = "MODULATION_FORMAT_DP_16QAM";
    public static final int    _MODULATION_FORMAT_PROPRIETARY = 1596804338;
    public static final String _MODULATION_FORMAT_PROPRIETARY_ = "MODULATION_FORMAT_PROPRIETARY";
    public static final int    _GRID_TYPE = 1089936915;
    public static final String _GRID_TYPE_ = "GRID_TYPE";
    public static final int    _FEC_HD = 1863035650;
    public static final String _FEC_HD_ = "FEC_HD";
    public static final int    _UNCONSTRAINED = 298224154;
    public static final String _UNCONSTRAINED_ = "UNCONSTRAINED";
    public static final int    _G_6_25GHZ = 947882027;
    public static final String _G_6_25GHZ_ = "G_6_25GHZ";
    public static final int    _G_100GHZ = 612063798;
    public static final String _G_100GHZ_ = "G_100GHZ";
    public static final int    _DWDM = 11631793;
    public static final String _DWDM_ = "DWDM";
    public static final int    _MODULATION_FORMAT = 1230767504;
    public static final String _MODULATION_FORMAT_ = "MODULATION_FORMAT";
    public static final int    _MODULATION_FORMAT_DP_QPSK = 641392521;
    public static final String _MODULATION_FORMAT_DP_QPSK_ = "MODULATION_FORMAT_DP_QPSK";
    public static final int    _OFF = 2072370329;
    public static final String _OFF_ = "OFF";
    public static final int    _MODULATION_FORMAT_DC_DP_32QAM = 1664096805;
    public static final String _MODULATION_FORMAT_DC_DP_32QAM_ = "MODULATION_FORMAT_DC_DP_32QAM";
    public static final int    _IMPAIRMENT_TYPE = 1943676821;
    public static final String _IMPAIRMENT_TYPE_ = "IMPAIRMENT_TYPE";
    public static final int    _GRIDLESS = 984583523;
    public static final String _GRIDLESS_ = "GRIDLESS";
    public static final int    _MODULATION_FORMAT_DP_64QAM = 780931619;
    public static final String _MODULATION_FORMAT_DP_64QAM_ = "MODULATION_FORMAT_DP_64QAM";
    public static final int    _G_12_5GHZ = 107827371;
    public static final String _G_12_5GHZ_ = "G_12_5GHZ";
}
