/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-probes.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-probes.yang */
public class openconfigProbes extends ConfNamespace {
    public static final int hash = 2028471624;
    public int hash() {
        return openconfigProbes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/probes";
    public String id() {
        return openconfigProbes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/probes";
    public String uri() {
        return openconfigProbes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigProbes.uri);
    }

    public static final String prefix = "oc-probes";
    public String prefix() {
        return openconfigProbes.prefix;
    }

    public openconfigProbes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _test_duration = 339206802;
    public static final String _test_duration_ = "test-duration";
    public static final int    _count = 180894398;
    public static final String _count_ = "count";
    public static final int    _test = 151660234;
    public static final String _test_ = "test";
    public static final int    _results = 609602154;
    public static final String _results_ = "results";
    public static final int    _history_size = 1520089433;
    public static final String _history_size_ = "history-size";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _url = 1560781157;
    public static final String _url_ = "url";
    public static final int    _target = 1914145912;
    public static final String _target_ = "target";
    public static final int    _jitter = 965990611;
    public static final String _jitter_ = "jitter";
    public static final int    _item = 1470352621;
    public static final String _item_ = "item";
    public static final int    _port = 10387472;
    public static final String _port_ = "port";
    public static final int    _interval = 559952988;
    public static final String _interval_ = "interval";
    public static final int    _source = 1141829056;
    public static final String _source_ = "source";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _probe = 1118433712;
    public static final String _probe_ = "probe";
    public static final int    _probes_received = 954288172;
    public static final String _probes_received_ = "probes-received";
    public static final int    _min_delay = 498309688;
    public static final String _min_delay_ = "min-delay";
    public static final int    _stddev_delay = 63702773;
    public static final String _stddev_delay_ = "stddev-delay";
    public static final int    _last_test_timestamp = 803282817;
    public static final String _last_test_timestamp_ = "last-test-timestamp";
    public static final int    _failed = 244831632;
    public static final String _failed_ = "failed";
    public static final int    _source_port = 256320896;
    public static final String _source_port_ = "source-port";
    public static final int    _items = 2098922342;
    public static final String _items_ = "items";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _test_type = 1741501172;
    public static final String _test_type_ = "test-type";
    public static final int    _probes = 726461839;
    public static final String _probes_ = "probes";
    public static final int    _tests = 336696582;
    public static final String _tests_ = "tests";
    public static final int    _timestamp = 35058824;
    public static final String _timestamp_ = "timestamp";
    public static final int    _history = 919502929;
    public static final String _history_ = "history";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _max_delay = 1211843452;
    public static final String _max_delay_ = "max-delay";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _end_timestamp = 2086710081;
    public static final String _end_timestamp_ = "end-timestamp";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _start_timestamp = 1495048809;
    public static final String _start_timestamp_ = "start-timestamp";
    public static final int    _avg_delay = 1515425507;
    public static final String _avg_delay_ = "avg-delay";
    public static final int    _dscp = 1118112132;
    public static final String _dscp_ = "dscp";
    public static final int    _probes_sent = 270075407;
    public static final String _probes_sent_ = "probes-sent";
    public static final int    _loss_percentage = 1322897060;
    public static final String _loss_percentage_ = "loss-percentage";
}
