/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-srte-policy.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-srte-policy.yang */
public class openconfigSrtePolicy extends ConfNamespace {
    public static final int hash = 1549670759;
    public int hash() {
        return openconfigSrtePolicy.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/segment-routing/srte-policy";
    public String id() {
        return openconfigSrtePolicy.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/segment-routing/srte-policy";
    public String uri() {
        return openconfigSrtePolicy.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigSrtePolicy.uri);
    }

    public static final String prefix = "oc-srte";
    public String prefix() {
        return openconfigSrtePolicy.prefix;
    }

    public openconfigSrtePolicy() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
