/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-rsvp-sr-ext.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-rsvp-sr-ext.yang */
public class openconfigRsvpSrExt extends ConfNamespace {
    public static final int hash = 628766684;
    public int hash() {
        return openconfigRsvpSrExt.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rsvp-sr-ext";
    public String id() {
        return openconfigRsvpSrExt.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rsvp-sr-ext";
    public String uri() {
        return openconfigRsvpSrExt.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigRsvpSrExt.uri);
    }

    public static final String prefix = "oc-sr-rsvp-ext";
    public String prefix() {
        return openconfigRsvpSrExt.prefix;
    }

    public openconfigRsvpSrExt() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _bandwidth_multiplier = 1219499947;
    public static final String _bandwidth_multiplier_ = "bandwidth-multiplier";
    public static final int    _bandwidth_measurement = 634253161;
    public static final String _bandwidth_measurement_ = "bandwidth-measurement";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _last_calculated_sr_utilisation = 426411958;
    public static final String _last_calculated_sr_utilisation_ = "last-calculated-sr-utilisation";
    public static final int    _adjustment_interval = 13482291;
    public static final String _adjustment_interval_ = "adjustment-interval";
    public static final int    _adjusted_absolute_subscription_bw = 947916735;
    public static final String _adjusted_absolute_subscription_bw_ = "adjusted-absolute-subscription-bw";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _collection_interval = 880323978;
    public static final String _collection_interval_ = "collection-interval";
    public static final int    _last_calculated_time = 211199008;
    public static final String _last_calculated_time_ = "last-calculated-time";
    public static final int    _last_sample_measured_rsvp_util = 475520912;
    public static final String _last_sample_measured_rsvp_util_ = "last-sample-measured-rsvp-util";
    public static final int    _last_sample_measured_sr_util = 1879456218;
    public static final String _last_sample_measured_sr_util_ = "last-sample-measured-sr-util";
    public static final int    _effective_adjustment_interval = 622159440;
    public static final String _effective_adjustment_interval_ = "effective-adjustment-interval";
    public static final int    _adjusted_max_reservable_bw_pct = 1500910758;
    public static final String _adjusted_max_reservable_bw_pct_ = "adjusted-max-reservable-bw-pct";
    public static final int    _measure_sr_traffic = 381453395;
    public static final String _measure_sr_traffic_ = "measure-sr-traffic";
    public static final int    _last_flooded_time = 336790771;
    public static final String _last_flooded_time_ = "last-flooded-time";
    public static final int    _last_sample_time = 1978518778;
    public static final String _last_sample_time_ = "last-sample-time";
    public static final int    _update_trigger = 400709998;
    public static final String _update_trigger_ = "update-trigger";
    public static final int    _sr_traffic_pct = 1794406695;
    public static final String _sr_traffic_pct_ = "sr-traffic-pct";
}
