/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-yang-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-yang-types.yang */
public class openconfigYangTypes extends ConfNamespace {
    public static final int hash = 131710919;
    public int hash() {
        return openconfigYangTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/types/yang";
    public String id() {
        return openconfigYangTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/types/yang";
    public String uri() {
        return openconfigYangTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigYangTypes.uri);
    }

    public static final String prefix = "oc-yang";
    public String prefix() {
        return openconfigYangTypes.prefix;
    }

    public openconfigYangTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
