/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-igmp-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-igmp-types.yang */
public class openconfigIgmpTypes extends ConfNamespace {
    public static final int hash = 2134997153;
    public int hash() {
        return openconfigIgmpTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/igmp/types";
    public String id() {
        return openconfigIgmpTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/igmp/types";
    public String uri() {
        return openconfigIgmpTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigIgmpTypes.uri);
    }

    public static final String prefix = "oc-igmp-types";
    public String prefix() {
        return openconfigIgmpTypes.prefix;
    }

    public openconfigIgmpTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
