/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-pim.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-pim.yang */
public class openconfigPim extends ConfNamespace {
    public static final int hash = 203565799;
    public int hash() {
        return openconfigPim.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/pim";
    public String id() {
        return openconfigPim.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/pim";
    public String uri() {
        return openconfigPim.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigPim.uri);
    }

    public static final String prefix = "oc-pim";
    public String prefix() {
        return openconfigPim.prefix;
    }

    public openconfigPim() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
