/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-ospfv2.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-ospfv2.yang */
public class openconfigOspfv2 extends ConfNamespace {
    public static final int hash = 94690678;
    public int hash() {
        return openconfigOspfv2.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ospfv2";
    public String id() {
        return openconfigOspfv2.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ospfv2";
    public String uri() {
        return openconfigOspfv2.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigOspfv2.uri);
    }

    public static final String prefix = "oc-ospfv2";
    public String prefix() {
        return openconfigOspfv2.prefix;
    }

    public openconfigOspfv2() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
