/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-types.yang */
public class openconfigTypes extends ConfNamespace {
    public static final int hash = 508000094;
    public int hash() {
        return openconfigTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-types";
    public String id() {
        return openconfigTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-types";
    public String uri() {
        return openconfigTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigTypes.uri);
    }

    public static final String prefix = "oc-types";
    public String prefix() {
        return openconfigTypes.prefix;
    }

    public openconfigTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _IPV4 = 2050433468;
    public static final String _IPV4_ = "IPV4";
    public static final int    _IPV6 = 1468531886;
    public static final String _IPV6_ = "IPV6";
    public static final int    _L2_ETHERNET = 1415666213;
    public static final String _L2_ETHERNET_ = "L2_ETHERNET";
    public static final int    _ADDRESS_FAMILY = 2015099501;
    public static final String _ADDRESS_FAMILY_ = "ADDRESS_FAMILY";
    public static final int    _MPLS = 2067937967;
    public static final String _MPLS_ = "MPLS";
}
