/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-if-aggregate.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-if-aggregate.yang */
public class openconfigIfAggregate extends ConfNamespace {
    public static final int hash = 289559046;
    public int hash() {
        return openconfigIfAggregate.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/interfaces/aggregate";
    public String id() {
        return openconfigIfAggregate.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/interfaces/aggregate";
    public String uri() {
        return openconfigIfAggregate.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigIfAggregate.uri);
    }

    public static final String prefix = "oc-lag";
    public String prefix() {
        return openconfigIfAggregate.prefix;
    }

    public openconfigIfAggregate() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _lag_type = 1214577214;
    public static final String _lag_type_ = "lag-type";
    public static final int    _aggregate_id = 448835689;
    public static final String _aggregate_id_ = "aggregate-id";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _lag_speed = 899368516;
    public static final String _lag_speed_ = "lag-speed";
    public static final int    _aggregation = 640445680;
    public static final String _aggregation_ = "aggregation";
    public static final int    _member = 387693123;
    public static final String _member_ = "member";
    public static final int    _min_links = 1996282515;
    public static final String _min_links_ = "min-links";
}
