/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-segment-routing-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-segment-routing-types.yang */
public class openconfigSegmentRoutingTypes extends ConfNamespace {
    public static final int hash = 1409378949;
    public int hash() {
        return openconfigSegmentRoutingTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/segment-routing-types";
    public String id() {
        return openconfigSegmentRoutingTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/segment-routing-types";
    public String uri() {
        return openconfigSegmentRoutingTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigSegmentRoutingTypes.uri);
    }

    public static final String prefix = "oc-srt";
    public String prefix() {
        return openconfigSegmentRoutingTypes.prefix;
    }

    public openconfigSegmentRoutingTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
