/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-vlan.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-vlan.yang */
public class openconfigVlan extends ConfNamespace {
    public static final int hash = 228085247;
    public int hash() {
        return openconfigVlan.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/vlan";
    public String id() {
        return openconfigVlan.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/vlan";
    public String uri() {
        return openconfigVlan.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigVlan.uri);
    }

    public static final String prefix = "oc-vlan";
    public String prefix() {
        return openconfigVlan.prefix;
    }

    public openconfigVlan() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _trunk_vlans = 1077818890;
    public static final String _trunk_vlans_ = "trunk-vlans";
    public static final int    _inner_low_vlan_id = 1559851846;
    public static final String _inner_low_vlan_id_ = "inner-low-vlan-id";
    public static final int    _vlan_id = 1443431623;
    public static final String _vlan_id_ = "vlan-id";
    public static final int    _single_tagged_range = 703910030;
    public static final String _single_tagged_range_ = "single-tagged-range";
    public static final int    _outer_vlan_id = 2008251797;
    public static final String _outer_vlan_id_ = "outer-vlan-id";
    public static final int    _inner_vlan_ids = 303498286;
    public static final String _inner_vlan_ids_ = "inner-vlan-ids";
    public static final int    _outer_high_vlan_id = 1823628390;
    public static final String _outer_high_vlan_id_ = "outer-high-vlan-id";
    public static final int    _switched_vlan = 1368499734;
    public static final String _switched_vlan_ = "switched-vlan";
    public static final int    _vlan = 71481437;
    public static final String _vlan_ = "vlan";
    public static final int    _interface_mode = 1229050048;
    public static final String _interface_mode_ = "interface-mode";
    public static final int    _inner_vlan_id = 333468475;
    public static final String _inner_vlan_id_ = "inner-vlan-id";
    public static final int    _double_tagged_inner_range = 884213616;
    public static final String _double_tagged_inner_range_ = "double-tagged-inner-range";
    public static final int    _inner_high_vlan_id = 253530737;
    public static final String _inner_high_vlan_id_ = "inner-high-vlan-id";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _native_vlan = 1159886695;
    public static final String _native_vlan_ = "native-vlan";
    public static final int    _vlan_stack_action = 1541409462;
    public static final String _vlan_stack_action_ = "vlan-stack-action";
    public static final int    _double_tagged_inner_outer_range = 177199481;
    public static final String _double_tagged_inner_outer_range_ = "double-tagged-inner-outer-range";
    public static final int    _match = 1501964518;
    public static final String _match_ = "match";
    public static final int    _low_vlan_id = 2143350458;
    public static final String _low_vlan_id_ = "low-vlan-id";
    public static final int    _single_tagged = 1338140550;
    public static final String _single_tagged_ = "single-tagged";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _outer_vlan_ids = 2044724970;
    public static final String _outer_vlan_ids_ = "outer-vlan-ids";
    public static final int    _high_vlan_id = 190189862;
    public static final String _high_vlan_id_ = "high-vlan-id";
    public static final int    _egress_mapping = 1659599184;
    public static final String _egress_mapping_ = "egress-mapping";
    public static final int    _double_tagged = 30146062;
    public static final String _double_tagged_ = "double-tagged";
    public static final int    _routed_vlan = 1375184969;
    public static final String _routed_vlan_ = "routed-vlan";
    public static final int    _tpid = 1809362859;
    public static final String _tpid_ = "tpid";
    public static final int    _single_tagged_list = 890964007;
    public static final String _single_tagged_list_ = "single-tagged-list";
    public static final int    _access_vlan = 2014822852;
    public static final String _access_vlan_ = "access-vlan";
    public static final int    _outer_low_vlan_id = 1166184422;
    public static final String _outer_low_vlan_id_ = "outer-low-vlan-id";
    public static final int    _double_tagged_outer_range = 454624053;
    public static final String _double_tagged_outer_range_ = "double-tagged-outer-range";
    public static final int    _double_tagged_inner_list = 897542526;
    public static final String _double_tagged_inner_list_ = "double-tagged-inner-list";
    public static final int    _ingress_mapping = 367656293;
    public static final String _ingress_mapping_ = "ingress-mapping";
    public static final int    _vlan_ids = 310768076;
    public static final String _vlan_ids_ = "vlan-ids";
    public static final int    _double_tagged_outer_list = 1425449404;
    public static final String _double_tagged_outer_list_ = "double-tagged-outer-list";
}
