/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-pcep.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-pcep.yang */
public class openconfigPcep extends ConfNamespace {
    public static final int hash = 342881269;
    public int hash() {
        return openconfigPcep.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/pcep";
    public String id() {
        return openconfigPcep.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/pcep";
    public String uri() {
        return openconfigPcep.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigPcep.uri);
    }

    public static final String prefix = "oc-pcep";
    public String prefix() {
        return openconfigPcep.prefix;
    }

    public openconfigPcep() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
