/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-platform-psu.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-platform-psu.yang */
public class openconfigPlatformPsu extends ConfNamespace {
    public static final int hash = 474980313;
    public int hash() {
        return openconfigPlatformPsu.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/psu";
    public String id() {
        return openconfigPlatformPsu.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/psu";
    public String uri() {
        return openconfigPlatformPsu.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigPlatformPsu.uri);
    }

    public static final String prefix = "oc-platform-psu";
    public String prefix() {
        return openconfigPlatformPsu.prefix;
    }

    public openconfigPlatformPsu() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _output_voltage = 1366260725;
    public static final String _output_voltage_ = "output-voltage";
    public static final int    _input_current = 820465870;
    public static final String _input_current_ = "input-current";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _output_current = 1258195278;
    public static final String _output_current_ = "output-current";
    public static final int    _capacity = 191070892;
    public static final String _capacity_ = "capacity";
    public static final int    _output_power = 571387945;
    public static final String _output_power_ = "output-power";
    public static final int    _input_voltage = 1875433346;
    public static final String _input_voltage_ = "input-voltage";
}
