/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-p4rt.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-p4rt.yang */
public class openconfigP4rt extends ConfNamespace {
    public static final int hash = 21518831;
    public int hash() {
        return openconfigP4rt.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/p4rt";
    public String id() {
        return openconfigP4rt.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/p4rt";
    public String uri() {
        return openconfigP4rt.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigP4rt.uri);
    }

    public static final String prefix = "oc-p4rt";
    public String prefix() {
        return openconfigP4rt.prefix;
    }

    public openconfigP4rt() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _node_id = 98319925;
    public static final String _node_id_ = "node-id";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _P4RT = 1548290100;
    public static final String _P4RT_ = "P4RT";
}
