/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-rib-bgp-ext.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-rib-bgp-ext.yang */
public class openconfigRibBgpExt extends ConfNamespace {
    public static final int hash = 917647684;
    public int hash() {
        return openconfigRibBgpExt.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rib/bgp-ext";
    public String id() {
        return openconfigRibBgpExt.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rib/bgp-ext";
    public String uri() {
        return openconfigRibBgpExt.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigRibBgpExt.uri);
    }

    public static final String prefix = "oc-bgprib-ext";
    public String prefix() {
        return openconfigRibBgpExt.prefix;
    }

    public openconfigRibBgpExt() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _reject_reason = 1955150025;
    public static final String _reject_reason_ = "reject-reason";
}
