/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-platform-integrated-circuit.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-platform-integrated-circuit.yang */
public class openconfigPlatformIntegratedCircuit extends ConfNamespace {
    public static final int hash = 1336651448;
    public int hash() {
        return openconfigPlatformIntegratedCircuit.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/integrated-circuit";
    public String id() {
        return openconfigPlatformIntegratedCircuit.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/integrated-circuit";
    public String uri() {
        return openconfigPlatformIntegratedCircuit.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigPlatformIntegratedCircuit.uri);
    }

    public static final String prefix = "oc-ic";
    public String prefix() {
        return openconfigPlatformIntegratedCircuit.prefix;
    }

    public openconfigPlatformIntegratedCircuit() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _memory = 1156186237;
    public static final String _memory_ = "memory";
    public static final int    _backplane_facing_capacity = 735618595;
    public static final String _backplane_facing_capacity_ = "backplane-facing-capacity";
    public static final int    _total_operational_capacity = 1998482726;
    public static final String _total_operational_capacity_ = "total-operational-capacity";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _total = 482693535;
    public static final String _total_ = "total";
    public static final int    _corrected_parity_errors = 1496395732;
    public static final String _corrected_parity_errors_ = "corrected-parity-errors";
    public static final int    _consumed_capacity = 1833194233;
    public static final String _consumed_capacity_ = "consumed-capacity";
    public static final int    _available_pct = 642264506;
    public static final String _available_pct_ = "available-pct";
    public static final int    _total_parity_errors = 1681903356;
    public static final String _total_parity_errors_ = "total-parity-errors";
    public static final int    _uncorrected_parity_errors = 1937875829;
    public static final String _uncorrected_parity_errors_ = "uncorrected-parity-errors";
}
