/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-telemetry-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-telemetry-types.yang */
public class openconfigTelemetryTypes extends ConfNamespace {
    public static final int hash = 200621933;
    public int hash() {
        return openconfigTelemetryTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/telemetry-types";
    public String id() {
        return openconfigTelemetryTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/telemetry-types";
    public String uri() {
        return openconfigTelemetryTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigTelemetryTypes.uri);
    }

    public static final String prefix = "oc-telemetry-types";
    public String prefix() {
        return openconfigTelemetryTypes.prefix;
    }

    public openconfigTelemetryTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _DATA_ENCODING_METHOD = 864500188;
    public static final String _DATA_ENCODING_METHOD_ = "DATA_ENCODING_METHOD";
    public static final int    _STREAM_SSH = 1748818774;
    public static final String _STREAM_SSH_ = "STREAM_SSH";
    public static final int    _STREAM_THRIFT_RPC = 2066710899;
    public static final String _STREAM_THRIFT_RPC_ = "STREAM_THRIFT_RPC";
    public static final int    _STREAM_GRPC = 442300132;
    public static final String _STREAM_GRPC_ = "STREAM_GRPC";
    public static final int    _ENC_PROTO3 = 679227105;
    public static final String _ENC_PROTO3_ = "ENC_PROTO3";
    public static final int    _ENC_JSON_IETF = 810803199;
    public static final String _ENC_JSON_IETF_ = "ENC_JSON_IETF";
    public static final int    _STREAM_WEBSOCKET_RPC = 891393615;
    public static final String _STREAM_WEBSOCKET_RPC_ = "STREAM_WEBSOCKET_RPC";
    public static final int    _STREAM_PROTOCOL = 1998828232;
    public static final String _STREAM_PROTOCOL_ = "STREAM_PROTOCOL";
    public static final int    _STREAM_JSON_RPC = 412762089;
    public static final String _STREAM_JSON_RPC_ = "STREAM_JSON_RPC";
    public static final int    _ENC_XML = 1958722388;
    public static final String _ENC_XML_ = "ENC_XML";
}
