/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-rib-bgp.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-rib-bgp.yang */
public class openconfigRibBgp extends ConfNamespace {
    public static final int hash = 88752953;
    public int hash() {
        return openconfigRibBgp.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rib/bgp";
    public String id() {
        return openconfigRibBgp.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rib/bgp";
    public String uri() {
        return openconfigRibBgp.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigRibBgp.uri);
    }

    public static final String prefix = "oc-rib-bgp";
    public String prefix() {
        return openconfigRibBgp.prefix;
    }

    public openconfigRibBgp() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
