/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-network-instance-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-network-instance-types.yang */
public class openconfigNetworkInstanceTypes extends ConfNamespace {
    public static final int hash = 1905621350;
    public int hash() {
        return openconfigNetworkInstanceTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/network-instance-types";
    public String id() {
        return openconfigNetworkInstanceTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/network-instance-types";
    public String uri() {
        return openconfigNetworkInstanceTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigNetworkInstanceTypes.uri);
    }

    public static final String prefix = "oc-ni-types";
    public String prefix() {
        return openconfigNetworkInstanceTypes.prefix;
    }

    public openconfigNetworkInstanceTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _LOCAL = 460621875;
    public static final String _LOCAL_ = "LOCAL";
    public static final int    _L2VSI = 54139560;
    public static final String _L2VSI_ = "L2VSI";
    public static final int    _L2L3 = 549903540;
    public static final String _L2L3_ = "L2L3";
    public static final int    _L3VRF = 1684502484;
    public static final String _L3VRF_ = "L3VRF";
    public static final int    _SIGNALLING_PROTOCOL = 1324016391;
    public static final String _SIGNALLING_PROTOCOL_ = "SIGNALLING_PROTOCOL";
    public static final int    _LABEL_ALLOCATION_MODE = 729169488;
    public static final String _LABEL_ALLOCATION_MODE_ = "LABEL_ALLOCATION_MODE";
    public static final int    _NETWORK_INSTANCE_TYPE = 691911598;
    public static final String _NETWORK_INSTANCE_TYPE_ = "NETWORK_INSTANCE_TYPE";
    public static final int    _VXLAN = 1449468224;
    public static final String _VXLAN_ = "VXLAN";
    public static final int    _ENDPOINT_TYPE = 97140199;
    public static final String _ENDPOINT_TYPE_ = "ENDPOINT_TYPE";
    public static final int    _ENCAPSULATION = 1893057283;
    public static final String _ENCAPSULATION_ = "ENCAPSULATION";
    public static final int    _REMOTE = 1111950581;
    public static final String _REMOTE_ = "REMOTE";
    public static final int    _BGP_EVPN = 17969827;
    public static final String _BGP_EVPN_ = "BGP_EVPN";
    public static final int    _L2P2P = 1871119045;
    public static final String _L2P2P_ = "L2P2P";
    public static final int    _PER_PREFIX = 932560854;
    public static final String _PER_PREFIX_ = "PER_PREFIX";
    public static final int    _INSTANCE_LABEL = 1331221488;
    public static final String _INSTANCE_LABEL_ = "INSTANCE_LABEL";
    public static final int    _DEFAULT_INSTANCE = 899602892;
    public static final String _DEFAULT_INSTANCE_ = "DEFAULT_INSTANCE";
    public static final int    _LDP = 1944089980;
    public static final String _LDP_ = "LDP";
    public static final int    _MPLS = 2067937967;
    public static final String _MPLS_ = "MPLS";
    public static final int    _BGP_VPLS = 178280769;
    public static final String _BGP_VPLS_ = "BGP_VPLS";
    public static final int    _PER_NEXTHOP = 1781188095;
    public static final String _PER_NEXTHOP_ = "PER_NEXTHOP";
}
