/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-extensions.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-extensions.yang */
public class openconfigExtensions extends ConfNamespace {
    public static final int hash = 2049145129;
    public int hash() {
        return openconfigExtensions.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-ext";
    public String id() {
        return openconfigExtensions.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-ext";
    public String uri() {
        return openconfigExtensions.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigExtensions.uri);
    }

    public static final String prefix = "oc-ext";
    public String prefix() {
        return openconfigExtensions.prefix;
    }

    public openconfigExtensions() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
