/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-platform-controller-card.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-platform-controller-card.yang */
public class openconfigPlatformControllerCard extends ConfNamespace {
    public static final int hash = 1646259851;
    public int hash() {
        return openconfigPlatformControllerCard.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/controller-card";
    public String id() {
        return openconfigPlatformControllerCard.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/controller-card";
    public String uri() {
        return openconfigPlatformControllerCard.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigPlatformControllerCard.uri);
    }

    public static final String prefix = "oc-ctrl-card";
    public String prefix() {
        return openconfigPlatformControllerCard.prefix;
    }

    public openconfigPlatformControllerCard() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _power_admin_state = 444634152;
    public static final String _power_admin_state_ = "power-admin-state";
}
