/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-macsec-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-macsec-types.yang */
public class openconfigMacsecTypes extends ConfNamespace {
    public static final int hash = 1856349470;
    public int hash() {
        return openconfigMacsecTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/macsec/types";
    public String id() {
        return openconfigMacsecTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/macsec/types";
    public String uri() {
        return openconfigMacsecTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigMacsecTypes.uri);
    }

    public static final String prefix = "oc-macsect";
    public String prefix() {
        return openconfigMacsecTypes.prefix;
    }

    public openconfigMacsecTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
