/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-mpls-sr.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-mpls-sr.yang */
public class openconfigMplsSr extends ConfNamespace {
    public static final int hash = 2091975827;
    public int hash() {
        return openconfigMplsSr.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/mpls-sr";
    public String id() {
        return openconfigMplsSr.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/mpls-sr";
    public String uri() {
        return openconfigMplsSr.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigMplsSr.uri);
    }

    public static final String prefix = "oc-mpls-sr";
    public String prefix() {
        return openconfigMplsSr.prefix;
    }

    public openconfigMplsSr() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

}
