/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-pim-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-pim-types.yang */
public class openconfigPimTypes extends ConfNamespace {
    public static final int hash = 376938377;
    public int hash() {
        return openconfigPimTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/pim/types";
    public String id() {
        return openconfigPimTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/pim/types";
    public String uri() {
        return openconfigPimTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigPimTypes.uri);
    }

    public static final String prefix = "oc-pim-types";
    public String prefix() {
        return openconfigPimTypes.prefix;
    }

    public openconfigPimTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _PIM_MODE = 1303515708;
    public static final String _PIM_MODE_ = "PIM_MODE";
    public static final int    _PIM_MODE_DENSE = 77129274;
    public static final String _PIM_MODE_DENSE_ = "PIM_MODE_DENSE";
    public static final int    _PIM_MODE_SPARSE = 1344031631;
    public static final String _PIM_MODE_SPARSE_ = "PIM_MODE_SPARSE";
}
