/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-ospf-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-ospf-types.yang */
public class openconfigOspfTypes extends ConfNamespace {
    public static final int hash = 1467522258;
    public int hash() {
        return openconfigOspfTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ospf-types";
    public String id() {
        return openconfigOspfTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ospf-types";
    public String uri() {
        return openconfigOspfTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigOspfTypes.uri);
    }

    public static final String prefix = "oc-ospf-types";
    public String prefix() {
        return openconfigOspfTypes.prefix;
    }

    public openconfigOspfTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _OSPF_TE_LSA_TLV_TYPE = 1534064168;
    public static final String _OSPF_TE_LSA_TLV_TYPE_ = "OSPF_TE_LSA_TLV_TYPE";
    public static final int    _MAX_METRIC_INCLUDE_STUB = 1813782523;
    public static final String _MAX_METRIC_INCLUDE_STUB_ = "MAX_METRIC_INCLUDE_STUB";
    public static final int    _ADJACENCY_SID = 677329760;
    public static final String _ADJACENCY_SID_ = "ADJACENCY_SID";
    public static final int    _IPV4_SEGMENT = 1676836352;
    public static final String _IPV4_SEGMENT_ = "IPV4_SEGMENT";
    public static final int    _SPF = 1912670565;
    public static final String _SPF_ = "SPF";
    public static final int    _EXCHANGE = 1926429516;
    public static final String _EXCHANGE_ = "EXCHANGE";
    public static final int    _ROUTER_INFORMATION = 1690368878;
    public static final String _ROUTER_INFORMATION_ = "ROUTER_INFORMATION";
    public static final int    _NETWORK_LSA = 1679393331;
    public static final String _NETWORK_LSA_ = "NETWORK_LSA";
    public static final int    _NODE_IPV6_LOCAL_ADDRESS = 226377646;
    public static final String _NODE_IPV6_LOCAL_ADDRESS_ = "NODE_IPV6_LOCAL_ADDRESS";
    public static final int    _STUB_NETWORK_LINK = 1840027165;
    public static final String _STUB_NETWORK_LINK_ = "STUB_NETWORK_LINK";
    public static final int    _TE_NODE_ATTRIBUTE_TLV_TYPE = 1207063361;
    public static final String _TE_NODE_ATTRIBUTE_TLV_TYPE_ = "TE_NODE_ATTRIBUTE_TLV_TYPE";
    public static final int    _NODE_IPV4_LOCAL_ADDRESS = 1279870694;
    public static final String _NODE_IPV4_LOCAL_ADDRESS_ = "NODE_IPV4_LOCAL_ADDRESS";
    public static final int    _MAX_METRIC_INCLUDE = 1946942437;
    public static final String _MAX_METRIC_INCLUDE_ = "MAX_METRIC_INCLUDE";
    public static final int    _BROADCAST_NETWORK = 144806415;
    public static final String _BROADCAST_NETWORK_ = "BROADCAST_NETWORK";
    public static final int    _TE_ROUTER_ADDRESS = 279284552;
    public static final String _TE_ROUTER_ADDRESS_ = "TE_ROUTER_ADDRESS";
    public static final int    _OSPFV2_EXTPREFIX_BINDING_ERO_PATH_SEGMENT_TYPE = 446447811;
    public static final String _OSPFV2_EXTPREFIX_BINDING_ERO_PATH_SEGMENT_TYPE_ = "OSPFV2_EXTPREFIX_BINDING_ERO_PATH_SEGMENT_TYPE";
    public static final int    _DOWN = 1781612810;
    public static final String _DOWN_ = "DOWN";
    public static final int    _SUMMARY_ASBR_LSA = 598191774;
    public static final String _SUMMARY_ASBR_LSA_ = "SUMMARY_ASBR_LSA";
    public static final int    _OSPF_NEIGHBOR_STATE = 679742554;
    public static final String _OSPF_NEIGHBOR_STATE_ = "OSPF_NEIGHBOR_STATE";
    public static final int    _OSPFV2_EXTENDED_LINK = 2083147151;
    public static final String _OSPFV2_EXTENDED_LINK_ = "OSPFV2_EXTENDED_LINK";
    public static final int    _TRANSIT_NETWORK_LINK = 2013261132;
    public static final String _TRANSIT_NETWORK_LINK_ = "TRANSIT_NETWORK_LINK";
    public static final int    _OSPFV2_ROUTER_LINK_TYPE = 1288132354;
    public static final String _OSPFV2_ROUTER_LINK_TYPE_ = "OSPFV2_ROUTER_LINK_TYPE";
    public static final int    _TE_LINK_ADMIN_GROUP = 1798776404;
    public static final String _TE_LINK_ADMIN_GROUP_ = "TE_LINK_ADMIN_GROUP";
    public static final int    _ERO_METRIC = 1784041423;
    public static final String _ERO_METRIC_ = "ERO_METRIC";
    public static final int    _SR_SID_LABEL_TLV = 1550820795;
    public static final String _SR_SID_LABEL_TLV_ = "SR_SID_LABEL_TLV";
    public static final int    _VIRTUAL_LINK = 1685389655;
    public static final String _VIRTUAL_LINK_ = "VIRTUAL_LINK";
    public static final int    _PREFIX_SID = 877873840;
    public static final String _PREFIX_SID_ = "PREFIX_SID";
    public static final int    _ERO_PATH = 170236892;
    public static final String _ERO_PATH_ = "ERO_PATH";
    public static final int    _TE_ROUTER_IPV6_ADDRESS = 1366550499;
    public static final String _TE_ROUTER_IPV6_ADDRESS_ = "TE_ROUTER_IPV6_ADDRESS";
    public static final int    _MAX_METRIC_TRIGGER = 1597985558;
    public static final String _MAX_METRIC_TRIGGER_ = "MAX_METRIC_TRIGGER";
    public static final int    _OSPFV2_EXTENDED_PREFIX_SUBTLV_TYPE = 1808075077;
    public static final String _OSPFV2_EXTENDED_PREFIX_SUBTLV_TYPE_ = "OSPFV2_EXTENDED_PREFIX_SUBTLV_TYPE";
    public static final int    _UNNUMBERED_INTERFACE_SEGMENT = 87659766;
    public static final String _UNNUMBERED_INTERFACE_SEGMENT_ = "UNNUMBERED_INTERFACE_SEGMENT";
    public static final int    _TE_LINK_ID = 1496711164;
    public static final String _TE_LINK_ID_ = "TE_LINK_ID";
    public static final int    _OSPFV2_EXTENDED_PREFIX = 12356977;
    public static final String _OSPFV2_EXTENDED_PREFIX_ = "OSPFV2_EXTENDED_PREFIX";
    public static final int    _MAX_METRIC_INCLUDE_TYPE2_EXTERNAL = 1967434649;
    public static final String _MAX_METRIC_INCLUDE_TYPE2_EXTERNAL_ = "MAX_METRIC_INCLUDE_TYPE2_EXTERNAL";
    public static final int    _OSPFV2_EXTENDED_PREFIX_SID_LABEL_BINDING_SUBTLV_TYPE = 1186662413;
    public static final String _OSPFV2_EXTENDED_PREFIX_SID_LABEL_BINDING_SUBTLV_TYPE_ = "OSPFV2_EXTENDED_PREFIX_SID_LABEL_BINDING_SUBTLV_TYPE";
    public static final int    _ATTEMPT = 218970994;
    public static final String _ATTEMPT_ = "ATTEMPT";
    public static final int    _SR_ALGORITHM = 1139078522;
    public static final String _SR_ALGORITHM_ = "SR_ALGORITHM";
    public static final int    _STRICT_SPF = 1268132646;
    public static final String _STRICT_SPF_ = "STRICT_SPF";
    public static final int    _GRACE_IP_INTERFACE_ADDRESS = 2075738747;
    public static final String _GRACE_IP_INTERFACE_ADDRESS_ = "GRACE_IP_INTERFACE_ADDRESS";
    public static final int    _RI_LSA_TLV_TYPES = 1321808049;
    public static final String _RI_LSA_TLV_TYPES_ = "RI_LSA_TLV_TYPES";
    public static final int    _OSPFV2_AS_SCOPE_OPAQUE_LSA = 1845623727;
    public static final String _OSPFV2_AS_SCOPE_OPAQUE_LSA_ = "OSPFV2_AS_SCOPE_OPAQUE_LSA";
    public static final int    _ROUTER_LSA_VIRTUAL_LINK = 1935492204;
    public static final String _ROUTER_LSA_VIRTUAL_LINK_ = "ROUTER_LSA_VIRTUAL_LINK";
    public static final int    _ROUTER_LSA_TYPES = 1222444308;
    public static final String _ROUTER_LSA_TYPES_ = "ROUTER_LSA_TYPES";
    public static final int    _TE_LINK_MAXIMUM_RESERVABLE_BANDWIDTH = 1773458701;
    public static final String _TE_LINK_MAXIMUM_RESERVABLE_BANDWIDTH_ = "TE_LINK_MAXIMUM_RESERVABLE_BANDWIDTH";
    public static final int    _GRACE_PERIOD = 645612686;
    public static final String _GRACE_PERIOD_ = "GRACE_PERIOD";
    public static final int    _RI_SR_SID_LABEL_RANGE = 431568600;
    public static final String _RI_SR_SID_LABEL_RANGE_ = "RI_SR_SID_LABEL_RANGE";
    public static final int    _OSPFV2_EXTENDED_LINK_SUBTLV_TYPE = 641206296;
    public static final String _OSPFV2_EXTENDED_LINK_SUBTLV_TYPE_ = "OSPFV2_EXTENDED_LINK_SUBTLV_TYPE";
    public static final int    _EXSTART = 1707723236;
    public static final String _EXSTART_ = "EXSTART";
    public static final int    _GRACE_LSA_TLV_TYPES = 1938252157;
    public static final String _GRACE_LSA_TLV_TYPES_ = "GRACE_LSA_TLV_TYPES";
    public static final int    _TE_LINK_REMOTE_IP = 1513783339;
    public static final String _TE_LINK_REMOTE_IP_ = "TE_LINK_REMOTE_IP";
    public static final int    _TE_LINK_METRIC = 1847774344;
    public static final String _TE_LINK_METRIC_ = "TE_LINK_METRIC";
    public static final int    _TE_LINK_MAXIMUM_BANDWIDTH = 1232376138;
    public static final String _TE_LINK_MAXIMUM_BANDWIDTH_ = "TE_LINK_MAXIMUM_BANDWIDTH";
    public static final int    _OSPF_OPAQUE_LSA_TYPE = 1805007284;
    public static final String _OSPF_OPAQUE_LSA_TYPE_ = "OSPF_OPAQUE_LSA_TYPE";
    public static final int    _TWO_WAY = 2104846276;
    public static final String _TWO_WAY_ = "TWO_WAY";
    public static final int    _ROUTER_LSA = 1899462152;
    public static final String _ROUTER_LSA_ = "ROUTER_LSA";
    public static final int    _TE_LINK_TYPE = 314283400;
    public static final String _TE_LINK_TYPE_ = "TE_LINK_TYPE";
    public static final int    _GRACE_RESTART_REASON = 1698637363;
    public static final String _GRACE_RESTART_REASON_ = "GRACE_RESTART_REASON";
    public static final int    _ROUTER_LSA_P2P = 699827790;
    public static final String _ROUTER_LSA_P2P_ = "ROUTER_LSA_P2P";
    public static final int    _POINT_TO_POINT_NETWORK = 1606886067;
    public static final String _POINT_TO_POINT_NETWORK_ = "POINT_TO_POINT_NETWORK";
    public static final int    _TE_LINK_LOCAL = 334672386;
    public static final String _TE_LINK_LOCAL_ = "TE_LINK_LOCAL";
    public static final int    _RI_SR_ALGORITHM = 1354759577;
    public static final String _RI_SR_ALGORITHM_ = "RI_SR_ALGORITHM";
    public static final int    _SID_LABEL_BINDING = 1110270845;
    public static final String _SID_LABEL_BINDING_ = "SID_LABEL_BINDING";
    public static final int    _OSPF_NETWORK_TYPE = 192553546;
    public static final String _OSPF_NETWORK_TYPE_ = "OSPF_NETWORK_TYPE";
    public static final int    _ROUTER_LSA_TRANSIT_NETWORK = 1150747073;
    public static final String _ROUTER_LSA_TRANSIT_NETWORK_ = "ROUTER_LSA_TRANSIT_NETWORK";
    public static final int    _OSPF_RI_SR_SID_LABEL_TLV_TYPES = 1152988850;
    public static final String _OSPF_RI_SR_SID_LABEL_TLV_TYPES_ = "OSPF_RI_SR_SID_LABEL_TLV_TYPES";
    public static final int    _GRACE_LSA = 1286669438;
    public static final String _GRACE_LSA_ = "GRACE_LSA";
    public static final int    _TE_OPTICAL_NODE_PROPERTY = 238312154;
    public static final String _TE_OPTICAL_NODE_PROPERTY_ = "TE_OPTICAL_NODE_PROPERTY";
    public static final int    _RI_INFORMATIONAL_CAPABILITIES = 1724154063;
    public static final String _RI_INFORMATIONAL_CAPABILITIES_ = "RI_INFORMATIONAL_CAPABILITIES";
    public static final int    _NSSA_AS_EXTERNAL_LSA = 2036828346;
    public static final String _NSSA_AS_EXTERNAL_LSA_ = "NSSA_AS_EXTERNAL_LSA";
    public static final int    _ROUTER_LSA_STUB_NETWORK = 221872753;
    public static final String _ROUTER_LSA_STUB_NETWORK_ = "ROUTER_LSA_STUB_NETWORK";
    public static final int    _RI_NODE_ADMIN_TAG = 911635619;
    public static final String _RI_NODE_ADMIN_TAG_ = "RI_NODE_ADMIN_TAG";
    public static final int    _FULL = 2045790236;
    public static final String _FULL_ = "FULL";
    public static final int    _SUMMARY_IP_NETWORK_LSA = 1023689708;
    public static final String _SUMMARY_IP_NETWORK_LSA_ = "SUMMARY_IP_NETWORK_LSA";
    public static final int    _EXTENDED_PREFIX_RANGE = 2086316016;
    public static final String _EXTENDED_PREFIX_RANGE_ = "EXTENDED_PREFIX_RANGE";
    public static final int    _MAX_METRIC_ON_SYSTEM_BOOT = 990059651;
    public static final String _MAX_METRIC_ON_SYSTEM_BOOT_ = "MAX_METRIC_ON_SYSTEM_BOOT";
    public static final int    _OSPFV2_LINK_SCOPE_OPAQUE_LSA = 1721099091;
    public static final String _OSPFV2_LINK_SCOPE_OPAQUE_LSA_ = "OSPFV2_LINK_SCOPE_OPAQUE_LSA";
    public static final int    _INIT = 908279663;
    public static final String _INIT_ = "INIT";
    public static final int    _TRAFFIC_ENGINEERING = 1515235791;
    public static final String _TRAFFIC_ENGINEERING_ = "TRAFFIC_ENGINEERING";
    public static final int    _OSPF_LSA_TYPE = 1781221298;
    public static final String _OSPF_LSA_TYPE_ = "OSPF_LSA_TYPE";
    public static final int    _RI_FUNCTIONAL_CAPABILITIES = 788878320;
    public static final String _RI_FUNCTIONAL_CAPABILITIES_ = "RI_FUNCTIONAL_CAPABILITIES";
    public static final int    _OSPFV2_AREA_SCOPE_OPAQUE_LSA = 482799320;
    public static final String _OSPFV2_AREA_SCOPE_OPAQUE_LSA_ = "OSPFV2_AREA_SCOPE_OPAQUE_LSA";
    public static final int    _TE_LINK_LOCAL_IP = 1635198103;
    public static final String _TE_LINK_LOCAL_IP_ = "TE_LINK_LOCAL_IP";
    public static final int    _TE_LINK = 130867209;
    public static final String _TE_LINK_ = "TE_LINK";
    public static final int    _LOADING = 1517861758;
    public static final String _LOADING_ = "LOADING";
    public static final int    _SID_MPLS_LABEL_BINDING = 1449723339;
    public static final String _SID_MPLS_LABEL_BINDING_ = "SID_MPLS_LABEL_BINDING";
    public static final int    _TE_NODE_ATTRIBUTE = 1574586051;
    public static final String _TE_NODE_ATTRIBUTE_ = "TE_NODE_ATTRIBUTE";
    public static final int    _OSPF_TE_LINK_TLV_TYPE = 1666936088;
    public static final String _OSPF_TE_LINK_TLV_TYPE_ = "OSPF_TE_LINK_TLV_TYPE";
    public static final int    _AS_EXTERNAL_LSA = 14399360;
    public static final String _AS_EXTERNAL_LSA_ = "AS_EXTERNAL_LSA";
    public static final int    _TE_LINK_UNRESERVED_BANDWIDTH = 1133281801;
    public static final String _TE_LINK_UNRESERVED_BANDWIDTH_ = "TE_LINK_UNRESERVED_BANDWIDTH";
    public static final int    _NON_BROADCAST_NETWORK = 1029656382;
    public static final String _NON_BROADCAST_NETWORK_ = "NON_BROADCAST_NETWORK";
    public static final int    _POINT_TO_POINT_LINK = 961563833;
    public static final String _POINT_TO_POINT_LINK_ = "POINT_TO_POINT_LINK";
}
