/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-system-grpc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-system-grpc.yang */
public class openconfigSystemGrpc extends ConfNamespace {
    public static final int hash = 1113344019;
    public int hash() {
        return openconfigSystemGrpc.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/system-grpc";
    public String id() {
        return openconfigSystemGrpc.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/system-grpc";
    public String uri() {
        return openconfigSystemGrpc.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigSystemGrpc.uri);
    }

    public static final String prefix = "oc-sys-grpc";
    public String prefix() {
        return openconfigSystemGrpc.prefix;
    }

    public openconfigSystemGrpc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _services = 284312249;
    public static final String _services_ = "services";
    public static final int    _grpc_servers = 1544242818;
    public static final String _grpc_servers_ = "grpc-servers";
    public static final int    _port = 10387472;
    public static final String _port_ = "port";
    public static final int    _network_instance = 1958697851;
    public static final String _network_instance_ = "network-instance";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _GNMI = 362231934;
    public static final String _GNMI_ = "GNMI";
    public static final int    _listen_addresses = 1210788452;
    public static final String _listen_addresses_ = "listen-addresses";
    public static final int    _enable = 448570367;
    public static final String _enable_ = "enable";
    public static final int    _certificate_id = 371782284;
    public static final String _certificate_id_ = "certificate-id";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _metadata_authentication = 955559787;
    public static final String _metadata_authentication_ = "metadata-authentication";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _GRPC_SERVICE = 1877873298;
    public static final String _GRPC_SERVICE_ = "GRPC_SERVICE";
    public static final int    _grpc_server = 1905627648;
    public static final String _grpc_server_ = "grpc-server";
    public static final int    _transport_security = 944148043;
    public static final String _transport_security_ = "transport-security";
}
