/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-ap-interfaces.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-ap-interfaces.yang */
public class openconfigApInterfaces extends ConfNamespace {
    public static final int hash = 191479472;
    public int hash() {
        return openconfigApInterfaces.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ap-interfaces";
    public String id() {
        return openconfigApInterfaces.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ap-interfaces";
    public String uri() {
        return openconfigApInterfaces.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigApInterfaces.uri);
    }

    public static final String prefix = "oc-ap-if";
    public String prefix() {
        return openconfigApInterfaces.prefix;
    }

    public openconfigApInterfaces() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _supplicant_timeout = 1485013791;
    public static final String _supplicant_timeout_ = "supplicant-timeout";
    public static final int    _out_mac_control_frames = 1033076598;
    public static final String _out_mac_control_frames_ = "out-mac-control-frames";
    public static final int    _trunk_vlans = 1077818890;
    public static final String _trunk_vlans_ = "trunk-vlans";
    public static final int    _neighbor = 81789621;
    public static final String _neighbor_ = "neighbor";
    public static final int    _src = 1474138878;
    public static final String _src_ = "src";
    public static final int    _subinterfaces = 1730428758;
    public static final String _subinterfaces_ = "subinterfaces";
    public static final int    _out_pkts = 335453834;
    public static final String _out_pkts_ = "out-pkts";
    public static final int    _proxy_arp = 676928388;
    public static final String _proxy_arp_ = "proxy-arp";
    public static final int    _in_multicast_pkts = 1126031588;
    public static final String _in_multicast_pkts_ = "in-multicast-pkts";
    public static final int    _ipv4 = 268057062;
    public static final String _ipv4_ = "ipv4";
    public static final int    _carrier_transitions = 1056552358;
    public static final String _carrier_transitions_ = "carrier-transitions";
    public static final int    _out_octets = 2123582464;
    public static final String _out_octets_ = "out-octets";
    public static final int    _in_error_pkts = 1525691105;
    public static final String _in_error_pkts_ = "in-error-pkts";
    public static final int    _suppress = 1746378947;
    public static final String _suppress_ = "suppress";
    public static final int    _out_forwarded_pkts = 1671788686;
    public static final String _out_forwarded_pkts_ = "out-forwarded-pkts";
    public static final int    _cpu = 1825182739;
    public static final String _cpu_ = "cpu";
    public static final int    _mode = 575893728;
    public static final String _mode_ = "mode";
    public static final int    _out_broadcast_pkts = 1427076806;
    public static final String _out_broadcast_pkts_ = "out-broadcast-pkts";
    public static final int    _out_8021q_frames = 1916377746;
    public static final String _out_8021q_frames_ = "out-8021q-frames";
    public static final int    _duplex_mode = 1404309190;
    public static final String _duplex_mode_ = "duplex-mode";
    public static final int    _in_maxsize_exceeded = 1592620661;
    public static final String _in_maxsize_exceeded_ = "in-maxsize-exceeded";
    public static final int    _port_speed = 1659992901;
    public static final String _port_speed_ = "port-speed";
    public static final int    _out_error_pkts = 1259985273;
    public static final String _out_error_pkts_ = "out-error-pkts";
    public static final int    _fec_mode = 1758513387;
    public static final String _fec_mode_ = "fec-mode";
    public static final int    _in_symbol_error = 330345552;
    public static final String _in_symbol_error_ = "in-symbol-error";
    public static final int    _ethernet = 766975154;
    public static final String _ethernet_ = "ethernet";
    public static final int    _dot1x_vlan_map = 101779416;
    public static final String _dot1x_vlan_map_ = "dot1x-vlan-map";
    public static final int    _hw_mac_address = 761716137;
    public static final String _hw_mac_address_ = "hw-mac-address";
    public static final int    _ifindex = 1259815303;
    public static final String _ifindex_ = "ifindex";
    public static final int    _interfaces = 321503962;
    public static final String _interfaces_ = "interfaces";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _switched_vlan = 1368499734;
    public static final String _switched_vlan_ = "switched-vlan";
    public static final int    _enable_flow_control = 204818831;
    public static final String _enable_flow_control_ = "enable-flow-control";
    public static final int    _interface_mode = 1229050048;
    public static final String _interface_mode_ = "interface-mode";
    public static final int    _auth_fail_vlan = 1975668347;
    public static final String _auth_fail_vlan_ = "auth-fail-vlan";
    public static final int    _subinterface = 1294223328;
    public static final String _subinterface_ = "subinterface";
    public static final int    _in_jabber_frames = 408306399;
    public static final String _in_jabber_frames_ = "in-jabber-frames";
    public static final int    _in_pkts = 1264605324;
    public static final String _in_pkts_ = "in-pkts";
    public static final int    _interval = 559952988;
    public static final String _interval_ = "interval";
    public static final int    _in_block_errors = 574971365;
    public static final String _in_block_errors_ = "in-block-errors";
    public static final int    _loopback_mode = 2918605;
    public static final String _loopback_mode_ = "loopback-mode";
    public static final int    _retransmit_interval = 1593920370;
    public static final String _retransmit_interval_ = "retransmit-interval";
    public static final int    _in_8021q_frames = 1930482994;
    public static final String _in_8021q_frames_ = "in-8021q-frames";
    public static final int    _logical = 2102296514;
    public static final String _logical_ = "logical";
    public static final int    _out_mac_errors_tx = 1741887964;
    public static final String _out_mac_errors_tx_ = "out-mac-errors-tx";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _addresses = 1825332052;
    public static final String _addresses_ = "addresses";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _in_single_collision = 644608466;
    public static final String _in_single_collision_ = "in-single-collision";
    public static final int    _mac_address = 2110689796;
    public static final String _mac_address_ = "mac-address";
    public static final int    _neighbors = 1478644450;
    public static final String _neighbors_ = "neighbors";
    public static final int    _native_vlan = 1159886695;
    public static final String _native_vlan_ = "native-vlan";
    public static final int    _neighbor_state = 393193907;
    public static final String _neighbor_state_ = "neighbor-state";
    public static final int    _mac = 474706838;
    public static final String _mac_ = "mac";
    public static final int    _dup_addr_detect_transmits = 53367116;
    public static final String _dup_addr_detect_transmits_ = "dup-addr-detect-transmits";
    public static final int    _lag_type = 1214577214;
    public static final String _lag_type_ = "lag-type";
    public static final int    _in_unicast_pkts = 1100444555;
    public static final String _in_unicast_pkts_ = "in-unicast-pkts";
    public static final int    _authenticated_session = 779789955;
    public static final String _authenticated_session_ = "authenticated-session";
    public static final int    _max_requests = 1169769215;
    public static final String _max_requests_ = "max-requests";
    public static final int    _dst = 1772754210;
    public static final String _dst_ = "dst";
    public static final int    _in_carrier_errors = 1819454577;
    public static final String _in_carrier_errors_ = "in-carrier-errors";
    public static final int    _poe = 575544877;
    public static final String _poe_ = "poe";
    public static final int    _in_interrupted_tx = 1788111094;
    public static final String _in_interrupted_tx_ = "in-interrupted-tx";
    public static final int    _in_crc_errors = 621329595;
    public static final String _in_crc_errors_ = "in-crc-errors";
    public static final int    _tunnel = 1120006729;
    public static final String _tunnel_ = "tunnel";
    public static final int    _power_used = 513298623;
    public static final String _power_used_ = "power-used";
    public static final int    _session_id = 372565948;
    public static final String _session_id_ = "session-id";
    public static final int    _in_oversize_frames = 1638462268;
    public static final String _in_oversize_frames_ = "in-oversize-frames";
    public static final int    _reauthenticate_interval = 846126068;
    public static final String _reauthenticate_interval_ = "reauthenticate-interval";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _in_mac_control_frames = 1842676927;
    public static final String _in_mac_control_frames_ = "in-mac-control-frames";
    public static final int    _authenticated_sessions = 405082666;
    public static final String _authenticated_sessions_ = "authenticated-sessions";
    public static final int    _in_late_collision = 1149684835;
    public static final String _in_late_collision_ = "in-late-collision";
    public static final int    _out_mac_pause_frames = 1294592065;
    public static final String _out_mac_pause_frames_ = "out-mac-pause-frames";
    public static final int    _admin_status = 2104862928;
    public static final String _admin_status_ = "admin-status";
    public static final int    _ttl = 774234709;
    public static final String _ttl_ = "ttl";
    public static final int    _power_class = 697483843;
    public static final String _power_class_ = "power-class";
    public static final int    _in_discards = 1607867097;
    public static final String _in_discards_ = "in-discards";
    public static final int    _in_errors = 419802148;
    public static final String _in_errors_ = "in-errors";
    public static final int    _dot1x = 331072404;
    public static final String _dot1x_ = "dot1x";
    public static final int    _ipv6 = 1228132394;
    public static final String _ipv6_ = "ipv6";
    public static final int    _in_unknown_protos = 1961345832;
    public static final String _in_unknown_protos_ = "in-unknown-protos";
    public static final int    _origin = 2002579816;
    public static final String _origin_ = "origin";
    public static final int    _management = 1308506682;
    public static final String _management_ = "management";
    public static final int    _mtu = 1751455506;
    public static final String _mtu_ = "mtu";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _in_fcs_errors = 422454373;
    public static final String _in_fcs_errors_ = "in-fcs-errors";
    public static final int    _in_mac_errors_rx = 1863161887;
    public static final String _in_mac_errors_rx_ = "in-mac-errors-rx";
    public static final int    _negotiated_duplex_mode = 1452772647;
    public static final String _negotiated_duplex_mode_ = "negotiated-duplex-mode";
    public static final int    _host_mode = 1074934560;
    public static final String _host_mode_ = "host-mode";
    public static final int    _index = 827593980;
    public static final String _index_ = "index";
    public static final int    _standalone_link_training = 963533190;
    public static final String _standalone_link_training_ = "standalone-link-training";
    public static final int    _in_mac_pause_frames = 1003418322;
    public static final String _in_mac_pause_frames_ = "in-mac-pause-frames";
    public static final int    _counters = 1327053922;
    public static final String _counters_ = "counters";
    public static final int    _out_discarded_pkts = 2063997953;
    public static final String _out_discarded_pkts_ = "out-discarded-pkts";
    public static final int    _out_errors = 1825475719;
    public static final String _out_errors_ = "out-errors";
    public static final int    _in_octets = 1354763654;
    public static final String _in_octets_ = "in-octets";
    public static final int    _lifetime = 92991035;
    public static final String _lifetime_ = "lifetime";
    public static final int    _vlan_name = 706279704;
    public static final String _vlan_name_ = "vlan-name";
    public static final int    _in_broadcast_pkts = 1140019954;
    public static final String _in_broadcast_pkts_ = "in-broadcast-pkts";
    public static final int    _lag_speed = 899368516;
    public static final String _lag_speed_ = "lag-speed";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _dhcp_client = 1259775382;
    public static final String _dhcp_client_ = "dhcp-client";
    public static final int    _is_router = 1891156201;
    public static final String _is_router_ = "is-router";
    public static final int    _out_multicast_pkts = 723352241;
    public static final String _out_multicast_pkts_ = "out-multicast-pkts";
    public static final int    _in_discarded_pkts = 1037387075;
    public static final String _in_discarded_pkts_ = "in-discarded-pkts";
    public static final int    _out_forwarded_octets = 1487514732;
    public static final String _out_forwarded_octets_ = "out-forwarded-octets";
    public static final int    _in_undersize_frames = 1512667264;
    public static final String _in_undersize_frames_ = "in-undersize-frames";
    public static final int    _router_advertisement = 996372025;
    public static final String _router_advertisement_ = "router-advertisement";
    public static final int    _last_change = 2008341778;
    public static final String _last_change_ = "last-change";
    public static final int    _access_vlan = 2014822852;
    public static final String _access_vlan_ = "access-vlan";
    public static final int    _oper_status = 1906453952;
    public static final String _oper_status_ = "oper-status";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _in_fragment_frames = 564635238;
    public static final String _in_fragment_frames_ = "in-fragment-frames";
    public static final int    _negotiated_port_speed = 1543346698;
    public static final String _negotiated_port_speed_ = "negotiated-port-speed";
    public static final int    _ip = 1643785435;
    public static final String _ip_ = "ip";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _auto_negotiate = 2102272149;
    public static final String _auto_negotiate_ = "auto-negotiate";
    public static final int    _server_fail_vlan = 620338056;
    public static final String _server_fail_vlan_ = "server-fail-vlan";
    public static final int    _in_forwarded_octets = 425114535;
    public static final String _in_forwarded_octets_ = "in-forwarded-octets";
    public static final int    _out_unicast_pkts = 170730703;
    public static final String _out_unicast_pkts_ = "out-unicast-pkts";
    public static final int    _aggregation = 640445680;
    public static final String _aggregation_ = "aggregation";
    public static final int    _member = 387693123;
    public static final String _member_ = "member";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _description = 202559156;
    public static final String _description_ = "description";
    public static final int    _link_layer_address = 2084100809;
    public static final String _link_layer_address_ = "link-layer-address";
    public static final int    _in_forwarded_pkts = 1440015958;
    public static final String _in_forwarded_pkts_ = "in-forwarded-pkts";
    public static final int    _gre_key = 835370429;
    public static final String _gre_key_ = "gre-key";
    public static final int    _authenticate_port = 1279881523;
    public static final String _authenticate_port_ = "authenticate-port";
    public static final int    _last_clear = 1168907511;
    public static final String _last_clear_ = "last-clear";
    public static final int    _out_discards = 2051284211;
    public static final String _out_discards_ = "out-discards";
    public static final int    _min_links = 1996282515;
    public static final String _min_links_ = "min-links";
    public static final int    _prefix_length = 524393771;
    public static final String _prefix_length_ = "prefix-length";
}
