/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-messages.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-messages.yang */
public class openconfigMessages extends ConfNamespace {
    public static final int hash = 86236328;
    public int hash() {
        return openconfigMessages.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/messages";
    public String id() {
        return openconfigMessages.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/messages";
    public String uri() {
        return openconfigMessages.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigMessages.uri);
    }

    public static final String prefix = "oc-messages";
    public String prefix() {
        return openconfigMessages.prefix;
    }

    public openconfigMessages() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _debug_entries = 1494426096;
    public static final String _debug_entries_ = "debug-entries";
    public static final int    _msg = 381476903;
    public static final String _msg_ = "msg";
    public static final int    _msgid = 1175192235;
    public static final String _msgid_ = "msgid";
    public static final int    _enabled = 197426095;
    public static final String _enabled_ = "enabled";
    public static final int    _messages = 1588018753;
    public static final String _messages_ = "messages";
    public static final int    _app_name = 1425497104;
    public static final String _app_name_ = "app-name";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _priority = 1346277862;
    public static final String _priority_ = "priority";
    public static final int    _procid = 757462765;
    public static final String _procid_ = "procid";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _service = 855380710;
    public static final String _service_ = "service";
    public static final int    _message = 1674281495;
    public static final String _message_ = "message";
    public static final int    _DEBUG_SERVICE = 1110658352;
    public static final String _DEBUG_SERVICE_ = "DEBUG_SERVICE";
    public static final int    _debug_service = 250426212;
    public static final String _debug_service_ = "debug-service";
    public static final int    _severity = 483607279;
    public static final String _severity_ = "severity";
}
