/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-aaa-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-aaa-types.yang */
public class openconfigAaaTypes extends ConfNamespace {
    public static final int hash = 1530331377;
    public int hash() {
        return openconfigAaaTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/aaa/types";
    public String id() {
        return openconfigAaaTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/aaa/types";
    public String uri() {
        return openconfigAaaTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigAaaTypes.uri);
    }

    public static final String prefix = "oc-aaa-types";
    public String prefix() {
        return openconfigAaaTypes.prefix;
    }

    public openconfigAaaTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _LOCAL = 460621875;
    public static final String _LOCAL_ = "LOCAL";
    public static final int    _AAA_METHOD_TYPE = 559682576;
    public static final String _AAA_METHOD_TYPE_ = "AAA_METHOD_TYPE";
    public static final int    _AAA_SERVER_TYPE = 613022448;
    public static final String _AAA_SERVER_TYPE_ = "AAA_SERVER_TYPE";
    public static final int    _SYSTEM_DEFINED_ROLES = 521067205;
    public static final String _SYSTEM_DEFINED_ROLES_ = "SYSTEM_DEFINED_ROLES";
    public static final int    _AAA_ACCOUNTING_EVENT_TYPE = 124546406;
    public static final String _AAA_ACCOUNTING_EVENT_TYPE_ = "AAA_ACCOUNTING_EVENT_TYPE";
    public static final int    _TACACS_ALL = 115280843;
    public static final String _TACACS_ALL_ = "TACACS_ALL";
    public static final int    _AAA_AUTHORIZATION_EVENT_CONFIG = 1006046516;
    public static final String _AAA_AUTHORIZATION_EVENT_CONFIG_ = "AAA_AUTHORIZATION_EVENT_CONFIG";
    public static final int    _AAA_AUTHORIZATION_EVENT_TYPE = 2145214605;
    public static final String _AAA_AUTHORIZATION_EVENT_TYPE_ = "AAA_AUTHORIZATION_EVENT_TYPE";
    public static final int    _AAA_ACCOUNTING_EVENT_LOGIN = 1034593224;
    public static final String _AAA_ACCOUNTING_EVENT_LOGIN_ = "AAA_ACCOUNTING_EVENT_LOGIN";
    public static final int    _AAA_ACCOUNTING_EVENT_COMMAND = 1033975239;
    public static final String _AAA_ACCOUNTING_EVENT_COMMAND_ = "AAA_ACCOUNTING_EVENT_COMMAND";
    public static final int    _AAA_AUTHORIZATION_EVENT_COMMAND = 748669924;
    public static final String _AAA_AUTHORIZATION_EVENT_COMMAND_ = "AAA_AUTHORIZATION_EVENT_COMMAND";
    public static final int    _SYSTEM_ROLE_ADMIN = 34094209;
    public static final String _SYSTEM_ROLE_ADMIN_ = "SYSTEM_ROLE_ADMIN";
    public static final int    _RADIUS_ALL = 1387723537;
    public static final String _RADIUS_ALL_ = "RADIUS_ALL";
}
