/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-evpn-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-evpn-types.yang */
public class openconfigEvpnTypes extends ConfNamespace {
    public static final int hash = 969140351;
    public int hash() {
        return openconfigEvpnTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/evpn-types";
    public String id() {
        return openconfigEvpnTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/evpn-types";
    public String uri() {
        return openconfigEvpnTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigEvpnTypes.uri);
    }

    public static final String prefix = "oc-evpn-types";
    public String prefix() {
        return openconfigEvpnTypes.prefix;
    }

    public openconfigEvpnTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _EVI = 1958456747;
    public static final String _EVI_ = "EVI";
    public static final int    _SINGLE_ACTIVE = 134677756;
    public static final String _SINGLE_ACTIVE_ = "SINGLE_ACTIVE";
    public static final int    _NVE = 1299005861;
    public static final String _NVE_ = "NVE";
    public static final int    _ALL_ACTIVE = 1273543671;
    public static final String _ALL_ACTIVE_ = "ALL_ACTIVE";
    public static final int    _EVPN_REDUNDANCY_MODE = 1952232930;
    public static final String _EVPN_REDUNDANCY_MODE_ = "EVPN_REDUNDANCY_MODE";
    public static final int    _MAC_VRF = 1318653587;
    public static final String _MAC_VRF_ = "MAC_VRF";
    public static final int    _EVPN_CAPABILITY = 1841362908;
    public static final String _EVPN_CAPABILITY_ = "EVPN_CAPABILITY";
    public static final int    _VLAN_AWARE = 1224275169;
    public static final String _VLAN_AWARE_ = "VLAN_AWARE";
    public static final int    _VLAN_BUNDLE = 1372939797;
    public static final String _VLAN_BUNDLE_ = "VLAN_BUNDLE";
    public static final int    _VLAN_BASED = 771125677;
    public static final String _VLAN_BASED_ = "VLAN_BASED";
    public static final int    _IRB = 1293421017;
    public static final String _IRB_ = "IRB";
    public static final int    _EVPN_TYPE = 2134458162;
    public static final String _EVPN_TYPE_ = "EVPN_TYPE";
    public static final int    _IP_VRF = 873762200;
    public static final String _IP_VRF_ = "IP_VRF";
}
