/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-routing-policy.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-routing-policy.yang */
public class openconfigRoutingPolicy extends ConfNamespace {
    public static final int hash = 1214832453;
    public int hash() {
        return openconfigRoutingPolicy.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/routing-policy";
    public String id() {
        return openconfigRoutingPolicy.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/routing-policy";
    public String uri() {
        return openconfigRoutingPolicy.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigRoutingPolicy.uri);
    }

    public static final String prefix = "oc-rpol";
    public String prefix() {
        return openconfigRoutingPolicy.prefix;
    }

    public openconfigRoutingPolicy() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _neighbor_set = 1237696180;
    public static final String _neighbor_set_ = "neighbor-set";
    public static final int    _tag_value = 633774587;
    public static final String _tag_value_ = "tag-value";
    public static final int    _mode = 575893728;
    public static final String _mode_ = "mode";
    public static final int    _routing_policy = 1803236680;
    public static final String _routing_policy_ = "routing-policy";
    public static final int    _prefix = 1408440115;
    public static final String _prefix_ = "prefix";
    public static final int    _tag = 21925559;
    public static final String _tag_ = "tag";
    public static final int    _ip_prefix = 289539202;
    public static final String _ip_prefix_ = "ip-prefix";
    public static final int    _subinterface = 1294223328;
    public static final String _subinterface_ = "subinterface";
    public static final int    _neighbor_sets = 477381007;
    public static final String _neighbor_sets_ = "neighbor-sets";
    public static final int    _set_tag = 177790014;
    public static final String _set_tag_ = "set-tag";
    public static final int    _conditions = 975488036;
    public static final String _conditions_ = "conditions";
    public static final int    _tag_set = 196489743;
    public static final String _tag_set_ = "tag-set";
    public static final int    _state = 630973766;
    public static final String _state_ = "state";
    public static final int    _statement = 2020184598;
    public static final String _statement_ = "statement";
    public static final int    _match_interface = 1869116648;
    public static final String _match_interface_ = "match-interface";
    public static final int    _match_set_options = 517327943;
    public static final String _match_set_options_ = "match-set-options";
    public static final int    _prefix_set = 1234120084;
    public static final String _prefix_set_ = "prefix-set";
    public static final int    _match_neighbor_set = 2124471048;
    public static final String _match_neighbor_set_ = "match-neighbor-set";
    public static final int    _match_prefix_set = 499359715;
    public static final String _match_prefix_set_ = "match-prefix-set";
    public static final int    _prefixes = 1405994391;
    public static final String _prefixes_ = "prefixes";
    public static final int    _policy_definition = 927599493;
    public static final String _policy_definition_ = "policy-definition";
    public static final int    _prefix_sets = 2035865838;
    public static final String _prefix_sets_ = "prefix-sets";
    public static final int    _match_tag_set = 2016437036;
    public static final String _match_tag_set_ = "match-tag-set";
    public static final int    _reference = 1577200258;
    public static final String _reference_ = "reference";
    public static final int    _config = 2105663071;
    public static final String _config_ = "config";
    public static final int    _inline = 1987224790;
    public static final String _inline_ = "inline";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _masklength_range = 497977763;
    public static final String _masklength_range_ = "masklength-range";
    public static final int    _statements = 1505610507;
    public static final String _statements_ = "statements";
    public static final int    _defined_sets = 952897476;
    public static final String _defined_sets_ = "defined-sets";
    public static final int    _policy_result = 1672578308;
    public static final String _policy_result_ = "policy-result";
    public static final int    _install_protocol_eq = 1943059095;
    public static final String _install_protocol_eq_ = "install-protocol-eq";
    public static final int    _interface = 221572658;
    public static final String _interface_ = "interface";
    public static final int    _address = 1266954393;
    public static final String _address_ = "address";
    public static final int    _actions = 2034878685;
    public static final String _actions_ = "actions";
    public static final int    _policy_definitions = 492676988;
    public static final String _policy_definitions_ = "policy-definitions";
    public static final int    _call_policy = 1718898824;
    public static final String _call_policy_ = "call-policy";
    public static final int    _tag_sets = 381894197;
    public static final String _tag_sets_ = "tag-sets";
}
