/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-bgp-types.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-bgp-types.yang */
public class openconfigBgpTypes extends ConfNamespace {
    public static final int hash = 1526894959;
    public int hash() {
        return openconfigBgpTypes.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/bgp-types";
    public String id() {
        return openconfigBgpTypes.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/bgp-types";
    public String uri() {
        return openconfigBgpTypes.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigBgpTypes.uri);
    }

    public static final String prefix = "oc-bgp-types";
    public String prefix() {
        return openconfigBgpTypes.prefix;
    }

    public openconfigBgpTypes() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _ADMINISTRATIVE_RESET = 1677317102;
    public static final String _ADMINISTRATIVE_RESET_ = "ADMINISTRATIVE_RESET";
    public static final int    _L2VPN_EVPN = 1637199637;
    public static final String _L2VPN_EVPN_ = "L2VPN_EVPN";
    public static final int    _CEASE = 1551408101;
    public static final String _CEASE_ = "CEASE";
    public static final int    _BAD_MESSAGE_LENGTH = 494135864;
    public static final String _BAD_MESSAGE_LENGTH_ = "BAD_MESSAGE_LENGTH";
    public static final int    _AFI_SAFI_TYPE = 1755201881;
    public static final String _AFI_SAFI_TYPE_ = "AFI_SAFI_TYPE";
    public static final int    _L3VPN_IPV4_MULTICAST = 186926127;
    public static final String _L3VPN_IPV4_MULTICAST_ = "L3VPN_IPV4_MULTICAST";
    public static final int    _INVALID_NEXT_HOP_ATTRIBUTE = 2065427773;
    public static final String _INVALID_NEXT_HOP_ATTRIBUTE_ = "INVALID_NEXT_HOP_ATTRIBUTE";
    public static final int    _UNSUPPORTED_VERSION_NUMBER = 840225116;
    public static final String _UNSUPPORTED_VERSION_NUMBER_ = "UNSUPPORTED_VERSION_NUMBER";
    public static final int    _MESSAGE_HEADER_ERROR = 1981502493;
    public static final String _MESSAGE_HEADER_ERROR_ = "MESSAGE_HEADER_ERROR";
    public static final int    _RECEIVE_UNEXPECTED_MESSAGE_OPENSENT = 194768019;
    public static final String _RECEIVE_UNEXPECTED_MESSAGE_OPENSENT_ = "RECEIVE_UNEXPECTED_MESSAGE_OPENSENT";
    public static final int    _IPV6_LABELED_UNICAST = 250019660;
    public static final String _IPV6_LABELED_UNICAST_ = "IPV6_LABELED_UNICAST";
    public static final int    _L2VPN_VPLS = 1188880318;
    public static final String _L2VPN_VPLS_ = "L2VPN_VPLS";
    public static final int    _LINKSTATE_VPN = 2061540244;
    public static final String _LINKSTATE_VPN_ = "LINKSTATE_VPN";
    public static final int    _NO_EXPORT = 1826136237;
    public static final String _NO_EXPORT_ = "NO_EXPORT";
    public static final int    _CONN_COLLISION_RESOLUTION = 479286023;
    public static final String _CONN_COLLISION_RESOLUTION_ = "CONN_COLLISION_RESOLUTION";
    public static final int    _ATTRIBUTE_FLAGS_ERROR = 849083408;
    public static final String _ATTRIBUTE_FLAGS_ERROR_ = "ATTRIBUTE_FLAGS_ERROR";
    public static final int    _L3VPN_IPV6_MULTICAST = 2103677679;
    public static final String _L3VPN_IPV6_MULTICAST_ = "L3VPN_IPV6_MULTICAST";
    public static final int    _L3VPN_IPV4_UNICAST = 1741386212;
    public static final String _L3VPN_IPV4_UNICAST_ = "L3VPN_IPV4_UNICAST";
    public static final int    _OPEN_MESSAGE_ERROR = 2130327400;
    public static final String _OPEN_MESSAGE_ERROR_ = "OPEN_MESSAGE_ERROR";
    public static final int    _MALFORMED_ATTRIBUTE_LIST = 587088262;
    public static final String _MALFORMED_ATTRIBUTE_LIST_ = "MALFORMED_ATTRIBUTE_LIST";
    public static final int    _RECEIVE_UNEXPECTED_MESSAGE_OPENCONFIRM = 1697526623;
    public static final String _RECEIVE_UNEXPECTED_MESSAGE_OPENCONFIRM_ = "RECEIVE_UNEXPECTED_MESSAGE_OPENCONFIRM";
    public static final int    _NOPEER = 221504254;
    public static final String _NOPEER_ = "NOPEER";
    public static final int    _L3VPN_IPV6_UNICAST = 1164674340;
    public static final String _L3VPN_IPV6_UNICAST_ = "L3VPN_IPV6_UNICAST";
    public static final int    _ADMINISTRATIVE_SHUTDOWN = 2068924448;
    public static final String _ADMINISTRATIVE_SHUTDOWN_ = "ADMINISTRATIVE_SHUTDOWN";
    public static final int    _UNSPECIFIC = 1666077215;
    public static final String _UNSPECIFIC_ = "UNSPECIFIC";
    public static final int    _PRIVATE_AS_REPLACE_ALL = 543865220;
    public static final String _PRIVATE_AS_REPLACE_ALL_ = "PRIVATE_AS_REPLACE_ALL";
    public static final int    _UNSUPPORTED_OPTIONAL_PARAMETER = 896547743;
    public static final String _UNSUPPORTED_OPTIONAL_PARAMETER_ = "UNSUPPORTED_OPTIONAL_PARAMETER";
    public static final int    _NO_EXPORT_SUBCONFED = 810499829;
    public static final String _NO_EXPORT_SUBCONFED_ = "NO_EXPORT_SUBCONFED";
    public static final int    _OPTIONAL_ATTRIBUTE_ERROR = 6333664;
    public static final String _OPTIONAL_ATTRIBUTE_ERROR_ = "OPTIONAL_ATTRIBUTE_ERROR";
    public static final int    _IPV4_FLOWSPEC = 2146449593;
    public static final String _IPV4_FLOWSPEC_ = "IPV4_FLOWSPEC";
    public static final int    _MALFORMED_AS_PATH = 461684128;
    public static final String _MALFORMED_AS_PATH_ = "MALFORMED_AS_PATH";
    public static final int    _LINKSTATE_SPF = 2049017264;
    public static final String _LINKSTATE_SPF_ = "LINKSTATE_SPF";
    public static final int    _BGP_ERROR_CODE = 1113338665;
    public static final String _BGP_ERROR_CODE_ = "BGP_ERROR_CODE";
    public static final int    _PEER_DE_CONFIGURED = 2101437413;
    public static final String _PEER_DE_CONFIGURED_ = "PEER_DE_CONFIGURED";
    public static final int    _MISSING_WELL_KNOWN_ATTRIBUTE = 128096075;
    public static final String _MISSING_WELL_KNOWN_ATTRIBUTE_ = "MISSING_WELL_KNOWN_ATTRIBUTE";
    public static final int    _HOLD_TIMER_EXPIRED = 1649113257;
    public static final String _HOLD_TIMER_EXPIRED_ = "HOLD_TIMER_EXPIRED";
    public static final int    _ADD_PATHS = 609910272;
    public static final String _ADD_PATHS_ = "ADD_PATHS";
    public static final int    _UNRECOGNIZED_WELL_KNOWN_ATTRIBUTE = 2144153951;
    public static final String _UNRECOGNIZED_WELL_KNOWN_ATTRIBUTE_ = "UNRECOGNIZED_WELL_KNOWN_ATTRIBUTE";
    public static final int    _IPV4_UNICAST = 751206307;
    public static final String _IPV4_UNICAST_ = "IPV4_UNICAST";
    public static final int    _BAD_PEER_AS = 1703155327;
    public static final String _BAD_PEER_AS_ = "BAD_PEER_AS";
    public static final int    _MAX_NUM_PREFIXES_REACHED = 273443020;
    public static final String _MAX_NUM_PREFIXES_REACHED_ = "MAX_NUM_PREFIXES_REACHED";
    public static final int    _SRTE_POLICY_IPV6 = 495698417;
    public static final String _SRTE_POLICY_IPV6_ = "SRTE_POLICY_IPV6";
    public static final int    _FINITE_STATE_MACHINE_ERROR = 491103025;
    public static final String _FINITE_STATE_MACHINE_ERROR_ = "FINITE_STATE_MACHINE_ERROR";
    public static final int    _REMOVE_PRIVATE_AS_OPTION = 1673720754;
    public static final String _REMOVE_PRIVATE_AS_OPTION_ = "REMOVE_PRIVATE_AS_OPTION";
    public static final int    _UPDATE_MESSAGE_SUBCODE = 1423441070;
    public static final String _UPDATE_MESSAGE_SUBCODE_ = "UPDATE_MESSAGE_SUBCODE";
    public static final int    _BGP_ERROR_SUBCODE = 1612135093;
    public static final String _BGP_ERROR_SUBCODE_ = "BGP_ERROR_SUBCODE";
    public static final int    _UNACCEPTABLE_HOLD_TIME = 431768231;
    public static final String _UNACCEPTABLE_HOLD_TIME_ = "UNACCEPTABLE_HOLD_TIME";
    public static final int    _LINKSTATE = 1061983961;
    public static final String _LINKSTATE_ = "LINKSTATE";
    public static final int    _NO_ADVERTISE = 904946328;
    public static final String _NO_ADVERTISE_ = "NO_ADVERTISE";
    public static final int    _INVALID_ORIGIN_ATTRIBUTE = 1738984153;
    public static final String _INVALID_ORIGIN_ATTRIBUTE_ = "INVALID_ORIGIN_ATTRIBUTE";
    public static final int    _VPNV4_FLOWSPEC = 1760800898;
    public static final String _VPNV4_FLOWSPEC_ = "VPNV4_FLOWSPEC";
    public static final int    _OTHER_CONFIG_CHANGE = 1913248039;
    public static final String _OTHER_CONFIG_CHANGE_ = "OTHER_CONFIG_CHANGE";
    public static final int    _ASN32 = 217320232;
    public static final String _ASN32_ = "ASN32";
    public static final int    _ATTRIBUTE_LENGTH_ERROR = 1599283138;
    public static final String _ATTRIBUTE_LENGTH_ERROR_ = "ATTRIBUTE_LENGTH_ERROR";
    public static final int    _FINITE_STATE_MACHINE_SUBCODE = 34499209;
    public static final String _FINITE_STATE_MACHINE_SUBCODE_ = "FINITE_STATE_MACHINE_SUBCODE";
    public static final int    _BAD_MESSAGE_TYPE = 1835503461;
    public static final String _BAD_MESSAGE_TYPE_ = "BAD_MESSAGE_TYPE";
    public static final int    _IPV4_LABELED_UNICAST = 993232452;
    public static final String _IPV4_LABELED_UNICAST_ = "IPV4_LABELED_UNICAST";
    public static final int    _ROUTE_REFRESH_MESSAGE_ERROR = 1731375829;
    public static final String _ROUTE_REFRESH_MESSAGE_ERROR_ = "ROUTE_REFRESH_MESSAGE_ERROR";
    public static final int    _UPDATE_MESSAGE_ERROR = 1525396369;
    public static final String _UPDATE_MESSAGE_ERROR_ = "UPDATE_MESSAGE_ERROR";
    public static final int    _OPEN_MESSAGE_SUBCODE = 1294371799;
    public static final String _OPEN_MESSAGE_SUBCODE_ = "OPEN_MESSAGE_SUBCODE";
    public static final int    _ROUTE_REFRESH = 1933423903;
    public static final String _ROUTE_REFRESH_ = "ROUTE_REFRESH";
    public static final int    _MESSAGE_HEADER_SUBCODE = 198155303;
    public static final String _MESSAGE_HEADER_SUBCODE_ = "MESSAGE_HEADER_SUBCODE";
    public static final int    _BGP_CAPABILITY = 725351094;
    public static final String _BGP_CAPABILITY_ = "BGP_CAPABILITY";
    public static final int    _GRACEFUL_RESTART = 759126455;
    public static final String _GRACEFUL_RESTART_ = "GRACEFUL_RESTART";
    public static final int    _CONNECTION_REJECTED = 1649625068;
    public static final String _CONNECTION_REJECTED_ = "CONNECTION_REJECTED";
    public static final int    _UNSUPPORTED_CAPABILITY = 603778452;
    public static final String _UNSUPPORTED_CAPABILITY_ = "UNSUPPORTED_CAPABILITY";
    public static final int    _CONNECTION_NOT_SYNCHRONIZED = 61486092;
    public static final String _CONNECTION_NOT_SYNCHRONIZED_ = "CONNECTION_NOT_SYNCHRONIZED";
    public static final int    _PRIVATE_AS_REMOVE_ALL = 1993688401;
    public static final String _PRIVATE_AS_REMOVE_ALL_ = "PRIVATE_AS_REMOVE_ALL";
    public static final int    _INVALID_NETWORK_FIELD = 659303899;
    public static final String _INVALID_NETWORK_FIELD_ = "INVALID_NETWORK_FIELD";
    public static final int    _BAD_BGP_IDENTIFIER = 1518530477;
    public static final String _BAD_BGP_IDENTIFIER_ = "BAD_BGP_IDENTIFIER";
    public static final int    _SRTE_POLICY_IPV4 = 1167882248;
    public static final String _SRTE_POLICY_IPV4_ = "SRTE_POLICY_IPV4";
    public static final int    _OUT_OF_RESOURCES = 1441904958;
    public static final String _OUT_OF_RESOURCES_ = "OUT_OF_RESOURCES";
    public static final int    _IPV6_UNICAST = 1440955788;
    public static final String _IPV6_UNICAST_ = "IPV6_UNICAST";
    public static final int    _INVALID_MESSAGE_LENGTH = 683139548;
    public static final String _INVALID_MESSAGE_LENGTH_ = "INVALID_MESSAGE_LENGTH";
    public static final int    _CEASE_SUBCODE = 765135701;
    public static final String _CEASE_SUBCODE_ = "CEASE_SUBCODE";
    public static final int    _EXTENDED_NEXTHOP_ENCODING = 1475204892;
    public static final String _EXTENDED_NEXTHOP_ENCODING_ = "EXTENDED_NEXTHOP_ENCODING";
    public static final int    _MPBGP = 1700298006;
    public static final String _MPBGP_ = "MPBGP";
    public static final int    _BGP_WELL_KNOWN_STD_COMMUNITY = 1857443241;
    public static final String _BGP_WELL_KNOWN_STD_COMMUNITY_ = "BGP_WELL_KNOWN_STD_COMMUNITY";
    public static final int    _ROUTE_REFRESH_SUBCODE = 191706362;
    public static final String _ROUTE_REFRESH_SUBCODE_ = "ROUTE_REFRESH_SUBCODE";
    public static final int    _RECEIVE_UNEXPECTED_MESSAGE_ESTABLISHED = 1421919527;
    public static final String _RECEIVE_UNEXPECTED_MESSAGE_ESTABLISHED_ = "RECEIVE_UNEXPECTED_MESSAGE_ESTABLISHED";
}
