/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/openconfig-platform-fabric.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.ocall.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module openconfig-platform-fabric.yang */
public class openconfigPlatformFabric extends ConfNamespace {
    public static final int hash = 1363575684;
    public int hash() {
        return openconfigPlatformFabric.hash;
    }

    public static final String id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/fabric";
    public String id() {
        return openconfigPlatformFabric.id;
    }

    public static final String uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/fabric";
    public String uri() {
        return openconfigPlatformFabric.uri;
    }

    public String xmlUri() {
        return ConfNamespace.truncateToXMLUri(openconfigPlatformFabric.uri);
    }

    public static final String prefix = "oc-fabric";
    public String prefix() {
        return openconfigPlatformFabric.prefix;
    }

    public openconfigPlatformFabric() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _power_admin_state = 444634152;
    public static final String _power_admin_state_ = "power-admin-state";
}
