#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-pf-srte.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-pf-srte.yang


class ns(object):
    hash = 731440622

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/policy-forwarding/sr-te"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/policy-forwarding/sr-te"

    prefix = "oc-pf-srte"

    oc_pf_srte_value = 864367181
    oc_pf_srte_value_ = "value"
    oc_pf_srte_state = 630973766
    oc_pf_srte_state_ = "state"
    oc_pf_srte_mpls_ttl = 1680459618
    oc_pf_srte_mpls_ttl_ = "mpls-ttl"
    oc_pf_srte_sid = 1233827376
    oc_pf_srte_sid_ = "sid"
    oc_pf_srte_srte = 888744401
    oc_pf_srte_srte_ = "srte"
    oc_pf_srte_sids = 1159055095
    oc_pf_srte_sids_ = "sids"
    oc_pf_srte_srte_color = 101044883
    oc_pf_srte_srte_color_ = "srte-color"
    oc_pf_srte_weight = 306158986
    oc_pf_srte_weight_ = "weight"
    oc_pf_srte_config = 2105663071
    oc_pf_srte_config_ = "config"
    oc_pf_srte_mpls_bsid = 1128629901
    oc_pf_srte_mpls_bsid_ = "mpls-bsid"
    oc_pf_srte_segment_list = 1508390484
    oc_pf_srte_segment_list_ = "segment-list"
    oc_pf_srte_index = 827593980
    oc_pf_srte_index_ = "index"
    oc_pf_srte_srte_endpoint = 1810842189
    oc_pf_srte_srte_endpoint_ = "srte-endpoint"
    oc_pf_srte_mpls_tc = 1374870376
    oc_pf_srte_mpls_tc_ = "mpls-tc"
    oc_pf_srte_srte_preference = 1861944655
    oc_pf_srte_srte_preference_ = "srte-preference"
    oc_pf_srte_segment_lists = 1956410405
    oc_pf_srte_segment_lists_ = "segment-lists"
