#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-platform-ext.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-platform-ext.yang


class ns(object):
    hash = 683075803

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/extension"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/extension"

    prefix = "oc-platform-ext"

    oc_platform_ext_entity_id = 506960278
    oc_platform_ext_entity_id_ = "entity-id"
