#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-platform-psu.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-platform-psu.yang


class ns(object):
    hash = 474980313

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/psu"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/psu"

    prefix = "oc-platform-psu"

    oc_platform_psu_output_voltage = 1366260725
    oc_platform_psu_output_voltage_ = "output-voltage"
    oc_platform_psu_input_current = 820465870
    oc_platform_psu_input_current_ = "input-current"
    oc_platform_psu_enabled = 197426095
    oc_platform_psu_enabled_ = "enabled"
    oc_platform_psu_output_current = 1258195278
    oc_platform_psu_output_current_ = "output-current"
    oc_platform_psu_capacity = 191070892
    oc_platform_psu_capacity_ = "capacity"
    oc_platform_psu_output_power = 571387945
    oc_platform_psu_output_power_ = "output-power"
    oc_platform_psu_input_voltage = 1875433346
    oc_platform_psu_input_voltage_ = "input-voltage"
