#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-rib-bgp.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-rib-bgp.yang


class ns(object):
    hash = 88752953

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rib/bgp"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rib/bgp"

    prefix = "oc-rib-bgp"

    oc_rib_bgp_IPV4_NODE_ADDRESS = 3
    oc_rib_bgp_IPV4_NODE_ADDRESS_ = "IPV4_NODE_ADDRESS"
    oc_rib_bgp_IPV6_LOCAL_REMOTE_ADDR = 8
    oc_rib_bgp_IPV6_LOCAL_REMOTE_ADDR_ = "IPV6_LOCAL_REMOTE_ADDR"
    oc_rib_bgp_IPV6_SID = 2
    oc_rib_bgp_IPV6_SID_ = "IPV6_SID"
    oc_rib_bgp_IPV6_NODE_ADDRESS = 4
    oc_rib_bgp_IPV6_NODE_ADDRESS_ = "IPV6_NODE_ADDRESS"
    oc_rib_bgp_MPLS_SID = 1
    oc_rib_bgp_MPLS_SID_ = "MPLS_SID"
    oc_rib_bgp_IPV4_LOCAL_REMOTE_ADDR = 6
    oc_rib_bgp_IPV4_LOCAL_REMOTE_ADDR_ = "IPV4_LOCAL_REMOTE_ADDR"
    oc_rib_bgp_IPV4_LOCAL_INTF_ID = 5
    oc_rib_bgp_IPV4_LOCAL_INTF_ID_ = "IPV4_LOCAL_INTF_ID"
    oc_rib_bgp_IPV6_LOCAL_INTF_ID = 7
    oc_rib_bgp_IPV6_LOCAL_INTF_ID_ = "IPV6_LOCAL_INTF_ID"
