#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-lacp.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-lacp.yang


class ns(object):
    hash = 1846623156

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/lacp"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/lacp"

    prefix = "oc-lacp"

    oc_lacp_lacp = 941807021
    oc_lacp_lacp_ = "lacp"
    oc_lacp_aggregatable = 1913014057
    oc_lacp_aggregatable_ = "aggregatable"
    oc_lacp_members = 654632324
    oc_lacp_members_ = "members"
    oc_lacp_system_priority = 772579520
    oc_lacp_system_priority_ = "system-priority"
    oc_lacp_lacp_rx_errors = 277889002
    oc_lacp_lacp_rx_errors_ = "lacp-rx-errors"
    oc_lacp_PASSIVE = 1
    oc_lacp_PASSIVE_ = "PASSIVE"
    oc_lacp_activity = 342061973
    oc_lacp_activity_ = "activity"
    oc_lacp_lacp_tx_errors = 116095096
    oc_lacp_lacp_tx_errors_ = "lacp-tx-errors"
    oc_lacp_interfaces = 321503962
    oc_lacp_interfaces_ = "interfaces"
    oc_lacp_OUT_SYNC = 1
    oc_lacp_OUT_SYNC_ = "OUT_SYNC"
    oc_lacp_interval = 559952988
    oc_lacp_interval_ = "interval"
    oc_lacp_partner_port_num = 1559475307
    oc_lacp_partner_port_num_ = "partner-port-num"
    oc_lacp_partner_key = 992929862
    oc_lacp_partner_key_ = "partner-key"
    oc_lacp_timeout = 614210192
    oc_lacp_timeout_ = "timeout"
    oc_lacp_state = 630973766
    oc_lacp_state_ = "state"
    oc_lacp_oper_key = 2073473131
    oc_lacp_oper_key_ = "oper-key"
    oc_lacp_partner_id = 2017302908
    oc_lacp_partner_id_ = "partner-id"
    oc_lacp_port_num = 325135876
    oc_lacp_port_num_ = "port-num"
    oc_lacp_lacp_timeout_transitions = 1382699651
    oc_lacp_lacp_timeout_transitions_ = "lacp-timeout-transitions"
    oc_lacp_FAST = 0
    oc_lacp_FAST_ = "FAST"
    oc_lacp_SHORT = 1
    oc_lacp_SHORT_ = "SHORT"
    oc_lacp_system_id_mac = 96224468
    oc_lacp_system_id_mac_ = "system-id-mac"
    oc_lacp_lacp_mode = 1718839254
    oc_lacp_lacp_mode_ = "lacp-mode"
    oc_lacp_ACTIVE = 0
    oc_lacp_ACTIVE_ = "ACTIVE"
    oc_lacp_IN_SYNC = 0
    oc_lacp_IN_SYNC_ = "IN_SYNC"
    oc_lacp_synchronization = 1454002976
    oc_lacp_synchronization_ = "synchronization"
    oc_lacp_config = 2105663071
    oc_lacp_config_ = "config"
    oc_lacp_LONG = 0
    oc_lacp_LONG_ = "LONG"
    oc_lacp_distributing = 1376147756
    oc_lacp_distributing_ = "distributing"
    oc_lacp_counters = 1327053922
    oc_lacp_counters_ = "counters"
    oc_lacp_lacp_errors = 446074538
    oc_lacp_lacp_errors_ = "lacp-errors"
    oc_lacp_lacp_in_pkts = 427708400
    oc_lacp_lacp_in_pkts_ = "lacp-in-pkts"
    oc_lacp_name = 1998270519
    oc_lacp_name_ = "name"
    oc_lacp_lacp_unknown_errors = 173733544
    oc_lacp_lacp_unknown_errors_ = "lacp-unknown-errors"
    oc_lacp_system_id = 1116890259
    oc_lacp_system_id_ = "system-id"
    oc_lacp_last_change = 2008341778
    oc_lacp_last_change_ = "last-change"
    oc_lacp_interface = 221572658
    oc_lacp_interface_ = "interface"
    oc_lacp_SLOW = 1
    oc_lacp_SLOW_ = "SLOW"
    oc_lacp_lacp_out_pkts = 697551856
    oc_lacp_lacp_out_pkts_ = "lacp-out-pkts"
    oc_lacp_member = 387693123
    oc_lacp_member_ = "member"
    oc_lacp_collecting = 1614936924
    oc_lacp_collecting_ = "collecting"
