#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-igmp.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-igmp.yang


class ns(object):
    hash = 1845427305

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/igmp"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/igmp"

    prefix = "oc-igmp"

