#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-inet-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-inet-types.yang


class ns(object):
    hash = 491695886

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/types/inet"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/types/inet"

    prefix = "oc-inet"

    oc_inet_IPV4 = 4
    oc_inet_IPV4_ = "IPV4"
    oc_inet_IPV6 = 6
    oc_inet_IPV6_ = "IPV6"
    oc_inet_UNKNOWN = 0
    oc_inet_UNKNOWN_ = "UNKNOWN"
