#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-macsec-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-macsec-types.yang


class ns(object):
    hash = 1856349470

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/macsec/types"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/macsec/types"

    prefix = "oc-macsect"

    oc_macsect_50_BYTES = 2
    oc_macsect_50_BYTES_ = "50_BYTES"
    oc_macsect_GCM_AES_256 = 1
    oc_macsect_GCM_AES_256_ = "GCM_AES_256"
    oc_macsect_30_BYTES = 1
    oc_macsect_30_BYTES_ = "30_BYTES"
    oc_macsect_GCM_AES_XPN_256 = 3
    oc_macsect_GCM_AES_XPN_256_ = "GCM_AES_XPN_256"
    oc_macsect_GCM_AES_XPN_128 = 2
    oc_macsect_GCM_AES_XPN_128_ = "GCM_AES_XPN_128"
    oc_macsect_0_BYTES = 0
    oc_macsect_0_BYTES_ = "0_BYTES"
    oc_macsect_GCM_AES_128 = 0
    oc_macsect_GCM_AES_128_ = "GCM_AES_128"
