#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-mpls.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-mpls.yang


class ns(object):
    hash = 845238616

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/mpls"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/mpls"

    prefix = "oc-mpls"

    oc_mpls_UNNUMBERED_INTERFACE = 5
    oc_mpls_UNNUMBERED_INTERFACE_ = "UNNUMBERED_INTERFACE"
    oc_mpls_NON_EXISTENT = 0
    oc_mpls_NON_EXISTENT_ = "NON_EXISTENT"
    oc_mpls_SEPARATE_UP_DOWN = 1
    oc_mpls_SEPARATE_UP_DOWN_ = "SEPARATE_UP_DOWN"
    oc_mpls_DOWN = 1
    oc_mpls_DOWN_ = "DOWN"
    oc_mpls_INITIALIZED = 1
    oc_mpls_INITIALIZED_ = "INITIALIZED"
    oc_mpls_STRICT = 1
    oc_mpls_STRICT_ = "STRICT"
    oc_mpls_IPV4 = 0
    oc_mpls_IPV4_ = "IPV4"
    oc_mpls_FLOODED_SRLG = 0
    oc_mpls_FLOODED_SRLG_ = "FLOODED_SRLG"
    oc_mpls_LOOSE = 0
    oc_mpls_LOOSE_ = "LOOSE"
    oc_mpls_ADJ_SID_ONLY = 0
    oc_mpls_ADJ_SID_ONLY_ = "ADJ_SID_ONLY"
    oc_mpls_LEAST_FILL = 1
    oc_mpls_LEAST_FILL_ = "LEAST_FILL"
    oc_mpls_IPV6 = 1
    oc_mpls_IPV6_ = "IPV6"
    oc_mpls_OPENREC = 2
    oc_mpls_OPENREC_ = "OPENREC"
    oc_mpls_MIRRORED_UP_DOWN = 0
    oc_mpls_MIRRORED_UP_DOWN_ = "MIRRORED_UP_DOWN"
    oc_mpls_SPECIFIED = 0
    oc_mpls_SPECIFIED_ = "SPECIFIED"
    oc_mpls_MIXED_MODE = 1
    oc_mpls_MIXED_MODE_ = "MIXED_MODE"
    oc_mpls_UP = 0
    oc_mpls_UP_ = "UP"
    oc_mpls_IGP = 0
    oc_mpls_IGP_ = "IGP"
    oc_mpls_AUTO = 1
    oc_mpls_AUTO_ = "AUTO"
    oc_mpls_OPENSENT = 3
    oc_mpls_OPENSENT_ = "OPENSENT"
    oc_mpls_THRESHOLD_CROSSED = 1
    oc_mpls_THRESHOLD_CROSSED_ = "THRESHOLD_CROSSED"
    oc_mpls_STATIC_SRLG = 1
    oc_mpls_STATIC_SRLG_ = "STATIC_SRLG"
    oc_mpls_ASN4 = 3
    oc_mpls_ASN4_ = "ASN4"
    oc_mpls_RANDOM = 0
    oc_mpls_RANDOM_ = "RANDOM"
    oc_mpls_MOST_FILL = 2
    oc_mpls_MOST_FILL_ = "MOST_FILL"
    oc_mpls_DELTA = 0
    oc_mpls_DELTA_ = "DELTA"
    oc_mpls_OPERATIONAL = 4
    oc_mpls_OPERATIONAL_ = "OPERATIONAL"
    oc_mpls_ASN = 2
    oc_mpls_ASN_ = "ASN"
    oc_mpls_LABEL = 4
    oc_mpls_LABEL_ = "LABEL"
