#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-rsvp-sr-ext.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-rsvp-sr-ext.yang


class ns(object):
    hash = 628766684

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rsvp-sr-ext"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/rsvp-sr-ext"

    prefix = "oc-sr-rsvp-ext"

    oc_sr_rsvp_ext_bandwidth_multiplier = 1219499947
    oc_sr_rsvp_ext_bandwidth_multiplier_ = "bandwidth-multiplier"
    oc_sr_rsvp_ext_MEASURE_AND_FLOOD = 1
    oc_sr_rsvp_ext_MEASURE_AND_FLOOD_ = "MEASURE_AND_FLOOD"
    oc_sr_rsvp_ext_bandwidth_measurement = 634253161
    oc_sr_rsvp_ext_bandwidth_measurement_ = "bandwidth-measurement"
    oc_sr_rsvp_ext_state = 630973766
    oc_sr_rsvp_ext_state_ = "state"
    oc_sr_rsvp_ext_last_calculated_sr_utilisation = 426411958
    oc_sr_rsvp_ext_last_calculated_sr_utilisation_ = "last-calculated-sr-utilisation"
    oc_sr_rsvp_ext_MEASURE_ONLY = 0
    oc_sr_rsvp_ext_MEASURE_ONLY_ = "MEASURE_ONLY"
    oc_sr_rsvp_ext_adjustment_interval = 13482291
    oc_sr_rsvp_ext_adjustment_interval_ = "adjustment-interval"
    oc_sr_rsvp_ext_adjusted_absolute_subscription_bw = 947916735
    oc_sr_rsvp_ext_adjusted_absolute_subscription_bw_ = "adjusted-absolute-subscription-bw"
    oc_sr_rsvp_ext_SR_TRAFFIC_PCT = 1
    oc_sr_rsvp_ext_SR_TRAFFIC_PCT_ = "SR_TRAFFIC_PCT"
    oc_sr_rsvp_ext_config = 2105663071
    oc_sr_rsvp_ext_config_ = "config"
    oc_sr_rsvp_ext_ADJUSTED_MAX_RESERVABLE_PCT = 0
    oc_sr_rsvp_ext_ADJUSTED_MAX_RESERVABLE_PCT_ = "ADJUSTED_MAX_RESERVABLE_PCT"
    oc_sr_rsvp_ext_collection_interval = 880323978
    oc_sr_rsvp_ext_collection_interval_ = "collection-interval"
    oc_sr_rsvp_ext_last_calculated_time = 211199008
    oc_sr_rsvp_ext_last_calculated_time_ = "last-calculated-time"
    oc_sr_rsvp_ext_last_sample_measured_rsvp_util = 475520912
    oc_sr_rsvp_ext_last_sample_measured_rsvp_util_ = "last-sample-measured-rsvp-util"
    oc_sr_rsvp_ext_last_sample_measured_sr_util = 1879456218
    oc_sr_rsvp_ext_last_sample_measured_sr_util_ = "last-sample-measured-sr-util"
    oc_sr_rsvp_ext_effective_adjustment_interval = 622159440
    oc_sr_rsvp_ext_effective_adjustment_interval_ = "effective-adjustment-interval"
    oc_sr_rsvp_ext_adjusted_max_reservable_bw_pct = 1500910758
    oc_sr_rsvp_ext_adjusted_max_reservable_bw_pct_ = "adjusted-max-reservable-bw-pct"
    oc_sr_rsvp_ext_measure_sr_traffic = 381453395
    oc_sr_rsvp_ext_measure_sr_traffic_ = "measure-sr-traffic"
    oc_sr_rsvp_ext_last_flooded_time = 336790771
    oc_sr_rsvp_ext_last_flooded_time_ = "last-flooded-time"
    oc_sr_rsvp_ext_last_sample_time = 1978518778
    oc_sr_rsvp_ext_last_sample_time_ = "last-sample-time"
    oc_sr_rsvp_ext_update_trigger = 400709998
    oc_sr_rsvp_ext_update_trigger_ = "update-trigger"
    oc_sr_rsvp_ext_sr_traffic_pct = 1794406695
    oc_sr_rsvp_ext_sr_traffic_pct_ = "sr-traffic-pct"
