#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-qos-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-qos-types.yang


class ns(object):
    hash = 958674271

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/qos-types"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/qos-types"

    prefix = "oc-qos-types"

    oc_qos_types_DROP_TAIL = 1005353367
    oc_qos_types_DROP_TAIL_ = "DROP_TAIL"
    oc_qos_types_SHAPE = 0
    oc_qos_types_SHAPE_ = "SHAPE"
    oc_qos_types_WRED = 544615582
    oc_qos_types_WRED_ = "WRED"
    oc_qos_types_POLICE = 1
    oc_qos_types_POLICE_ = "POLICE"
    oc_qos_types_QOS_SCHEDULER_TYPE = 1894500945
    oc_qos_types_QOS_SCHEDULER_TYPE_ = "QOS_SCHEDULER_TYPE"
    oc_qos_types_TWO_RATE_THREE_COLOR = 933954196
    oc_qos_types_TWO_RATE_THREE_COLOR_ = "TWO_RATE_THREE_COLOR"
    oc_qos_types_QOS_QUEUE_TYPE = 1422478134
    oc_qos_types_QOS_QUEUE_TYPE_ = "QOS_QUEUE_TYPE"
    oc_qos_types_RED = 1866424521
    oc_qos_types_RED_ = "RED"
    oc_qos_types_ONE_RATE_TWO_COLOR = 348192294
    oc_qos_types_ONE_RATE_TWO_COLOR_ = "ONE_RATE_TWO_COLOR"
