#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-aft.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-aft.yang


class ns(object):
    hash = 1107473983

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/aft"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/aft"

    prefix = "oc-aft"

