#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-transport-line-connectivity.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-transport-line-connectivity.yang


class ns(object):
    hash = 2063687039

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-transport-line-connectivity"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/openconfig-transport-line-connectivity"

    prefix = "oc-line-connect"

    oc_line_connect_connection = 1134114300
    oc_line_connect_connection_ = "connection"
    oc_line_connect_dest = 1478643067
    oc_line_connect_dest_ = "dest"
    oc_line_connect_source = 1141829056
    oc_line_connect_source_ = "source"
    oc_line_connect_state = 630973766
    oc_line_connect_state_ = "state"
    oc_line_connect_PORT_CONNECTION_TYPE = 1007059418
    oc_line_connect_PORT_CONNECTION_TYPE_ = "PORT_CONNECTION_TYPE"
    oc_line_connect_fiber_type = 1613900476
    oc_line_connect_fiber_type_ = "fiber-type"
    oc_line_connect_config = 2105663071
    oc_line_connect_config_ = "config"
    oc_line_connect_index = 827593980
    oc_line_connect_index_ = "index"
    oc_line_connect_EXTERNAL = 1708429095
    oc_line_connect_EXTERNAL_ = "EXTERNAL"
    oc_line_connect_connections = 1259277820
    oc_line_connect_connections_ = "connections"
