#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-bgp-policy.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-bgp-policy.yang


class ns(object):
    hash = 378707418

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/bgp-policy"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/bgp-policy"

    prefix = "oc-bgp-pol"

    oc_bgp_pol_origin_eq = 1419691803
    oc_bgp_pol_origin_eq_ = "origin-eq"
    oc_bgp_pol_afi_safi_in = 1137862139
    oc_bgp_pol_afi_safi_in_ = "afi-safi-in"
    oc_bgp_pol_bgp_defined_sets = 950785907
    oc_bgp_pol_bgp_defined_sets_ = "bgp-defined-sets"
    oc_bgp_pol_community_set_name = 1009704853
    oc_bgp_pol_community_set_name_ = "community-set-name"
    oc_bgp_pol_ADD = 0
    oc_bgp_pol_ADD_ = "ADD"
    oc_bgp_pol_ext_community_set = 1898620195
    oc_bgp_pol_ext_community_set_ = "ext-community-set"
    oc_bgp_pol_INTERNAL = 0
    oc_bgp_pol_INTERNAL_ = "INTERNAL"
    oc_bgp_pol_match_as_path_set = 1640949474
    oc_bgp_pol_match_as_path_set_ = "match-as-path-set"
    oc_bgp_pol_REFERENCE = 1
    oc_bgp_pol_REFERENCE_ = "REFERENCE"
    oc_bgp_pol_community_sets = 322680218
    oc_bgp_pol_community_sets_ = "community-sets"
    oc_bgp_pol_local_pref_eq = 231562658
    oc_bgp_pol_local_pref_eq_ = "local-pref-eq"
    oc_bgp_pol_community_set_ref = 1808334167
    oc_bgp_pol_community_set_ref_ = "community-set-ref"
    oc_bgp_pol_bgp_actions = 1352269610
    oc_bgp_pol_bgp_actions_ = "bgp-actions"
    oc_bgp_pol_bgp_conditions = 72140219
    oc_bgp_pol_bgp_conditions_ = "bgp-conditions"
    oc_bgp_pol_value = 864367181
    oc_bgp_pol_value_ = "value"
    oc_bgp_pol_state = 630973766
    oc_bgp_pol_state_ = "state"
    oc_bgp_pol_community_set = 1484206391
    oc_bgp_pol_community_set_ = "community-set"
    oc_bgp_pol_as_path_set_name = 1085699960
    oc_bgp_pol_as_path_set_name_ = "as-path-set-name"
    oc_bgp_pol_set_med = 1771976606
    oc_bgp_pol_set_med_ = "set-med"
    oc_bgp_pol_match_set_options = 517327943
    oc_bgp_pol_match_set_options_ = "match-set-options"
    oc_bgp_pol_set_as_path_prepend = 139590977
    oc_bgp_pol_set_as_path_prepend_ = "set-as-path-prepend"
    oc_bgp_pol_ext_community_set_ref = 2135503522
    oc_bgp_pol_ext_community_set_ref_ = "ext-community-set-ref"
    oc_bgp_pol_set_ext_community = 550082755
    oc_bgp_pol_set_ext_community_ = "set-ext-community"
    oc_bgp_pol_REMOVE = 1
    oc_bgp_pol_REMOVE_ = "REMOVE"
    oc_bgp_pol_INLINE = 0
    oc_bgp_pol_INLINE_ = "INLINE"
    oc_bgp_pol_operator = 1597165302
    oc_bgp_pol_operator_ = "operator"
    oc_bgp_pol_REPLACE = 2
    oc_bgp_pol_REPLACE_ = "REPLACE"
    oc_bgp_pol_reference = 1577200258
    oc_bgp_pol_reference_ = "reference"
    oc_bgp_pol_config = 2105663071
    oc_bgp_pol_config_ = "config"
    oc_bgp_pol_community_count = 1042945495
    oc_bgp_pol_community_count_ = "community-count"
    oc_bgp_pol_asn = 888483392
    oc_bgp_pol_asn_ = "asn"
    oc_bgp_pol_SELF = 0
    oc_bgp_pol_SELF_ = "SELF"
    oc_bgp_pol_EXTERNAL = 1
    oc_bgp_pol_EXTERNAL_ = "EXTERNAL"
    oc_bgp_pol_set_community = 238159714
    oc_bgp_pol_set_community_ = "set-community"
    oc_bgp_pol_IGP = 0
    oc_bgp_pol_IGP_ = "IGP"
    oc_bgp_pol_ext_community_set_name = 622786908
    oc_bgp_pol_ext_community_set_name_ = "ext-community-set-name"
    oc_bgp_pol_as_path_sets = 336859460
    oc_bgp_pol_as_path_sets_ = "as-path-sets"
    oc_bgp_pol_inline = 1987224790
    oc_bgp_pol_inline_ = "inline"
    oc_bgp_pol_as_path_set_member = 1230437632
    oc_bgp_pol_as_path_set_member_ = "as-path-set-member"
    oc_bgp_pol_set_next_hop = 824501075
    oc_bgp_pol_set_next_hop_ = "set-next-hop"
    oc_bgp_pol_as_path_length = 340925940
    oc_bgp_pol_as_path_length_ = "as-path-length"
    oc_bgp_pol_ext_community_member = 1993370683
    oc_bgp_pol_ext_community_member_ = "ext-community-member"
    oc_bgp_pol_options = 268171404
    oc_bgp_pol_options_ = "options"
    oc_bgp_pol_as_path_set = 1375156679
    oc_bgp_pol_as_path_set_ = "as-path-set"
    oc_bgp_pol_next_hop_in = 728610331
    oc_bgp_pol_next_hop_in_ = "next-hop-in"
    oc_bgp_pol_med_eq = 47808834
    oc_bgp_pol_med_eq_ = "med-eq"
    oc_bgp_pol_set_local_pref = 2048438639
    oc_bgp_pol_set_local_pref_ = "set-local-pref"
    oc_bgp_pol_community_member = 1851273270
    oc_bgp_pol_community_member_ = "community-member"
    oc_bgp_pol_set_route_origin = 1338231261
    oc_bgp_pol_set_route_origin_ = "set-route-origin"
    oc_bgp_pol_route_type = 695663619
    oc_bgp_pol_route_type_ = "route-type"
    oc_bgp_pol_communities = 858373404
    oc_bgp_pol_communities_ = "communities"
    oc_bgp_pol_repeat_n = 864415541
    oc_bgp_pol_repeat_n_ = "repeat-n"
    oc_bgp_pol_method = 781988118
    oc_bgp_pol_method_ = "method"
    oc_bgp_pol_ext_community_sets = 1642161109
    oc_bgp_pol_ext_community_sets_ = "ext-community-sets"
