#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-macsec.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-macsec.yang


class ns(object):
    hash = 536728785

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/macsec"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/macsec"

    prefix = "oc-macsec"

    oc_macsec_sa_invalid = 1367441760
    oc_macsec_sa_invalid_ = "sa-invalid"
    oc_macsec_out_sak_mkpdu = 2048313186
    oc_macsec_out_sak_mkpdu_ = "out-sak-mkpdu"
    oc_macsec_in_sak_mkpdu = 1484924014
    oc_macsec_in_sak_mkpdu_ = "in-sak-mkpdu"
    oc_macsec_out_mkpdu_errors = 101749763
    oc_macsec_out_mkpdu_errors_ = "out-mkpdu-errors"
    oc_macsec_out_cak_mkpdu = 1078484789
    oc_macsec_out_cak_mkpdu_ = "out-cak-mkpdu"
    oc_macsec_mka_policy = 1297797302
    oc_macsec_mka_policy_ = "mka-policy"
    oc_macsec_policy = 1919655803
    oc_macsec_policy_ = "policy"
    oc_macsec_sa_auth_only = 1920882109
    oc_macsec_sa_auth_only_ = "sa-auth-only"
    oc_macsec_sak_generation_errors = 1916320277
    oc_macsec_sak_generation_errors_ = "sak-generation-errors"
    oc_macsec_interfaces = 321503962
    oc_macsec_interfaces_ = "interfaces"
    oc_macsec_sak_rekey_on_live_peer_loss = 562608463
    oc_macsec_sak_rekey_on_live_peer_loss_ = "sak-rekey-on-live-peer-loss"
    oc_macsec_sci_rx = 2013407749
    oc_macsec_sci_rx_ = "sci-rx"
    oc_macsec_key_server_priority = 1595468216
    oc_macsec_key_server_priority_ = "key-server-priority"
    oc_macsec_policies = 764028492
    oc_macsec_policies_ = "policies"
    oc_macsec_sak_encryption_errors = 1239224021
    oc_macsec_sak_encryption_errors_ = "sak-encryption-errors"
    oc_macsec_delay_protection = 1764680021
    oc_macsec_delay_protection_ = "delay-protection"
    oc_macsec_replay_protection = 1524657482
    oc_macsec_replay_protection_ = "replay-protection"
    oc_macsec_in_mkpdu = 2073301604
    oc_macsec_in_mkpdu_ = "in-mkpdu"
    oc_macsec_state = 630973766
    oc_macsec_state_ = "state"
    oc_macsec_rx_badtag_pkts = 631447530
    oc_macsec_rx_badtag_pkts_ = "rx-badtag-pkts"
    oc_macsec_sak_rekey_interval = 1360607198
    oc_macsec_sak_rekey_interval_ = "sak-rekey-interval"
    oc_macsec_in_mkpdu_bad_peer_errors = 195383445
    oc_macsec_in_mkpdu_bad_peer_errors_ = "in-mkpdu-bad-peer-errors"
    oc_macsec_in_mkpdu_validation_errors = 607472120
    oc_macsec_in_mkpdu_validation_errors_ = "in-mkpdu-validation-errors"
    oc_macsec_use_updated_eth_header = 293518806
    oc_macsec_use_updated_eth_header_ = "use-updated-eth-header"
    oc_macsec_macsec = 1063323203
    oc_macsec_macsec_ = "macsec"
    oc_macsec_sc_encrypted = 1984836898
    oc_macsec_sc_encrypted_ = "sc-encrypted"
    oc_macsec_include_icv_indicator = 1695300568
    oc_macsec_include_icv_indicator_ = "include-icv-indicator"
    oc_macsec_AES_256_CMAC = 1
    oc_macsec_AES_256_CMAC_ = "AES_256_CMAC"
    oc_macsec_enable = 448570367
    oc_macsec_enable_ = "enable"
    oc_macsec_rx_unknownsci_pkts = 224340119
    oc_macsec_rx_unknownsci_pkts_ = "rx-unknownsci-pkts"
    oc_macsec_sc_auth_only = 1977549854
    oc_macsec_sc_auth_only_ = "sc-auth-only"
    oc_macsec_out_mkpdu = 737387029
    oc_macsec_out_mkpdu_ = "out-mkpdu"
    oc_macsec_in_mkpdu_peer_list_errors = 707615749
    oc_macsec_in_mkpdu_peer_list_errors_ = "in-mkpdu-peer-list-errors"
    oc_macsec_sak_hash_errors = 1344235128
    oc_macsec_sak_hash_errors_ = "sak-hash-errors"
    oc_macsec_sc_invalid = 527149976
    oc_macsec_sc_invalid_ = "sc-invalid"
    oc_macsec_sa_valid = 1279395327
    oc_macsec_sa_valid_ = "sa-valid"
    oc_macsec_scsa_rx = 1660430984
    oc_macsec_scsa_rx_ = "scsa-rx"
    oc_macsec_confidentiality_offset = 1383962441
    oc_macsec_confidentiality_offset_ = "confidentiality-offset"
    oc_macsec_rx_nosci_pkts = 886080741
    oc_macsec_rx_nosci_pkts_ = "rx-nosci-pkts"
    oc_macsec_scsa_tx = 718953170
    oc_macsec_scsa_tx_ = "scsa-tx"
    oc_macsec_config = 2105663071
    oc_macsec_config_ = "config"
    oc_macsec_sci_tx = 1723208562
    oc_macsec_sci_tx_ = "sci-tx"
    oc_macsec_sc_valid = 2132774195
    oc_macsec_sc_valid_ = "sc-valid"
    oc_macsec_counters = 1327053922
    oc_macsec_counters_ = "counters"
    oc_macsec_in_cak_mkpdu = 1058276780
    oc_macsec_in_cak_mkpdu_ = "in-cak-mkpdu"
    oc_macsec_key_chain = 1359335192
    oc_macsec_key_chain_ = "key-chain"
    oc_macsec_name = 1998270519
    oc_macsec_name_ = "name"
    oc_macsec_mka = 1464935962
    oc_macsec_mka_ = "mka"
    oc_macsec_sak_cipher_mismatch_errors = 463852340
    oc_macsec_sak_cipher_mismatch_errors_ = "sak-cipher-mismatch-errors"
    oc_macsec_rx_untagged_pkts = 1642185061
    oc_macsec_rx_untagged_pkts_ = "rx-untagged-pkts"
    oc_macsec_sa_encrypted = 1947562407
    oc_macsec_sa_encrypted_ = "sa-encrypted"
    oc_macsec_interface = 221572658
    oc_macsec_interface_ = "interface"
    oc_macsec_AES_128_CMAC = 0
    oc_macsec_AES_128_CMAC_ = "AES_128_CMAC"
    oc_macsec_macsec_cipher_suite = 2134603552
    oc_macsec_macsec_cipher_suite_ = "macsec-cipher-suite"
    oc_macsec_sak_decryption_errors = 327158451
    oc_macsec_sak_decryption_errors_ = "sak-decryption-errors"
    oc_macsec_in_mkpdu_icv_verification_errors = 524849401
    oc_macsec_in_mkpdu_icv_verification_errors_ = "in-mkpdu-icv-verification-errors"
    oc_macsec_tx_untagged_pkts = 660501857
    oc_macsec_tx_untagged_pkts_ = "tx-untagged-pkts"
