#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-license.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-license.yang


class ns(object):
    hash = 1208096034

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/license"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/license"

    prefix = "oc-license"

