#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-platform-cpu.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-platform-cpu.yang


class ns(object):
    hash = 747192571

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/cpu"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/cpu"

    prefix = "oc-cpu"

    oc_cpu_max = 2088175689
    oc_cpu_max_ = "max"
    oc_cpu_interval = 559952988
    oc_cpu_interval_ = "interval"
    oc_cpu_min_time = 1805904672
    oc_cpu_min_time_ = "min-time"
    oc_cpu_state = 630973766
    oc_cpu_state_ = "state"
    oc_cpu_utilization = 1882370771
    oc_cpu_utilization_ = "utilization"
    oc_cpu_min = 83205090
    oc_cpu_min_ = "min"
    oc_cpu_avg = 2050512522
    oc_cpu_avg_ = "avg"
    oc_cpu_max_time = 1093347309
    oc_cpu_max_time_ = "max-time"
    oc_cpu_instant = 2051543381
    oc_cpu_instant_ = "instant"
