#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-local-routing.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-local-routing.yang


class ns(object):
    hash = 2032639807

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/local-routing"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/local-routing"

    prefix = "oc-loc-rt"

    oc_loc_rt_LOCAL_LINK = 297129746
    oc_loc_rt_LOCAL_LINK_ = "LOCAL_LINK"
    oc_loc_rt_LOCAL_DEFINED_NEXT_HOP = 1252477086
    oc_loc_rt_LOCAL_DEFINED_NEXT_HOP_ = "LOCAL_DEFINED_NEXT_HOP"
    oc_loc_rt_DROP = 1226140191
    oc_loc_rt_DROP_ = "DROP"
