#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-if-ethernet-ext.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-if-ethernet-ext.yang


class ns(object):
    hash = 1713764664

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/interfaces/ethernet-ext"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/interfaces/ethernet-ext"

    prefix = "oc-eth-ext"

    oc_eth_ext_in_frames_256_511_octets = 1388004516
    oc_eth_ext_in_frames_256_511_octets_ = "in-frames-256-511-octets"
    oc_eth_ext_in_frames_128_255_octets = 975532521
    oc_eth_ext_in_frames_128_255_octets_ = "in-frames-128-255-octets"
    oc_eth_ext_in_distribution = 1225035169
    oc_eth_ext_in_distribution_ = "in-distribution"
    oc_eth_ext_in_frames_64_octets = 292946505
    oc_eth_ext_in_frames_64_octets_ = "in-frames-64-octets"
    oc_eth_ext_in_frames_1024_1518_octets = 42346455
    oc_eth_ext_in_frames_1024_1518_octets_ = "in-frames-1024-1518-octets"
    oc_eth_ext_in_frames_65_127_octets = 686325803
    oc_eth_ext_in_frames_65_127_octets_ = "in-frames-65-127-octets"
    oc_eth_ext_in_frames_512_1023_octets = 337990356
    oc_eth_ext_in_frames_512_1023_octets_ = "in-frames-512-1023-octets"
