#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-keychain.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-keychain.yang


class ns(object):
    hash = 869243905

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/oc-keychain"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/oc-keychain"

    prefix = "oc-keychain"

    oc_keychain_tolerance = 1434023172
    oc_keychain_tolerance_ = "tolerance"
    oc_keychain_secret_key = 1737421940
    oc_keychain_secret_key_ = "secret-key"
    oc_keychain_receive_lifetime = 2104513356
    oc_keychain_receive_lifetime_ = "receive-lifetime"
    oc_keychain_keys = 305539744
    oc_keychain_keys_ = "keys"
    oc_keychain_keychains = 1322271875
    oc_keychain_keychains_ = "keychains"
    oc_keychain_state = 630973766
    oc_keychain_state_ = "state"
    oc_keychain_send_lifetime = 84392676
    oc_keychain_send_lifetime_ = "send-lifetime"
    oc_keychain_FOREVER = 0
    oc_keychain_FOREVER_ = "FOREVER"
    oc_keychain_send_and_receive = 1347196384
    oc_keychain_send_and_receive_ = "send-and-receive"
    oc_keychain_config = 2105663071
    oc_keychain_config_ = "config"
    oc_keychain_key = 1348858669
    oc_keychain_key_ = "key"
    oc_keychain_key_id = 1459848464
    oc_keychain_key_id_ = "key-id"
    oc_keychain_name = 1998270519
    oc_keychain_name_ = "name"
    oc_keychain_start_time = 84038180
    oc_keychain_start_time_ = "start-time"
    oc_keychain_keychain = 233700939
    oc_keychain_keychain_ = "keychain"
    oc_keychain_crypto_algorithm = 742525639
    oc_keychain_crypto_algorithm_ = "crypto-algorithm"
    oc_keychain_end_time = 1935053864
    oc_keychain_end_time_ = "end-time"
