#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-bgp.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-bgp.yang


class ns(object):
    hash = 211080827

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/bgp"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/bgp"

    prefix = "oc-bgp"

    oc_bgp_IPV4_NODE_ADDRESS = 3
    oc_bgp_IPV4_NODE_ADDRESS_ = "IPV4_NODE_ADDRESS"
    oc_bgp_IPV6_LOCAL_REMOTE_ADDR = 8
    oc_bgp_IPV6_LOCAL_REMOTE_ADDR_ = "IPV6_LOCAL_REMOTE_ADDR"
    oc_bgp_HELPER_ONLY = 0
    oc_bgp_HELPER_ONLY_ = "HELPER_ONLY"
    oc_bgp_IPV6_SID = 2
    oc_bgp_IPV6_SID_ = "IPV6_SID"
    oc_bgp_ESTABLISHED = 5
    oc_bgp_ESTABLISHED_ = "ESTABLISHED"
    oc_bgp_ACTIVE = 2
    oc_bgp_ACTIVE_ = "ACTIVE"
    oc_bgp_IPV6_NODE_ADDRESS = 4
    oc_bgp_IPV6_NODE_ADDRESS_ = "IPV6_NODE_ADDRESS"
    oc_bgp_IDLE = 0
    oc_bgp_IDLE_ = "IDLE"
    oc_bgp_REMOTE_HELPER = 2
    oc_bgp_REMOTE_HELPER_ = "REMOTE_HELPER"
    oc_bgp_MPLS_SID = 1
    oc_bgp_MPLS_SID_ = "MPLS_SID"
    oc_bgp_OPENSENT = 3
    oc_bgp_OPENSENT_ = "OPENSENT"
    oc_bgp_IPV4_LOCAL_REMOTE_ADDR = 6
    oc_bgp_IPV4_LOCAL_REMOTE_ADDR_ = "IPV4_LOCAL_REMOTE_ADDR"
    oc_bgp_CONNECT = 1
    oc_bgp_CONNECT_ = "CONNECT"
    oc_bgp_IPV4_LOCAL_INTF_ID = 5
    oc_bgp_IPV4_LOCAL_INTF_ID_ = "IPV4_LOCAL_INTF_ID"
    oc_bgp_OPENCONFIRM = 4
    oc_bgp_OPENCONFIRM_ = "OPENCONFIRM"
    oc_bgp_IPV6_LOCAL_INTF_ID = 7
    oc_bgp_IPV6_LOCAL_INTF_ID_ = "IPV6_LOCAL_INTF_ID"
    oc_bgp_BILATERAL = 1
    oc_bgp_BILATERAL_ = "BILATERAL"
