#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-if-ip-ext.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-if-ip-ext.yang


class ns(object):
    hash = 501595077

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/interfaces/ip-ext"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/interfaces/ip-ext"

    prefix = "oc-ip-ext"

    oc_ip_ext_temporary_preferred_lifetime = 1399830185
    oc_ip_ext_temporary_preferred_lifetime_ = "temporary-preferred-lifetime"
    oc_ip_ext_autoconf = 78817100
    oc_ip_ext_autoconf_ = "autoconf"
    oc_ip_ext_create_global_addresses = 1061463433
    oc_ip_ext_create_global_addresses_ = "create-global-addresses"
    oc_ip_ext_state = 630973766
    oc_ip_ext_state_ = "state"
    oc_ip_ext_temporary_valid_lifetime = 710688618
    oc_ip_ext_temporary_valid_lifetime_ = "temporary-valid-lifetime"
    oc_ip_ext_create_temporary_addresses = 575599870
    oc_ip_ext_create_temporary_addresses_ = "create-temporary-addresses"
    oc_ip_ext_config = 2105663071
    oc_ip_ext_config_ = "config"
