#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-mpls-ldp.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-mpls-ldp.yang


class ns(object):
    hash = 620255735

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ldp"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/ldp"

    prefix = "oc-ldp"

    oc_ldp_NON_EXISTENT = 0
    oc_ldp_NON_EXISTENT_ = "NON_EXISTENT"
    oc_ldp_INITIALIZED = 1
    oc_ldp_INITIALIZED_ = "INITIALIZED"
    oc_ldp_IPV4 = 0
    oc_ldp_IPV4_ = "IPV4"
    oc_ldp_TARGETED = 1
    oc_ldp_TARGETED_ = "TARGETED"
    oc_ldp_IPV6 = 1
    oc_ldp_IPV6_ = "IPV6"
    oc_ldp_OPENREC = 2
    oc_ldp_OPENREC_ = "OPENREC"
    oc_ldp_OPENSENT = 3
    oc_ldp_OPENSENT_ = "OPENSENT"
    oc_ldp_OPERATIONAL = 4
    oc_ldp_OPERATIONAL_ = "OPERATIONAL"
    oc_ldp_LINK = 0
    oc_ldp_LINK_ = "LINK"
