#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-routing-policy.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-routing-policy.yang


class ns(object):
    hash = 1214832453

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/routing-policy"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/routing-policy"

    prefix = "oc-rpol"

    oc_rpol_neighbor_set = 1237696180
    oc_rpol_neighbor_set_ = "neighbor-set"
    oc_rpol_tag_value = 633774587
    oc_rpol_tag_value_ = "tag-value"
    oc_rpol_mode = 575893728
    oc_rpol_mode_ = "mode"
    oc_rpol_routing_policy = 1803236680
    oc_rpol_routing_policy_ = "routing-policy"
    oc_rpol_prefix = 1408440115
    oc_rpol_prefix_ = "prefix"
    oc_rpol_REFERENCE = 1
    oc_rpol_REFERENCE_ = "REFERENCE"
    oc_rpol_tag = 21925559
    oc_rpol_tag_ = "tag"
    oc_rpol_ip_prefix = 289539202
    oc_rpol_ip_prefix_ = "ip-prefix"
    oc_rpol_subinterface = 1294223328
    oc_rpol_subinterface_ = "subinterface"
    oc_rpol_neighbor_sets = 477381007
    oc_rpol_neighbor_sets_ = "neighbor-sets"
    oc_rpol_set_tag = 177790014
    oc_rpol_set_tag_ = "set-tag"
    oc_rpol_conditions = 975488036
    oc_rpol_conditions_ = "conditions"
    oc_rpol_IPV4 = 0
    oc_rpol_IPV4_ = "IPV4"
    oc_rpol_tag_set = 196489743
    oc_rpol_tag_set_ = "tag-set"
    oc_rpol_state = 630973766
    oc_rpol_state_ = "state"
    oc_rpol_statement = 2020184598
    oc_rpol_statement_ = "statement"
    oc_rpol_match_interface = 1869116648
    oc_rpol_match_interface_ = "match-interface"
    oc_rpol_match_set_options = 517327943
    oc_rpol_match_set_options_ = "match-set-options"
    oc_rpol_prefix_set = 1234120084
    oc_rpol_prefix_set_ = "prefix-set"
    oc_rpol_IPV6 = 1
    oc_rpol_IPV6_ = "IPV6"
    oc_rpol_INLINE = 0
    oc_rpol_INLINE_ = "INLINE"
    oc_rpol_match_neighbor_set = 2124471048
    oc_rpol_match_neighbor_set_ = "match-neighbor-set"
    oc_rpol_match_prefix_set = 499359715
    oc_rpol_match_prefix_set_ = "match-prefix-set"
    oc_rpol_prefixes = 1405994391
    oc_rpol_prefixes_ = "prefixes"
    oc_rpol_policy_definition = 927599493
    oc_rpol_policy_definition_ = "policy-definition"
    oc_rpol_prefix_sets = 2035865838
    oc_rpol_prefix_sets_ = "prefix-sets"
    oc_rpol_match_tag_set = 2016437036
    oc_rpol_match_tag_set_ = "match-tag-set"
    oc_rpol_reference = 1577200258
    oc_rpol_reference_ = "reference"
    oc_rpol_config = 2105663071
    oc_rpol_config_ = "config"
    oc_rpol_MIXED = 2
    oc_rpol_MIXED_ = "MIXED"
    oc_rpol_inline = 1987224790
    oc_rpol_inline_ = "inline"
    oc_rpol_name = 1998270519
    oc_rpol_name_ = "name"
    oc_rpol_masklength_range = 497977763
    oc_rpol_masklength_range_ = "masklength-range"
    oc_rpol_ACCEPT_ROUTE = 0
    oc_rpol_ACCEPT_ROUTE_ = "ACCEPT_ROUTE"
    oc_rpol_statements = 1505610507
    oc_rpol_statements_ = "statements"
    oc_rpol_defined_sets = 952897476
    oc_rpol_defined_sets_ = "defined-sets"
    oc_rpol_policy_result = 1672578308
    oc_rpol_policy_result_ = "policy-result"
    oc_rpol_install_protocol_eq = 1943059095
    oc_rpol_install_protocol_eq_ = "install-protocol-eq"
    oc_rpol_interface = 221572658
    oc_rpol_interface_ = "interface"
    oc_rpol_address = 1266954393
    oc_rpol_address_ = "address"
    oc_rpol_REJECT_ROUTE = 1
    oc_rpol_REJECT_ROUTE_ = "REJECT_ROUTE"
    oc_rpol_actions = 2034878685
    oc_rpol_actions_ = "actions"
    oc_rpol_policy_definitions = 492676988
    oc_rpol_policy_definitions_ = "policy-definitions"
    oc_rpol_call_policy = 1718898824
    oc_rpol_call_policy_ = "call-policy"
    oc_rpol_tag_sets = 381894197
    oc_rpol_tag_sets_ = "tag-sets"
