#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-terminal-device-property-types.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-terminal-device-property-types.yang


class ns(object):
    hash = 1912288498

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://example.net/yang/openconfig-terminal-device-property-types"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://example.net/yang/openconfig-terminal-device-property-types"

    prefix = "oc-opt-term-prop-types"

    oc_opt_term_prop_types_ADJUSTMENT_GRANULARITY = 46926221
    oc_opt_term_prop_types_ADJUSTMENT_GRANULARITY_ = "ADJUSTMENT_GRANULARITY"
    oc_opt_term_prop_types_MODULATION_FORMAT_64QAM = 323334316
    oc_opt_term_prop_types_MODULATION_FORMAT_64QAM_ = "MODULATION_FORMAT_64QAM"
    oc_opt_term_prop_types_UNSPECIFIED = 723886692
    oc_opt_term_prop_types_UNSPECIFIED_ = "UNSPECIFIED"
    oc_opt_term_prop_types_MODULATION_FORMAT_DP_32QAM = 88555661
    oc_opt_term_prop_types_MODULATION_FORMAT_DP_32QAM_ = "MODULATION_FORMAT_DP_32QAM"
    oc_opt_term_prop_types_SHAPING_TYPE = 1588053289
    oc_opt_term_prop_types_SHAPING_TYPE_ = "SHAPING_TYPE"
    oc_opt_term_prop_types_MODULATION_FORMAT_BPSK = 905979364
    oc_opt_term_prop_types_MODULATION_FORMAT_BPSK_ = "MODULATION_FORMAT_BPSK"
    oc_opt_term_prop_types_TRANSCEIVER_MODE_TYPE_EXPLICIT = 90517129
    oc_opt_term_prop_types_TRANSCEIVER_MODE_TYPE_EXPLICIT_ = "TRANSCEIVER_MODE_TYPE_EXPLICIT"
    oc_opt_term_prop_types_MODULATION_FORMAT_DPSK = 364023509
    oc_opt_term_prop_types_MODULATION_FORMAT_DPSK_ = "MODULATION_FORMAT_DPSK"
    oc_opt_term_prop_types_MODULATION_FORMAT_DC_DP_64QAM = 1656004684
    oc_opt_term_prop_types_MODULATION_FORMAT_DC_DP_64QAM_ = "MODULATION_FORMAT_DC_DP_64QAM"
    oc_opt_term_prop_types_CD_PS_NM = 14600909
    oc_opt_term_prop_types_CD_PS_NM_ = "CD_PS_NM"
    oc_opt_term_prop_types_TRANSCEIVER_MODE_TYPE_STANDARD = 1131802017
    oc_opt_term_prop_types_TRANSCEIVER_MODE_TYPE_STANDARD_ = "TRANSCEIVER_MODE_TYPE_STANDARD"
    oc_opt_term_prop_types_FEC_E = 891045592
    oc_opt_term_prop_types_FEC_E_ = "FEC_E"
    oc_opt_term_prop_types_MODULATION_FORMAT_PAM8 = 1376341307
    oc_opt_term_prop_types_MODULATION_FORMAT_PAM8_ = "MODULATION_FORMAT_PAM8"
    oc_opt_term_prop_types_FEC_G = 1717115823
    oc_opt_term_prop_types_FEC_G_ = "FEC_G"
    oc_opt_term_prop_types_RC = 1595782611
    oc_opt_term_prop_types_RC_ = "RC"
    oc_opt_term_prop_types_MODULATION_FORMAT_32QAM = 1127783280
    oc_opt_term_prop_types_MODULATION_FORMAT_32QAM_ = "MODULATION_FORMAT_32QAM"
    oc_opt_term_prop_types_PDL_DB = 523741302
    oc_opt_term_prop_types_PDL_DB_ = "PDL_DB"
    oc_opt_term_prop_types_MODULATION_FORMAT_QPSK = 962781047
    oc_opt_term_prop_types_MODULATION_FORMAT_QPSK_ = "MODULATION_FORMAT_QPSK"
    oc_opt_term_prop_types_FEC_C = 1966462633
    oc_opt_term_prop_types_FEC_C_ = "FEC_C"
    oc_opt_term_prop_types_G_50GHZ = 1063038026
    oc_opt_term_prop_types_G_50GHZ_ = "G_50GHZ"
    oc_opt_term_prop_types_RRC = 140553445
    oc_opt_term_prop_types_RRC_ = "RRC"
    oc_opt_term_prop_types_MODULATION_FORMAT_DC_DP_16QAM = 385032979
    oc_opt_term_prop_types_MODULATION_FORMAT_DC_DP_16QAM_ = "MODULATION_FORMAT_DC_DP_16QAM"
    oc_opt_term_prop_types_FEC = 1824304257
    oc_opt_term_prop_types_FEC_ = "FEC"
    oc_opt_term_prop_types_G_3_125GHZ = 756935463
    oc_opt_term_prop_types_G_3_125GHZ_ = "G_3_125GHZ"
    oc_opt_term_prop_types_G_25GHZ = 871132125
    oc_opt_term_prop_types_G_25GHZ_ = "G_25GHZ"
    oc_opt_term_prop_types_CWDM = 315259850
    oc_opt_term_prop_types_CWDM_ = "CWDM"
    oc_opt_term_prop_types_FEC_OTHER = 1234385461
    oc_opt_term_prop_types_FEC_OTHER_ = "FEC_OTHER"
    oc_opt_term_prop_types_FLEX = 1453942473
    oc_opt_term_prop_types_FLEX_ = "FLEX"
    oc_opt_term_prop_types_MODULATION_FORMAT_DC_DP_8QAM = 1784803324
    oc_opt_term_prop_types_MODULATION_FORMAT_DC_DP_8QAM_ = "MODULATION_FORMAT_DC_DP_8QAM"
    oc_opt_term_prop_types_TRANSCEIVER_MODE_TYPE = 1905974487
    oc_opt_term_prop_types_TRANSCEIVER_MODE_TYPE_ = "TRANSCEIVER_MODE_TYPE"
    oc_opt_term_prop_types_MODULATION_FORMAT_PAM4 = 7025561
    oc_opt_term_prop_types_MODULATION_FORMAT_PAM4_ = "MODULATION_FORMAT_PAM4"
    oc_opt_term_prop_types_FEC_O = 2087256938
    oc_opt_term_prop_types_FEC_O_ = "FEC_O"
    oc_opt_term_prop_types_PMD_PS = 23067444
    oc_opt_term_prop_types_PMD_PS_ = "PMD_PS"
    oc_opt_term_prop_types_MODULATION_FORMAT_8QAM = 663136940
    oc_opt_term_prop_types_MODULATION_FORMAT_8QAM_ = "MODULATION_FORMAT_8QAM"
    oc_opt_term_prop_types_MODULATION_FORMAT_16QAM = 2087269376
    oc_opt_term_prop_types_MODULATION_FORMAT_16QAM_ = "MODULATION_FORMAT_16QAM"
    oc_opt_term_prop_types_MODULATION_FORMAT_DP_8QAM = 404959224
    oc_opt_term_prop_types_MODULATION_FORMAT_DP_8QAM_ = "MODULATION_FORMAT_DP_8QAM"
    oc_opt_term_prop_types_MODULATION_FORMAT_DP_16QAM = 1405104528
    oc_opt_term_prop_types_MODULATION_FORMAT_DP_16QAM_ = "MODULATION_FORMAT_DP_16QAM"
    oc_opt_term_prop_types_MODULATION_FORMAT_PROPRIETARY = 1596804338
    oc_opt_term_prop_types_MODULATION_FORMAT_PROPRIETARY_ = "MODULATION_FORMAT_PROPRIETARY"
    oc_opt_term_prop_types_GRID_TYPE = 1089936915
    oc_opt_term_prop_types_GRID_TYPE_ = "GRID_TYPE"
    oc_opt_term_prop_types_FEC_HD = 1863035650
    oc_opt_term_prop_types_FEC_HD_ = "FEC_HD"
    oc_opt_term_prop_types_UNCONSTRAINED = 298224154
    oc_opt_term_prop_types_UNCONSTRAINED_ = "UNCONSTRAINED"
    oc_opt_term_prop_types_G_6_25GHZ = 947882027
    oc_opt_term_prop_types_G_6_25GHZ_ = "G_6_25GHZ"
    oc_opt_term_prop_types_G_100GHZ = 612063798
    oc_opt_term_prop_types_G_100GHZ_ = "G_100GHZ"
    oc_opt_term_prop_types_DWDM = 11631793
    oc_opt_term_prop_types_DWDM_ = "DWDM"
    oc_opt_term_prop_types_MODULATION_FORMAT = 1230767504
    oc_opt_term_prop_types_MODULATION_FORMAT_ = "MODULATION_FORMAT"
    oc_opt_term_prop_types_MODULATION_FORMAT_DP_QPSK = 641392521
    oc_opt_term_prop_types_MODULATION_FORMAT_DP_QPSK_ = "MODULATION_FORMAT_DP_QPSK"
    oc_opt_term_prop_types_OFF = 2072370329
    oc_opt_term_prop_types_OFF_ = "OFF"
    oc_opt_term_prop_types_MODULATION_FORMAT_DC_DP_32QAM = 1664096805
    oc_opt_term_prop_types_MODULATION_FORMAT_DC_DP_32QAM_ = "MODULATION_FORMAT_DC_DP_32QAM"
    oc_opt_term_prop_types_IMPAIRMENT_TYPE = 1943676821
    oc_opt_term_prop_types_IMPAIRMENT_TYPE_ = "IMPAIRMENT_TYPE"
    oc_opt_term_prop_types_GRIDLESS = 984583523
    oc_opt_term_prop_types_GRIDLESS_ = "GRIDLESS"
    oc_opt_term_prop_types_MODULATION_FORMAT_DP_64QAM = 780931619
    oc_opt_term_prop_types_MODULATION_FORMAT_DP_64QAM_ = "MODULATION_FORMAT_DP_64QAM"
    oc_opt_term_prop_types_G_12_5GHZ = 107827371
    oc_opt_term_prop_types_G_12_5GHZ_ = "G_12_5GHZ"
