#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-platform-software.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-platform-software.yang


class ns(object):
    hash = 1211090896

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/software-module"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/platform/software-module"

    prefix = "oc-sw-module"

    oc_sw_module_USERSPACE_PACKAGE_BUNDLE = 1851031134
    oc_sw_module_USERSPACE_PACKAGE_BUNDLE_ = "USERSPACE_PACKAGE_BUNDLE"
    oc_sw_module_USERSPACE_PACKAGE = 1639281304
    oc_sw_module_USERSPACE_PACKAGE_ = "USERSPACE_PACKAGE"
    oc_sw_module_module_type = 1995105902
    oc_sw_module_module_type_ = "module-type"
    oc_sw_module_SOFTWARE_MODULE_TYPE = 111937536
    oc_sw_module_SOFTWARE_MODULE_TYPE_ = "SOFTWARE_MODULE_TYPE"
