#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-vlan.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-vlan.yang


class ns(object):
    hash = 228085247

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/vlan"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/vlan"

    prefix = "oc-vlan"

    oc_vlan_trunk_vlans = 1077818890
    oc_vlan_trunk_vlans_ = "trunk-vlans"
    oc_vlan_inner_low_vlan_id = 1559851846
    oc_vlan_inner_low_vlan_id_ = "inner-low-vlan-id"
    oc_vlan_vlan_id = 1443431623
    oc_vlan_vlan_id_ = "vlan-id"
    oc_vlan_single_tagged_range = 703910030
    oc_vlan_single_tagged_range_ = "single-tagged-range"
    oc_vlan_outer_vlan_id = 2008251797
    oc_vlan_outer_vlan_id_ = "outer-vlan-id"
    oc_vlan_inner_vlan_ids = 303498286
    oc_vlan_inner_vlan_ids_ = "inner-vlan-ids"
    oc_vlan_outer_high_vlan_id = 1823628390
    oc_vlan_outer_high_vlan_id_ = "outer-high-vlan-id"
    oc_vlan_switched_vlan = 1368499734
    oc_vlan_switched_vlan_ = "switched-vlan"
    oc_vlan_vlan = 71481437
    oc_vlan_vlan_ = "vlan"
    oc_vlan_interface_mode = 1229050048
    oc_vlan_interface_mode_ = "interface-mode"
    oc_vlan_inner_vlan_id = 333468475
    oc_vlan_inner_vlan_id_ = "inner-vlan-id"
    oc_vlan_SUSPENDED = 1
    oc_vlan_SUSPENDED_ = "SUSPENDED"
    oc_vlan_double_tagged_inner_range = 884213616
    oc_vlan_double_tagged_inner_range_ = "double-tagged-inner-range"
    oc_vlan_inner_high_vlan_id = 253530737
    oc_vlan_inner_high_vlan_id_ = "inner-high-vlan-id"
    oc_vlan_state = 630973766
    oc_vlan_state_ = "state"
    oc_vlan_native_vlan = 1159886695
    oc_vlan_native_vlan_ = "native-vlan"
    oc_vlan_vlan_stack_action = 1541409462
    oc_vlan_vlan_stack_action_ = "vlan-stack-action"
    oc_vlan_double_tagged_inner_outer_range = 177199481
    oc_vlan_double_tagged_inner_outer_range_ = "double-tagged-inner-outer-range"
    oc_vlan_ACTIVE = 0
    oc_vlan_ACTIVE_ = "ACTIVE"
    oc_vlan_match = 1501964518
    oc_vlan_match_ = "match"
    oc_vlan_low_vlan_id = 2143350458
    oc_vlan_low_vlan_id_ = "low-vlan-id"
    oc_vlan_single_tagged = 1338140550
    oc_vlan_single_tagged_ = "single-tagged"
    oc_vlan_config = 2105663071
    oc_vlan_config_ = "config"
    oc_vlan_outer_vlan_ids = 2044724970
    oc_vlan_outer_vlan_ids_ = "outer-vlan-ids"
    oc_vlan_high_vlan_id = 190189862
    oc_vlan_high_vlan_id_ = "high-vlan-id"
    oc_vlan_egress_mapping = 1659599184
    oc_vlan_egress_mapping_ = "egress-mapping"
    oc_vlan_double_tagged = 30146062
    oc_vlan_double_tagged_ = "double-tagged"
    oc_vlan_routed_vlan = 1375184969
    oc_vlan_routed_vlan_ = "routed-vlan"
    oc_vlan_tpid = 1809362859
    oc_vlan_tpid_ = "tpid"
    oc_vlan_single_tagged_list = 890964007
    oc_vlan_single_tagged_list_ = "single-tagged-list"
    oc_vlan_access_vlan = 2014822852
    oc_vlan_access_vlan_ = "access-vlan"
    oc_vlan_outer_low_vlan_id = 1166184422
    oc_vlan_outer_low_vlan_id_ = "outer-low-vlan-id"
    oc_vlan_double_tagged_outer_range = 454624053
    oc_vlan_double_tagged_outer_range_ = "double-tagged-outer-range"
    oc_vlan_double_tagged_inner_list = 897542526
    oc_vlan_double_tagged_inner_list_ = "double-tagged-inner-list"
    oc_vlan_ingress_mapping = 367656293
    oc_vlan_ingress_mapping_ = "ingress-mapping"
    oc_vlan_vlan_ids = 310768076
    oc_vlan_vlan_ids_ = "vlan-ids"
    oc_vlan_double_tagged_outer_list = 1425449404
    oc_vlan_double_tagged_outer_list_ = "double-tagged-outer-list"
