#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-lldp.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-lldp.yang


class ns(object):
    hash = 591569475

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/lldp"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/lldp"

    prefix = "oc-lldp"

    oc_lldp_neighbor = 81789621
    oc_lldp_neighbor_ = "neighbor"
    oc_lldp_interfaces = 321503962
    oc_lldp_interfaces_ = "interfaces"
    oc_lldp_enabled = 197426095
    oc_lldp_enabled_ = "enabled"
    oc_lldp_last_update = 498080631
    oc_lldp_last_update_ = "last-update"
    oc_lldp_frame_out = 899192982
    oc_lldp_frame_out_ = "frame-out"
    oc_lldp_port_id_type = 1294387739
    oc_lldp_port_id_type_ = "port-id-type"
    oc_lldp_management_address_type = 1070023607
    oc_lldp_management_address_type_ = "management-address-type"
    oc_lldp_value = 864367181
    oc_lldp_value_ = "value"
    oc_lldp_state = 630973766
    oc_lldp_state_ = "state"
    oc_lldp_neighbors = 1478644450
    oc_lldp_neighbors_ = "neighbors"
    oc_lldp_hello_timer = 1869518339
    oc_lldp_hello_timer_ = "hello-timer"
    oc_lldp_tlv_accepted = 1856541892
    oc_lldp_tlv_accepted_ = "tlv-accepted"
    oc_lldp_oui_subtype = 960442680
    oc_lldp_oui_subtype_ = "oui-subtype"
    oc_lldp_system_description = 1651773485
    oc_lldp_system_description_ = "system-description"
    oc_lldp_capabilities = 1381570067
    oc_lldp_capabilities_ = "capabilities"
    oc_lldp_age = 304093784
    oc_lldp_age_ = "age"
    oc_lldp_tlv_discard = 75606479
    oc_lldp_tlv_discard_ = "tlv-discard"
    oc_lldp_type = 2040883914
    oc_lldp_type_ = "type"
    oc_lldp_entries_aged_out = 818798602
    oc_lldp_entries_aged_out_ = "entries-aged-out"
    oc_lldp_capability = 1251322185
    oc_lldp_capability_ = "capability"
    oc_lldp_port_id = 411479338
    oc_lldp_port_id_ = "port-id"
    oc_lldp_ttl = 774234709
    oc_lldp_ttl_ = "ttl"
    oc_lldp_oui = 169238003
    oc_lldp_oui_ = "oui"
    oc_lldp_chassis_id_type = 2064781464
    oc_lldp_chassis_id_type_ = "chassis-id-type"
    oc_lldp_port_description = 1466459667
    oc_lldp_port_description_ = "port-description"
    oc_lldp_system_name = 1975516496
    oc_lldp_system_name_ = "system-name"
    oc_lldp_config = 2105663071
    oc_lldp_config_ = "config"
    oc_lldp_tlv_unknown = 546776942
    oc_lldp_tlv_unknown_ = "tlv-unknown"
    oc_lldp_chassis_id = 1476535866
    oc_lldp_chassis_id_ = "chassis-id"
    oc_lldp_counters = 1327053922
    oc_lldp_counters_ = "counters"
    oc_lldp_suppress_tlv_advertisement = 1552375923
    oc_lldp_suppress_tlv_advertisement_ = "suppress-tlv-advertisement"
    oc_lldp_lldp = 830250803
    oc_lldp_lldp_ = "lldp"
    oc_lldp_frame_discard = 1933515315
    oc_lldp_frame_discard_ = "frame-discard"
    oc_lldp_name = 1998270519
    oc_lldp_name_ = "name"
    oc_lldp_management_address = 613978086
    oc_lldp_management_address_ = "management-address"
    oc_lldp_custom_tlvs = 1472881104
    oc_lldp_custom_tlvs_ = "custom-tlvs"
    oc_lldp_frame_in = 497567735
    oc_lldp_frame_in_ = "frame-in"
    oc_lldp_interface = 221572658
    oc_lldp_interface_ = "interface"
    oc_lldp_id = 1279252765
    oc_lldp_id_ = "id"
    oc_lldp_frame_error_in = 511909285
    oc_lldp_frame_error_in_ = "frame-error-in"
    oc_lldp_tlv = 1250745731
    oc_lldp_tlv_ = "tlv"
    oc_lldp_frame_error_out = 1736170451
    oc_lldp_frame_error_out_ = "frame-error-out"
    oc_lldp_last_clear = 1168907511
    oc_lldp_last_clear_ = "last-clear"
