#
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
# This file has been auto-generated by the confdc compiler.
# Source: ../load-dir/openconfig-messages.fxs
# BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
#

# Autogenerated namespace class for YANG module openconfig-messages.yang


class ns(object):
    hash = 86236328

    id = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/messages"

    uri = "_oc-all-nc-1.0:oc-all-nc-1.0#http://openconfig.net/yang/messages"

    prefix = "oc-messages"

    oc_messages_debug_entries = 1494426096
    oc_messages_debug_entries_ = "debug-entries"
    oc_messages_msg = 381476903
    oc_messages_msg_ = "msg"
    oc_messages_msgid = 1175192235
    oc_messages_msgid_ = "msgid"
    oc_messages_enabled = 197426095
    oc_messages_enabled_ = "enabled"
    oc_messages_messages = 1588018753
    oc_messages_messages_ = "messages"
    oc_messages_app_name = 1425497104
    oc_messages_app_name_ = "app-name"
    oc_messages_state = 630973766
    oc_messages_state_ = "state"
    oc_messages_priority = 1346277862
    oc_messages_priority_ = "priority"
    oc_messages_procid = 757462765
    oc_messages_procid_ = "procid"
    oc_messages_config = 2105663071
    oc_messages_config_ = "config"
    oc_messages_service = 855380710
    oc_messages_service_ = "service"
    oc_messages_message = 1674281495
    oc_messages_message_ = "message"
    oc_messages_DEBUG_SERVICE = 1110658352
    oc_messages_DEBUG_SERVICE_ = "DEBUG_SERVICE"
    oc_messages_debug_service = 250426212
    oc_messages_debug_service_ = "debug-service"
    oc_messages_severity = 483607279
    oc_messages_severity_ = "severity"
